#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-location-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# search_places: Search for places using Amazon Location Service geo-places search_text API. Geocode the query using the geocode API to get BiasPosition. If no results, try a bounding box filter. Includes contact info and opening hours if present. Output is standardized and includes all fields, even if empty or not available.
# Usage: search_places <query> <max_results> <mode>
search_places() {
    aws location search-place-index-for-text \
        --index-name "$QUERY" \
        --text "$QUERY" \
        --max-results "$MAX_RESULTS"
}


# get_place: Get details for a place using Amazon Location Service geo-places get_place API. Output is standardized and includes all fields, even if empty or not available.
# Usage: get_place <place_id> <mode>
get_place() {
    aws location get-place \
        --place-id "$PLACE_ID" \
        --index-name "$MODE"
}


# reverse_geocode: Reverse geocode coordinates to an address using Amazon Location Service geo-places reverse_geocode API.
# Usage: reverse_geocode <longitude> <latitude>
reverse_geocode() {
    aws location search-place-index-for-position \
        --index-name "$DEFAULT" \
        --position "$LONGITUDE,LATITUDE"
}


# geocode: Get coordinates for a location name or address using Amazon Location Service geo-places geocode API.
# Usage: geocode <location>
geocode() {
    aws location search-place-index-for-text \
        --index-name "$LOCATION" \
        --text "$LOCATION"
}


# search_nearby: Search for places near a location using Amazon Location Service geo-places search_nearby API. If no results, expand the radius up to max_radius. Output is standardized and includes all fields, even if empty or not available.
# Usage: search_nearby <longitude> <latitude> <max_results> <query> <radius>
search_nearby() {
    aws location search-place-index-for-position \
        --index-name "$QUERY" \
        --position "$['LONGITUDE', 'LATITUDE']" \
        --max-results "$MAX_RESULTS" \
        --radius-in-meters "$RADIUS"
}


# search_places_open_now: Search for places that are open now using Amazon Location Service geo-places search_text API and filter by opening hours. If no open places, expand the search radius up to max_radius. Uses BiasPosition from geocode.
# Usage: search_places_open_now <query> <initial_radius>
search_places_open_now() {
    aws location search-place-index-for-text \
        --index-name "$QUERY" \
        --text "$QUERY" \
        --bias-position "$BIAS_POSITION" \
        --max-results "$MAX_RESULTS" \
        --filter-bbox "$FILTER_BBOX"
}


# calculate_route: Calculate a route and return summary info and turn-by-turn directions.

    Parameters:
        departure_position: [lon, lat]
        destination_position: [lon, lat]
        travel_mode: 'Car', 'Truck', 'Walking', or 'Bicycle' (default: 'Car')
        optimize_for: 'FastestRoute' or 'ShortestRoute' (default: 'FastestRoute')

    Returns:
        dict with distance, duration, and turn_by_turn directions (list of step summaries).
    
# Usage: calculate_route <departure_position> <destination_position> <travel_mode> <optimize_for>
calculate_route() {
    aws location calculate-route \
        --departure-position "$DEPARTURE_POSITION" \
        --destination-position "$DESTINATION_POSITION" \
        --travel-mode "$TRAVEL_MODE" \
        --optimize-for "$OPTIMIZE_FOR"
}


# optimize_waypoints: Optimize the order of waypoints using Amazon Location Service geo-routes optimize_waypoints API (V2).

    Returns summary (optimized order, total distance, duration, etc.) or full response if mode='raw'.
    
# Usage: optimize_waypoints <origin_position> <destination_position> <waypoints> <travel_mode> <mode>
optimize_waypoints() {
    aws location calculate-route \
        --calculator-name "$CTX.CONFIG.CALCULATOR_NAME" \
        --departure-position "$ORIGIN_POSITION" \
        --destination-position "$DESTINATION_POSITION" \
        --waypoints "$WAYPOINTS" \
        --travel-mode "$TRAVEL_MODE"
}


