#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-bedrock-kb-retrieval-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# ListKnowledgeBases: List all available Amazon Bedrock Knowledge Bases and their data sources.

    This tool returns a mapping of knowledge base IDs to their details, including:
    - name: The human-readable name of the knowledge base
    - description: The description of the knowledge base
    - data_sources: A list of data sources within the knowledge base, each with:
      - id: The unique identifier of the data source
      - name: The human-readable name of the data source

    ## Example response structure:
    ```json
    {
        "kb-12345": {
            "name": "Customer Support KB",
            "description": "Knowledge base containing customer support documentation and FAQs",
            "data_sources": [
                {"id": "ds-abc123", "name": "Technical Documentation"},
                {"id": "ds-def456", "name": "FAQs"}
            ]
        },
        "kb-67890": {
            "name": "Product Information KB",
            "description": "Comprehensive product specifications and details",
            "data_sources": [
                {"id": "ds-ghi789", "name": "Product Specifications"}
            ]
        }
    }
    ```

    ## How to use this information:
    1. Extract the knowledge base IDs (like "kb-12345") for use with the QueryKnowledgeBases tool
    2. Note the data source IDs if you want to filter queries to specific data sources
    3. Use the names to determine which knowledge base and data source(s) are most relevant to the user's query
    
# Usage: ListKnowledgeBases
ListKnowledgeBases() {
    aws bedrock-agent list-knowledge-bases \
}


# QueryKnowledgeBases: Query an Amazon Bedrock Knowledge Base using natural language.

    ## Usage Requirements
    - You MUST first use the ListKnowledgeBases tool to get valid knowledge base IDs
    - You can query different knowledge bases or make multiple queries to the same knowledge base

    ## Query Tips
    - Use clear, specific natural language queries for best results
    - You can use this tool MULTIPLE TIMES with different queries to gather comprehensive information
    - Break complex questions into multiple focused queries
    - Consider querying for factual information and explanations separately

    ## Tool output format
    The response contains multiple JSON objects (one per line), each representing a retrieved document with:
    - content: The text content of the document
    - location: The source location of the document
    - score: The relevance score of the document


    ## Interpretation Best Practices
    1. Extract and combine key information from multiple results
    2. Consider the source and relevance score when evaluating information
    3. Use follow-up queries to clarify ambiguous or incomplete information
    4. If the response is not relevant, try a different query, knowledge base, and/or data source
    5. After a few attempts, ask the user for clarification or a different query.
    
# Usage: QueryKnowledgeBases <query> <knowledge_base_id> <number_of_results> <reranking> <reranking_model_name> <data_source_ids>
QueryKnowledgeBases() {
    aws bedrock-agent-runtime retrieve \
        --knowledge-base-id "$KNOWLEDGE_BASE_ID" \
        --retrieval-query "$QUERY" \
        --max-results "$NUMBER_OF_RESULTS" \
        --data-source-ids "$DATA_SOURCE_IDS"
}


