#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-neptune-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# get_graph_schema: Get the schema for the graph including the vertex and edge labels as well as the
    (vertex)-[edge]->(vertex) combinations.
    
# Usage: get_graph_schema
get_graph_schema() {
    aws neptune get-graph-schema \
}


# run_opencypher_query: Executes the provided openCypher against the graph.
# Usage: run_opencypher_query <query> <parameters>
run_opencypher_query() {
    aws neptune execute-open-cypher-query \
        --query "$QUERY" \
        --parameters "$PARAMETERS"
}


# run_gremlin_query: Executes the provided Tinkerpop Gremlin against the graph.
# Usage: run_gremlin_query <query>
run_gremlin_query() {
    aws neptune execute-gremlin-query \
        --query "$QUERY"
}


