#!/usr/bin/env bash
# Auto-generated AWS CLI functions for aws-cloudformation-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# get_resource_schema_information: Get schema information for an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")

    Returns:
        The resource schema information
    
# Usage: get_resource_schema_information <resource_type> <region>
get_resource_schema_information() {
    aws cloudformation describe-type \
        --type "$RESOURCE_TYPE" \
        --region "$REGION"
}


# list_resources: List AWS resources of a specified type.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket", "AWS::RDS::DBInstance")
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        A list of resource identifiers
    
# Usage: list_resources <resource_type> <region>
list_resources() {
    aws cloudformation list-stack-resources \
        --stack-name "$RESOURCE_TYPE" \
        --region "$REGION"
}


# get_resource: Get details of a specific AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to get (e.g., bucket name for S3 buckets)
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Detailed information about the specified resource with a consistent structure:
        {
            "identifier": The resource identifier,
            "properties": The detailed information about the resource
        }
    
# Usage: get_resource <resource_type> <identifier> <region>
get_resource() {
    aws cloudformation describe-stack-resources \
        --stack-name "$IDENTIFIER" \
        --logical-resource-id "$RESOURCE_TYPE" \
        --region "$REGION"
}


# update_resource: Update an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to update
        patch_document: A list of RFC 6902 JSON Patch operations to apply
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the updated resource with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "resource_info": Optional information about the resource properties
        }
    
# Usage: update_resource <resource_type> <identifier> <patch_document> <region>
update_resource() {
    aws cloudformation update-stack \
        --stack-name "$IDENTIFIER" \
        --template-body "$PATCH_DOCUMENT" \
        --region "$REGION"
}


# create_resource: Create an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        properties: A dictionary of properties for the resource
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the created resource with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "resource_info": Optional information about the resource properties
        }
    
# Usage: create_resource <resource_type> <properties> <region>
create_resource() {
    aws cloudformation create-stack \
        --stack-name "$RESOURCE_TYPE" \
        --template-body "$PROPERTIES" \
        --region "$REGION"
}


# delete_resource: Delete an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to delete (e.g., bucket name for S3 buckets)
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the deletion operation with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", "NOT_FOUND", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
        }
    
# Usage: delete_resource <resource_type> <identifier> <region>
delete_resource() {
    aws cloudformation delete-stack \
        --stack-name "$IDENTIFIER"
}


# get_resource_request_status: Get the status of a long running operation with the request token.

    Args:
        request_token: The request_token returned from the long running operation
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Detailed information about the request status structured as
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", "NOT_FOUND", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "error_code": A code associated with any errors if the request failed
            "retry_after": A duration to wait before retrying the request
        }
    
# Usage: get_resource_request_status <request_token> <region>
get_resource_request_status() {
    aws cloudformation describe-stack-set-operation \
        --operation-id "$REQUEST_TOKEN" \
        --region "$REGION"
}


# create_template: Create a CloudFormation template from existing resources using the IaC Generator API.

    This tool allows you to generate CloudFormation templates from existing AWS resources
    that are not already managed by CloudFormation. The template generation process is
    asynchronous, so you can check the status of the process and retrieve the template
    once it's complete. You can pass up to 500 resources at a time.

    Examples:
    1. Start template generation for an S3 bucket:
       create_template(
           template_name="my-template",
           resources=[{"ResourceType": "AWS::S3::Bucket", "ResourceIdentifier": {"BucketName": "my-bucket"}}],
           deletion_policy="RETAIN",
           update_replace_policy="RETAIN"
       )

    2. Check status of template generation:
       create_template(template_id="arn:aws:cloudformation:us-east-1:123456789012:generatedtemplate/abcdef12-3456-7890-abcd-ef1234567890")

    3. Retrieve and save generated template:
       create_template(
           template_id="arn:aws:cloudformation:us-east-1:123456789012:generatedtemplate/abcdef12-3456-7890-abcd-ef1234567890",
           save_to_file="/path/to/template.yaml",
           output_format="YAML"
       )
    
# Usage: create_template <template_name> <resources> <output_format> <deletion_policy> <update_replace_policy> <template_id> <save_to_file> <region>
create_template() {
    aws cloudformation generate-template \
        --template-name "$TEMPLATE_NAME" \
        --resources "$RESOURCES" \
        --output-format "$OUTPUT_FORMAT" \
        --deletion-policy "$DELETION_POLICY" \
        --update-replace-policy "$UPDATE_REPLACE_POLICY" \
        --template-id "$TEMPLATE_ID" \
        --region "$REGION"
}


