#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-cloudwatch-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# describe_log_groups: Lists AWS CloudWatch log groups and saved queries associated with them, optionally filtering by a name prefix.

        This tool retrieves information about log groups in the account, or log groups in accounts linked to this account as a monitoring account.
        If a prefix is provided, only log groups with names starting with the specified prefix are returned.

        Additionally returns any user saved queries that are associated with any of the returned log groups.

        Usage: Use this tool to discover log groups that you'd retrieve or query logs from and queries that have been saved by the user.

        Returns:
        --------
        List of log group metadata dictionaries and saved queries associated with them
           Each log group metadata contains details such as:
                - logGroupName: The name of the log group.
                - creationTime: Timestamp when the log group was created
                - retentionInDays: Retention period, if set
                - storedBytes: The number of bytes stored.
                - kmsKeyId: KMS Key Id used for data encryption, if set
                - dataProtectionStatus: Displays whether this log group has a protection policy, or whether it had one in the past, if set
                - logGroupClass: Type of log group class
                - logGroupArn: The Amazon Resource Name (ARN) of the log group. This version of the ARN doesn't include a trailing :* after the log group name.
            Any saved queries that are applicable to the returned log groups are also included.
        
# Usage: describe_log_groups <account_identifiers> <include_linked_accounts> <log_group_class> <log_group_name_prefix> <max_items> <region> <profile_name>
describe_log_groups() {
    aws logs describe-log-groups \
        --log-group-name-prefix "$LOG_GROUP_NAME_PREFIX" \
        --max-items "$MAX_ITEMS" \
        --log-group-class "$LOG_GROUP_CLASS"
}


# analyze_log_group: Analyzes a CloudWatch log group for anomalies, message patterns, and error patterns within a specified time window.

        This tool performs an analysis of the specified log group by:
        1. Discovering and checking log anomaly detectors associated with the log group
        2. Retrieving anomalies from those detectors that fall within the specified time range
        3. Identifying the top 5 most common message patterns
        4. Finding the top 5 patterns containing error-related terms

        Usage: Use this tool to detect anomalies and understand common patterns in your log data, particularly
        focusing on error patterns that might indicate issues. This can help identify potential problems and
        understand the typical behavior of your application.

        Returns:
        --------
        A LogsAnalysisResult object containing:
            - log_anomaly_results: Information about anomaly detectors and their findings
                * anomaly_detectors: List of anomaly detectors for the log group
                * anomalies: List of anomalies that fall within the specified time range
            - top_patterns: Results of the query for most common message patterns
            - top_patterns_containing_errors: Results of the query for patterns containing error-related terms
                (error, exception, fail, timeout, fatal)
        
# Usage: analyze_log_group <log_group_arn> <start_time> <end_time> <region> <profile_name>
analyze_log_group() {
    aws logs start-query \
        --log-group-name "$LOG_GROUP_ARN" \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --query-string "$SELECT * FROM CLOUDWATCHLOGS" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# execute_log_insights_query: Executes a CloudWatch Logs Insights query and waits for the results to be available.

        IMPORTANT: The operation must include exactly one of the following parameters: log_group_names, or log_group_identifiers.

        CRITICAL: The volume of returned logs can easily overwhelm the agent context window. Always include a limit in the query
        (| limit 50) or using the limit parameter.

        Usage: Use to query, filter, collect statistics, or find patterns in one or more log groups. For example, the following
        query lists exceptions per hour.

        ```
        filter @message like /Exception/
        | stats count(*) as exceptionCount by bin(1h)
        | sort exceptionCount desc
        ```

        Returns:
        --------
            A dictionary containing the final query results, including:
                - status: The current status of the query (e.g., Scheduled, Running, Complete, Failed, etc.)
                - results: A list of the actual query results if the status is Complete.
                - statistics: Query performance statistics
                - messages: Any informational messages about the query
        
# Usage: execute_log_insights_query <log_group_names> <log_group_identifiers> <start_time> <end_time> <query_string> <limit> <max_timeout> <region> <profile_name>
execute_log_insights_query() {
    aws logs start-query \
        --log-group-names "$LOG_GROUP_NAMES" \
        --log-group-identifiers "$LOG_GROUP_IDENTIFIERS" \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --query-string "$QUERY_STRING" \
        --limit "$LIMIT"
}


# get_logs_insight_query_results: Retrieves the results of a previously started CloudWatch Logs Insights query.

        Usage: If a log query is started by execute_log_insights_query tool and has a polling time out, this tool can be used to try to retrieve
        the query results again.

        Returns:
        --------
            A dictionary containing the final query results, including:
                - status: The current status of the query (e.g., Scheduled, Running, Complete, Failed, etc.)
                - results: A list of the actual query results if the status is Complete.
                - statistics: Query performance statistics
                - messages: Any informational messages about the query
        
# Usage: get_logs_insight_query_results <query_id> <region> <profile_name>
get_logs_insight_query_results() {
    aws logs get-query-results \
        --query-id "$QUERY_ID" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# cancel_logs_insight_query: Cancels an ongoing CloudWatch Logs Insights query. If the query has already ended, returns an error that the given query is not running.

        Usage: If a log query is started by execute_log_insights_query tool and has a polling time out, this tool can be used to cancel
        it prematurely to avoid incurring additional costs.

        Returns:
        --------
            A LogsQueryCancelResult with a "success" key, which is True if the query was successfully cancelled.
        
# Usage: cancel_logs_insight_query <query_id> <region> <profile_name>
cancel_logs_insight_query() {
    aws logs stop-query \
        --query-id "$QUERY_ID" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# get_metric_data: Retrieves CloudWatch metric data for a specific metric.

        This tool retrieves metric data from CloudWatch for a specific metric identified by its
        namespace, metric name, and dimensions, within a specified time range. It can use either
        standard GetMetricData API or CloudWatch Metrics Insights for more advanced querying.

        The function automatically determines whether to use standard GetMetricData or Metrics Insights
        based on the parameters provided. If any Metrics Insights specific parameters are provided
        (group_by_dimension, schema_dimension_keys, limit, sort_order, or order_by_statistic), it will use Metrics Insights.

        When using group_by_dimension, you must include that dimension in schema_dimension_keys.

        Usage: Use this tool to get actual metric data from CloudWatch for analysis or visualization.

        Returns:
            GetMetricDataResponse: An object containing the metric data results

        Example 1 (Standard GetMetricData):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                dimensions=[
                    Dimension(name="InstanceId", value="i-1234567890abcdef0")
                ],
                statistic="Average"
                # Period will be auto-calculated based on time window and target_datapoints
            )

        Example 2 (Metrics Insights with group by):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                end_time="2023-01-02T00:00:00Z",
                statistic="AVG",
                schema_dimension_keys=["InstanceType"],
                group_by_dimension="InstanceType"
                # This will generate a query like: SELECT AVG("CPUUtilization") FROM SCHEMA("AWS/EC2", "InstanceType") GROUP BY "InstanceType"
            )

        Example 3 (Metrics Insights with schema dimension keys):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                end_time="2023-01-02T00:00:00Z",
                statistic="AVG",
                schema_dimension_keys=["InstanceId", "InstanceType"],
                group_by_dimension="InstanceId"
                # This will generate a query like: SELECT AVG("CPUUtilization") FROM SCHEMA("AWS/EC2", "InstanceId", "InstanceType") GROUP BY "InstanceId"
            )

        Example 4 (Metrics Insights with ORDER BY and LIMIT to find the top 5 EC2 instances with the highest CPU utilization):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                end_time="2023-01-02T00:00:00Z",
                statistic="AVG",
                schema_dimension_keys=["InstanceId"],
                group_by_dimension="InstanceId",
                sort_order="DESC",
                limit=5,
                order_by_statistic="MAX"
                # This will generate a query like: SELECT AVG("CPUUtilization") FROM SCHEMA("AWS/EC2", "InstanceId") GROUP BY "InstanceId" ORDER BY MAX() DESC LIMIT 5
            )

        Example 5 (Metrics Insights with ORDER BY without sort direction to find the EC2 instances with the highest CPU utilization ordered by default ASC):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                end_time="2023-01-02T00:00:00Z",
                statistic="AVG",
                schema_dimension_keys=["InstanceId"],
                group_by_dimension="InstanceId",
                order_by_statistic="MAX"
                # This will generate a query like: SELECT AVG("CPUUtilization") FROM SCHEMA("AWS/EC2", "InstanceId") GROUP BY "InstanceId" ORDER BY MAX()
            )

        Example 6 (Metrics Insights without ORDER BY clause to find the EC2 instances with the highest CPU utilization in no specific order):
            result = await get_metric_data(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                start_time="2023-01-01T00:00:00Z",
                end_time="2023-01-02T00:00:00Z",
                statistic="AVG",
                schema_dimension_keys=["InstanceId"],
                group_by_dimension="InstanceId"
                # This will generate a query like: SELECT AVG("CPUUtilization") FROM SCHEMA("AWS/EC2", "InstanceId") GROUP BY "InstanceId"
                # No ORDER BY clause is added since neither order_by_statistic nor sort_order is specified
            )

        For each result:
            for metric_result in result.metricDataResults:
                print(f"Metric: {metric_result.label}")
                for datapoint in metric_result.datapoints:
                    print(f"  {datapoint.timestamp}: {datapoint.value}")
        
# Usage: get_metric_data <namespace> <metric_name> <start_time> <dimensions> <end_time> <statistic> <target_datapoints> <group_by_dimension> <schema_dimension_keys> <limit> <sort_order> <order_by_statistic> <region> <profile_name>
get_metric_data() {
    aws cloudwatch get-metric-data \
        --metric-data-queries "$METRIC_DATA_QUERIES" \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --max-datapoints "$TARGET_DATAPOINTS" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# get_metric_metadata: Gets metadata for a CloudWatch metric including description, unit and recommended
        statistics that can be used for metric data retrieval.

        This tool retrieves comprehensive metadata about a specific CloudWatch metric
        identified by its namespace and metric name. Note: This function uses local metadata
        and does not make AWS API calls.

        Usage: Use this tool to get detailed information about CloudWatch metrics,
        including their descriptions, units, and recommended statistics to use.

        Args:
            ctx: The MCP context object for error handling and logging.
            namespace: The metric namespace (e.g., "AWS/EC2", "AWS/Lambda")
            metric_name: The name of the metric (e.g., "CPUUtilization", "Duration")

        Returns:
            Optional[MetricMetadata]: An object containing the metric's description,
                                     recommended statistics, and unit if found,
                                     None if no metadata is available.

        Example:
            result = await get_metric_metadata(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization"
            )
            if result:
                print(f"Description: {result.description}")
                print(f"Unit: {result.unit}")
                print(f"Recommended Statistics: {result.recommendedStatistics}")
        
# Usage: get_metric_metadata <namespace> <metric_name>
get_metric_metadata() {
    aws cloudwatch list-metrics \
        --namespace "$NAMESPACE" \
        --metric-name "$METRIC_NAME"
}


# analyze_metric: Analyzes CloudWatch metric data to determine seasonality, trend, data density and statistical properties.

        This tool provides RAW DATA ONLY about historical metric data and performs analysis including:
        - Seasonality detection
        - Trend analysis
        - Data density and publishing period
        - Advanced statistical measures (min/max/median, std dev, noise)

        Usage: Use this tool to get objective metric analysis data.

        Args:
            ctx: The MCP context object for error handling and logging.
            namespace: The metric namespace (e.g., "AWS/EC2", "AWS/Lambda")
            metric_name: The name of the metric (e.g., "CPUUtilization", "Duration")
            dimensions: List of dimensions with name and value pairs
            region: AWS region to query. Defaults to AWS_REGION environment variable or us-east-1 if not set.
            profile_name: AWS CLI Profile Name to use for AWS access. Falls back to AWS_PROFILE environment variable if not specified, or uses default AWS credential chain.
            statistic: The statistic to use for metric analysis. For guidance on choosing the correct statistic, refer to the get_recommended_metric_alarms tool.

        Returns:
            Dict[str, Any]: Analysis results including:
                - message: Status message indicating success or reason for empty result
                - seasonality_seconds: Detected seasonality period in seconds
                - trend: Trend direction (INCREASING, DECREASING, or NONE)
                - statistics: Statistical measures (std_deviation, variance, etc.)
                - data_quality: Data density and publishing period information

        Example:
            analysis = await analyze_metric(
                ctx,
                namespace="AWS/EC2",
                metric_name="CPUUtilization",
                dimensions=[
                    Dimension(name="InstanceId", value="i-1234567890abcdef0")
                ]
            )
            print(f"Status: {analysis['message']}")
            print(f"Seasonality: {analysis['seasonality_seconds']} seconds")
            print(f"Trend: {analysis['trend']}")
        
# Usage: analyze_metric <namespace> <metric_name> <dimensions> <region> <profile_name> <statistic>
analyze_metric() {
    aws cloudwatch get-metric-statistics \
        --namespace "$NAMESPACE" \
        --metric-name "$METRIC_NAME" \
        --dimensions "$DIMENSIONS" \
        --statistics "$STATISTIC" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# get_recommended_metric_alarms: Gets recommended alarms for a CloudWatch metric.

        This tool retrieves alarm recommendations for a specific CloudWatch metric
        identified by its namespace, metric name, and dimensions. The recommendations
        are filtered to match the provided dimensions.

        Usage: Use this tool to get recommended alarm configurations for CloudWatch metrics,
        including thresholds, evaluation periods, and other alarm settings.

        Args:
            ctx: The MCP context object for error handling and logging.
            namespace: The metric namespace (e.g., "AWS/EC2", "AWS/Lambda")
            metric_name: The name of the metric (e.g., "CPUUtilization", "Duration")
            dimensions: List of dimensions with name and value pairs
            region: AWS region to query. Defaults to AWS_REGION environment variable or us-east-1 if not set.
            profile_name: AWS CLI Profile Name to use for AWS access. Falls back to AWS_PROFILE environment variable if not specified, or uses default AWS credential chain.
            statistic: The statistic to use for alarm recommendations. Must match the metric's data type:
                - Aggregate count metrics (RequestCount, Errors, Faults, Throttles, CacheHits, Connections, EventsProcessed): Use 'Sum'
                - Event occurrence metrics (Invocations, CacheMisses): Use 'SampleCount'
                - Utilization metrics (CPUUtilization, MemoryUtilization, DiskUtilization, NetworkUtilization): Use 'Average'
                - Latency/Time metrics (Duration, Latency, ResponseTime, ProcessingTime, Delay, ExecutionTime, WaitTime): Use 'Average'
                - Size metrics (PayloadSize, MessageSize, RequestSize, BodySize): Use 'Average'
                If uncertain about the correct statistic for a custom metric, ask the user
                to confirm the metric type before generating recommendations. Using the wrong statistic
                (e.g., 'Average' on Invocations) will produce ineffective alarm thresholds

        Returns:
            AlarmRecommendationResult: A result containing alarm recommendations and optional message.
                                     Empty recommendations list if no recommendations are found.

        Example:
            recommendations = await get_recommended_metric_alarms(
                ctx,
                namespace="AWS/EC2",
                metric_name="StatusCheckFailed_Instance",
                dimensions=[
                    Dimension(name="InstanceId", value="i-1234567890abcdef0")
                ]
            )
            for alarm in recommendations:
                print(f"Alarm: {alarm.alarmDescription}")
                print(f"Threshold: {alarm.threshold.staticValue}")
        
# Usage: get_recommended_metric_alarms <namespace> <metric_name> <dimensions> <region> <profile_name> <statistic>
get_recommended_metric_alarms() {
    aws cloudwatch describe-alarms-for-metric \
        --namespace "$NAMESPACE" \
        --metric-name "$METRIC_NAME" \
        --dimensions "$DIMENSIONS" \
        --statistic "$STATISTIC"
}


# get_active_alarms: Gets all CloudWatch Alarms currently in ALARM state.

        This tool retrieves all CloudWatch Alarms that are currently in the ALARM state,
        including both metric alarms and composite alarms. Results are optimized for
        LLM reasoning with summary-level information.

        Usage: Use this tool to get an overview of all active alarms in your AWS account
        for troubleshooting, monitoring, and operational awareness.

        Args:
            ctx: The MCP context object for error handling and logging.
            max_items: Maximum number of alarms to return (default: 50).
            region: AWS region to query. Defaults to AWS_REGION environment variable or us-east-1 if not set.
            profile_name: AWS CLI Profile Name to use for AWS access. Falls back to AWS_PROFILE environment variable if not specified, or uses default AWS credential chain.

        Returns:
            ActiveAlarmsResponse: Response containing active alarms.

        Example:
            result = await get_active_alarms(ctx, max_items=25)
            if isinstance(result, ActiveAlarmsResponse):
                print(f"Found {len(result.metric_alarms + result.composite_alarms)} active alarms")
                for alarm in result.metric_alarms:
                    print(f"Metric Alarm: {alarm.alarm_name}")
                for alarm in result.composite_alarms:
                    print(f"Composite Alarm: {alarm.alarm_name}")
        
# Usage: get_active_alarms <max_items> <region> <profile_name>
get_active_alarms() {
    aws cloudwatch describe-alarms \
        --max-records "$MAX_ITEMS" \
        --state-value "$ALARM" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


# get_alarm_history: Gets the history for a CloudWatch alarm with time range suggestions for investigation.

        This tool retrieves the history for a specified CloudWatch alarm, focusing primarily
        on state transitions to ALARM state. It also provides suggested time ranges for
        investigation based on the alarm's configuration and history.

        Usage: Use this tool to understand when an alarm fired and get useful time ranges
        for investigating the underlying issue using other CloudWatch tools. The tool is
        particularly useful for identifying patterns like alarm flapping (going in and out
        of alarm state frequently).

        Args:
            ctx: The MCP context object for error handling and logging.
            region: AWS region to query. Defaults to AWS_REGION environment variable or us-east-1 if not set.
            alarm_name: Name of the alarm to retrieve history for.
            start_time: Optional start time for the history query. Defaults to 24 hours ago.
            end_time: Optional end time for the history query. Defaults to current time.
            history_item_type: Optional type of history items to retrieve. Defaults to 'StateUpdate'.
            max_items: Maximum number of history items to return. Defaults to 50.
            include_component_alarms: For composite alarms, whether to include details about component alarms.
            profile_name: AWS CLI Profile Name to use for AWS access. Falls back to AWS_PROFILE environment variable if not specified, or uses default AWS credential chain.

        Returns:
            Union[AlarmHistoryResponse, CompositeAlarmComponentResponse]: Either a response containing
            alarm history with time range suggestions, or component alarm details for composite alarms.

        Example:
            result = await get_alarm_history(
                ctx,
                alarm_name="my-cpu-alarm",
                start_time="2025-06-18T00:00:00Z",
                end_time="2025-06-19T00:00:00Z"
            )
            if isinstance(result, AlarmHistoryResponse):
                print(f"Found {len(result.history_items)} history items")
                for suggestion in result.time_range_suggestions:
                    print(f"Suggested investigation time range: {suggestion.start_time} to {suggestion.end_time}")
        
# Usage: get_alarm_history <alarm_name> <start_time> <end_time> <history_item_type> <max_items> <include_component_alarms> <region> <profile_name>
get_alarm_history() {
    aws cloudwatch describe-alarm-history \
        --alarm-name "$ALARM_NAME" \
        --start-date "$START_TIME" \
        --end-date "$END_TIME" \
        --history-item-type "$HISTORY_ITEM_TYPE" \
        --max-records "$MAX_ITEMS" \
        --scan-by "$INCLUDE_COMPONENT_ALARMS" \
        --region "$REGION" \
        --profile "$PROFILE_NAME"
}


