#!/usr/bin/env bash
# Auto-generated AWS CLI functions for aws-iam-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# list_users: List IAM users in the account.

    This tool retrieves a list of IAM users from your AWS account with optional filtering.
    Use this to get an overview of all users or find specific users by path prefix.

    ## Usage Tips:
    - Use path_prefix to filter users by organizational structure
    - Adjust max_items to control response size for large accounts
    - Results may be paginated for accounts with many users

    Args:
        ctx: MCP context for error reporting
        path_prefix: Optional path prefix to filter users
        max_items: Maximum number of users to return

    Returns:
        UsersListResponse containing list of users and metadata
    
# Usage: list_users <ctx> <path_prefix> <max_items>
list_users() {
    aws iam list-users \
        --path-prefix "$PATH_PREFIX" \
        --max-items "$MAX_ITEMS"
}


# get_user: Get detailed information about a specific IAM user.

    This tool retrieves comprehensive information about an IAM user including
    attached policies, group memberships, and access keys. Use this to get
    a complete picture of a user's permissions and configuration.

    ## Usage Tips:
    - Use this after list_users to get detailed information about specific users
    - Review attached policies to understand user permissions
    - Check access keys to identify potential security issues

    Args:
        ctx: MCP context for error reporting
        user_name: The name of the IAM user

    Returns:
        UserDetailsResponse containing comprehensive user information
    
# Usage: get_user <ctx> <user_name>
get_user() {
    aws iam get-user \
        --user-name "$USER_NAME"
}


# create_user: Create a new IAM user.

    This tool creates a new IAM user in your AWS account. The user will be created
    without any permissions by default - you'll need to attach policies separately.

    ## Security Best Practices:
    - Use descriptive user names that indicate the user's role or purpose
    - Set appropriate paths for organizational structure
    - Consider using permissions boundaries to limit maximum permissions
    - Follow the principle of least privilege when assigning permissions later

    Args:
        ctx: MCP context for error reporting
        user_name: The name of the new IAM user
        path: The path for the user (default: '/')
        permissions_boundary: Optional ARN of the permissions boundary policy

    Returns:
        CreateUserResponse containing the created user details
    
# Usage: create_user <ctx> <user_name> <path> <permissions_boundary>
create_user() {
    aws iam create-user \
        --user-name "$USER_NAME" \
        --path "$PATH" \
        --permissions-boundary "$PERMISSIONS_BOUNDARY"
}


# delete_user: Delete an IAM user.

    Args:
        user_name: The name of the IAM user to delete
        force: If True, removes all attached policies, groups, and access keys first

    Returns:
        Dictionary containing deletion status
    
# Usage: delete_user <user_name> <force>
delete_user() {
    aws iam delete-user \
        --user-name "$USER_NAME" \
        --force "$FORCE"
}


# list_roles: List IAM roles in the account.

    Args:
        path_prefix: Optional path prefix to filter roles
        max_items: Maximum number of roles to return

    Returns:
        Dictionary containing list of roles and metadata
    
# Usage: list_roles <path_prefix> <max_items>
list_roles() {
    aws iam list-roles \
        --path-prefix "$PATH_PREFIX" \
        --max-items "$MAX_ITEMS"
}


# create_role: Create a new IAM role.

    Args:
        role_name: The name of the new IAM role
        assume_role_policy_document: The trust policy document in JSON format
        path: The path for the role (default: '/')
        description: Optional description of the role
        max_session_duration: Maximum session duration in seconds
        permissions_boundary: Optional ARN of the permissions boundary policy

    Returns:
        Dictionary containing the created role details
    
# Usage: create_role <role_name> <assume_role_policy_document> <path> <description> <max_session_duration> <permissions_boundary>
create_role() {
    aws iam create-role \
        --role-name "$ROLE_NAME" \
        --assume-role-policy-document "$ASSUME_ROLE_POLICY_DOCUMENT" \
        --path "$PATH" \
        --description "$DESCRIPTION" \
        --max-session-duration "$MAX_SESSION_DURATION" \
        --permissions-boundary "$PERMISSIONS_BOUNDARY"
}


# list_policies: List IAM policies in the account.

    Args:
        scope: Scope of policies to list ("All", "AWS", or "Local")
        only_attached: Only return policies that are attached
        path_prefix: Optional path prefix to filter policies
        max_items: Maximum number of policies to return

    Returns:
        Dictionary containing list of policies and metadata
    
# Usage: list_policies <scope> <only_attached> <path_prefix> <max_items>
list_policies() {
    aws iam list-policies \
        --scope "$SCOPE" \
        --only-attached "$ONLY_ATTACHED" \
        --path-prefix "$PATH_PREFIX" \
        --max-items "$MAX_ITEMS"
}


# get_managed_policy_document: Retrieve the policy document for a managed policy.

    This tool retrieves the policy document for a specific managed policy version.
    Use this to examine the actual permissions and wildcards in managed policies.

    Args:
        policy_arn: The ARN of the managed policy
        version_id: Optional version ID (defaults to current version)

    Returns:
        ManagedPolicyResponse containing the policy document and details
    
# Usage: get_managed_policy_document <policy_arn> <version_id>
get_managed_policy_document() {
    aws iam get-policy-version \
        --policy-arn "$POLICY_ARN" \
        --version-id "$VERSION_ID"
}


# attach_user_policy: Attach a managed policy to an IAM user.

    Args:
        user_name: The name of the IAM user
        policy_arn: The ARN of the policy to attach

    Returns:
        Dictionary containing attachment status
    
# Usage: attach_user_policy <user_name> <policy_arn>
attach_user_policy() {
    aws iam attach-user-policy \
        --user-name "$USER_NAME" \
        --policy-arn "$POLICY_ARN"
}


# detach_user_policy: Detach a managed policy from an IAM user.

    Args:
        user_name: The name of the IAM user
        policy_arn: The ARN of the policy to detach

    Returns:
        Dictionary containing detachment status
    
# Usage: detach_user_policy <user_name> <policy_arn>
detach_user_policy() {
    aws iam detach-user-policy \
        --user-name "$USER_NAME" \
        --policy-arn "$POLICY_ARN"
}


# create_access_key: Create a new access key for an IAM user.

    Args:
        user_name: The name of the IAM user

    Returns:
        Dictionary containing the new access key details
    
# Usage: create_access_key <user_name>
create_access_key() {
    aws iam create-access-key \
        --user-name "$USER_NAME"
}


# delete_access_key: Delete an access key for an IAM user.

    Args:
        user_name: The name of the IAM user
        access_key_id: The access key ID to delete

    Returns:
        Dictionary containing deletion status
    
# Usage: delete_access_key <user_name> <access_key_id>
delete_access_key() {
    aws iam delete-access-key \
        --user-name "$USER_NAME" \
        --access-key-id "$ACCESS_KEY_ID"
}


# simulate_principal_policy: Simulate IAM policy evaluation for a principal.

    Args:
        policy_source_arn: ARN of the user or role to simulate
        action_names: List of actions to simulate
        resource_arns: Optional list of resource ARNs to test against
        context_entries: Optional context entries for the simulation

    Returns:
        Dictionary containing simulation results
    
# Usage: simulate_principal_policy <policy_source_arn> <action_names> <resource_arns> <context_entries>
simulate_principal_policy() {
    aws iam simulate-principal-policy \
        --policy-source-arn "$POLICY_SOURCE_ARN" \
        --action-names "$ACTION_NAMES" \
        --resource-arns "$RESOURCE_ARNS" \
        --context-entries "$CONTEXT_ENTRIES"
}


# list_groups: List IAM groups in the account.

    This tool retrieves a list of IAM groups from your AWS account with optional filtering.
    Use this to get an overview of all groups or find specific groups by path prefix.

    ## Usage Tips:
    - Use path_prefix to filter groups by organizational structure
    - Adjust max_items to control response size for large accounts
    - Results may be paginated for accounts with many groups

    Args:
        path_prefix: Optional path prefix to filter groups
        max_items: Maximum number of groups to return

    Returns:
        GroupsListResponse containing list of groups and metadata
    
# Usage: list_groups <path_prefix> <max_items>
list_groups() {
    aws iam list-groups \
        --path-prefix "$PATH_PREFIX" \
        --max-items "$MAX_ITEMS"
}


# get_group: Get detailed information about a specific IAM group.

    This tool retrieves comprehensive information about an IAM group including
    group members, attached policies, and inline policies. Use this to get
    a complete picture of a group's configuration and membership.

    ## Usage Tips:
    - Use this after list_groups to get detailed information about specific groups
    - Review attached policies to understand group permissions
    - Check group members to see who has these permissions

    Args:
        group_name: The name of the IAM group

    Returns:
        GroupDetailsResponse containing comprehensive group information
    
# Usage: get_group <group_name>
get_group() {
    aws iam get-group \
        --group-name "$GROUP_NAME"
}


# create_group: Create a new IAM group.

    This tool creates a new IAM group in your AWS account. The group will be created
    without any permissions by default - you'll need to attach policies separately.

    ## Security Best Practices:
    - Use descriptive group names that indicate the group's purpose
    - Set appropriate paths for organizational structure
    - Follow the principle of least privilege when assigning permissions later

    Args:
        group_name: The name of the new IAM group
        path: The path for the group (default: '/')

    Returns:
        CreateGroupResponse containing the created group details
    
# Usage: create_group <group_name> <path>
create_group() {
    aws iam create-group \
        --group-name "$GROUP_NAME" \
        --path "$PATH"
}


# delete_group: Delete an IAM group.

    Args:
        group_name: The name of the IAM group to delete
        force: If True, removes all members and attached policies first

    Returns:
        Dictionary containing deletion status
    
# Usage: delete_group <group_name> <force>
delete_group() {
    aws iam delete-group \
        --group-name "$GROUP_NAME" \
        --force "$FORCE"
}


# add_user_to_group: Add a user to an IAM group.

    Args:
        group_name: The name of the IAM group
        user_name: The name of the IAM user

    Returns:
        GroupMembershipResponse containing operation status
    
# Usage: add_user_to_group <group_name> <user_name>
add_user_to_group() {
    aws iam add-user-to-group \
        --group-name "$GROUP_NAME" \
        --user-name "$USER_NAME"
}


# remove_user_from_group: Remove a user from an IAM group.

    Args:
        group_name: The name of the IAM group
        user_name: The name of the IAM user

    Returns:
        GroupMembershipResponse containing operation status
    
# Usage: remove_user_from_group <group_name> <user_name>
remove_user_from_group() {
    aws iam remove-user-from-group \
        --group-name "$GROUP_NAME" \
        --user-name "$USER_NAME"
}


# attach_group_policy: Attach a managed policy to an IAM group.

    Args:
        group_name: The name of the IAM group
        policy_arn: The ARN of the policy to attach

    Returns:
        GroupPolicyAttachmentResponse containing operation status
    
# Usage: attach_group_policy <group_name> <policy_arn>
attach_group_policy() {
    aws iam attach-group-policy \
        --group-name "$GROUP_NAME" \
        --policy-arn "$POLICY_ARN"
}


# detach_group_policy: Detach a managed policy from an IAM group.

    Args:
        group_name: The name of the IAM group
        policy_arn: The ARN of the policy to detach

    Returns:
        GroupPolicyAttachmentResponse containing operation status
    
# Usage: detach_group_policy <group_name> <policy_arn>
detach_group_policy() {
    aws iam detach-group-policy \
        --group-name "$GROUP_NAME" \
        --policy-arn "$POLICY_ARN"
}


# put_user_policy: Create or update an inline policy for an IAM user.

    This tool creates a new inline policy or updates an existing one for the specified user.
    Inline policies are directly embedded in a single user, role, or group and have a one-to-one
    relationship with the identity.

    ## Security Best Practices:
    - Follow the principle of least privilege when creating policies
    - Use managed policies for common permissions that can be reused
    - Regularly review and audit inline policies
    - Test policies using simulate_principal_policy before applying

    Args:
        user_name: The name of the IAM user
        policy_name: The name of the inline policy
        policy_document: The policy document in JSON format

    Returns:
        InlinePolicyResponse containing the policy details and operation status
    
# Usage: put_user_policy <user_name> <policy_name> <policy_document>
put_user_policy() {
    aws iam put-user-policy \
        --user-name "$USER_NAME" \
        --policy-name "$POLICY_NAME" \
        --policy-document "$POLICY_DOCUMENT"
}


# get_user_policy: Retrieve an inline policy for an IAM user.

    This tool retrieves the policy document for a specific inline policy attached to a user.

    Args:
        user_name: The name of the IAM user
        policy_name: The name of the inline policy

    Returns:
        InlinePolicyResponse containing the policy document and details
    
# Usage: get_user_policy <user_name> <policy_name>
get_user_policy() {
    aws iam get-user-policy \
        --user-name "$USER_NAME" \
        --policy-name "$POLICY_NAME"
}


# delete_user_policy: Delete an inline policy from an IAM user.

    This tool removes an inline policy from the specified user. The policy document
    will be permanently deleted and cannot be recovered.

    Args:
        user_name: The name of the IAM user
        policy_name: The name of the inline policy to delete

    Returns:
        Dictionary containing deletion status
    
# Usage: delete_user_policy <user_name> <policy_name>
delete_user_policy() {
    aws iam delete-user-policy \
        --user-name "$USER_NAME" \
        --policy-name "$POLICY_NAME"
}


# put_role_policy: Create or update an inline policy for an IAM role.

    This tool creates a new inline policy or updates an existing one for the specified role.
    Inline policies are directly embedded in a single user, role, or group and have a one-to-one
    relationship with the identity.

    Args:
        role_name: The name of the IAM role
        policy_name: The name of the inline policy
        policy_document: The policy document in JSON format

    Returns:
        InlinePolicyResponse containing the policy details and operation status
    
# Usage: put_role_policy <role_name> <policy_name> <policy_document>
put_role_policy() {
    aws iam put-role-policy \
        --role-name "$ROLE_NAME" \
        --policy-name "$POLICY_NAME" \
        --policy-document "$POLICY_DOCUMENT"
}


# get_role_policy: Retrieve an inline policy for an IAM role.

    This tool retrieves the policy document for a specific inline policy attached to a role.

    Args:
        role_name: The name of the IAM role
        policy_name: The name of the inline policy

    Returns:
        InlinePolicyResponse containing the policy document and details
    
# Usage: get_role_policy <role_name> <policy_name>
get_role_policy() {
    aws iam get-role-policy \
        --role-name "$ROLE_NAME" \
        --policy-name "$POLICY_NAME"
}


# delete_role_policy: Delete an inline policy from an IAM role.

    This tool removes an inline policy from the specified role. The policy document
    will be permanently deleted and cannot be recovered.

    Args:
        role_name: The name of the IAM role
        policy_name: The name of the inline policy to delete

    Returns:
        Dictionary containing deletion status
    
# Usage: delete_role_policy <role_name> <policy_name>
delete_role_policy() {
    aws iam delete-role-policy \
        --role-name "$ROLE_NAME" \
        --policy-name "$POLICY_NAME"
}


# list_user_policies: List all inline policies for an IAM user.

    This tool retrieves the names of all inline policies attached to the specified user.

    Args:
        user_name: The name of the IAM user

    Returns:
        InlinePolicyListResponse containing the list of policy names
    
# Usage: list_user_policies <user_name>
list_user_policies() {
    aws iam list-user-policies \
        --user-name "$USER_NAME"
}


# list_role_policies: List all inline policies for an IAM role.

    This tool retrieves the names of all inline policies attached to the specified role.

    Args:
        role_name: The name of the IAM role

    Returns:
        InlinePolicyListResponse containing the list of policy names
    
# Usage: list_role_policies <role_name>
list_role_policies() {
    aws iam list-role-policies \
        --role-name "$ROLE_NAME"
}


