#!/usr/bin/env bash
# Auto-generated AWS CLI functions for aws-msk-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# describe_cluster_operation: Gets information about a cluster operation.
# Usage: describe_cluster_operation <region> <cluster_operation_arn>
describe_cluster_operation() {
    aws kafka describe-cluster-operation \
        --cluster-operation-arn "$CLUSTER_OPERATION_ARN" \
        --region "$REGION"
}


# describe_vpc_connection: Gets detailed information about a VPC connection.
# Usage: describe_vpc_connection <region> <vpc_connection_arn>
describe_vpc_connection() {
    aws kafka describe-vpc-connection \
        --vpc-connection-arn "$VPC_CONNECTION_ARN" \
        --region "$REGION"
}


# get_configuration_info: Gets information about MSK configurations.
# Usage: get_configuration_info <region> <action> <arn> <kwargs>
get_configuration_info() {
    aws kafka describe-configuration \
        --configuration-arn "$ARN" \
        --region "$REGION"
}


# list_tags_for_resource: Lists all tags for an MSK resource.
# Usage: list_tags_for_resource <region> <arn>
list_tags_for_resource() {
    aws kafka list-tags-for-resource \
        --resource-arn "$ARN" \
        --region "$REGION"
}


# list_topics: Returns all topics in an MSK cluster.
# Usage: list_topics <region> <cluster_arn> <topic_name_filter> <max_results> <next_token>
list_topics() {
    aws kafka list-topics \
        --cluster-arn "$CLUSTER_ARN" \
        --max-results "$MAX_RESULTS" \
        --next-token "$NEXT_TOKEN" \
        --filter "$TOPIC_NAME_FILTER"
}


# describe_topic: Returns details for a specific topic on an MSK cluster.
# Usage: describe_topic <region> <cluster_arn> <topic_name>
describe_topic() {
    aws kafka describe-topic \
        --cluster-arn "$CLUSTER_ARN" \
        --topic-name "$TOPIC_NAME" \
        --region "$REGION"
}


# describe_topic_partitions: Returns partition information for a specific topic on an MSK cluster.
# Usage: describe_topic_partitions <region> <cluster_arn> <topic_name> <max_results> <next_token>
describe_topic_partitions() {
    aws kafka list-cluster-operations \
        --cluster-arn "$CLUSTER_ARN" \
        --max-results "$MAX_RESULTS" \
        --next-token "$NEXT_TOKEN"
}


# list_customer_iam_access: Lists IAM access information for an MSK cluster.
# Usage: list_customer_iam_access <region> <cluster_arn>
list_customer_iam_access() {
    aws kafka list-cluster-operations \
        --cluster-arn "$CLUSTER_ARN" \
        --region "$REGION"
}


# get_cluster_best_practices: Gets best practices and quotas for AWS MSK clusters.
# Usage: get_cluster_best_practices <instance_type> <number_of_brokers>
get_cluster_best_practices() {
    aws kafka describe-cluster-operation \
        --cluster-operation-arn "$INSTANCE_TYPE" \
        --number-of-broker-nodes "$NUMBER_OF_BROKERS"
}


