#!/usr/bin/env bash
# Auto-generated AWS CLI functions for healthimaging-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# create_datastore: Create a new data store in AWS HealthImaging.
# Usage: create_datastore <datastore_name> <kms_key_arn> <tags>
create_datastore() {
    aws medical-imaging create-datastore \
        --datastore-name "$DATASTORE_NAME" \
        --kms-key-arn "$KMS_KEY_ARN" \
        --tags "$TAGS"
}


# delete_datastore: Delete a data store from AWS HealthImaging.
# Usage: delete_datastore <datastore_id>
delete_datastore() {
    aws medical-imaging delete-datastore \
        --datastore-id "$DATASTORE_ID"
}


# get_datastore: Get information about a specific data store.
# Usage: get_datastore <datastore_id>
get_datastore() {
    aws healthimaging get-datastore \
        --datastore-id "$DATASTORE_ID"
}


# list_datastores: List all data stores in the account.
# Usage: list_datastores <datastore_status> <max_results> <next_token>
list_datastores() {
    aws healthimaging list-datastores \
        --datastore-status "$DATASTORE_STATUS" \
        --max-results "$MAX_RESULTS" \
        --next-token "$NEXT_TOKEN"
}


# start_dicom_import_job: Start a DICOM import job.
# Usage: start_dicom_import_job <datastore_id> <data_access_role_arn> <input_s3_uri> <job_name> <client_token> <output_s3_uri> <input_owner_account_id>
start_dicom_import_job() {
    aws medical-imaging start-dicom-import-job \
        --datastore-id "$DATASTORE_ID" \
        --data-access-role-arn "$DATA_ACCESS_ROLE_ARN" \
        --input-s3-uri "$INPUT_S3_URI" \
        --job-name "$JOB_NAME" \
        --client-token "$CLIENT_TOKEN" \
        --output-s3-uri "$OUTPUT_S3_URI" \
        --input-owner-account-id "$INPUT_OWNER_ACCOUNT_ID"
}


# get_dicom_import_job: Get information about a DICOM import job.
# Usage: get_dicom_import_job <datastore_id> <job_id>
get_dicom_import_job() {
    aws medical-imaging get-dicom-import-job \
        --datastore-id "$DATASTORE_ID" \
        --job-id "$JOB_ID"
}


# list_dicom_import_jobs: List DICOM import jobs for a data store.
# Usage: list_dicom_import_jobs <datastore_id> <job_status> <next_token> <max_results>
list_dicom_import_jobs() {
    aws medical-imaging list-dicom-import-jobs \
        --datastore-id "$DATASTORE_ID" \
        --job-status "$JOB_STATUS" \
        --next-token "$NEXT_TOKEN" \
        --max-results "$MAX_RESULTS"
}


# search_image_sets: Search for image sets in a data store.
# Usage: search_image_sets <datastore_id> <search_criteria> <next_token> <max_results>
search_image_sets() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$SEARCH_CRITERIA" \
        --next-token "$NEXT_TOKEN" \
        --max-results "$MAX_RESULTS"
}


# get_image_set: Get information about a specific image set.
# Usage: get_image_set <datastore_id> <image_set_id> <version_id>
get_image_set() {
    aws medical-imaging get-image-set \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --version-id "$VERSION_ID"
}


# get_image_set_metadata: Get metadata for a specific image set.
# Usage: get_image_set_metadata <datastore_id> <image_set_id> <version_id>
get_image_set_metadata() {
    aws medical-imaging get-image-set-metadata \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --version-id "$VERSION_ID"
}


# list_image_set_versions: List versions of an image set.
# Usage: list_image_set_versions <datastore_id> <image_set_id> <next_token> <max_results>
list_image_set_versions() {
    aws medical-imaging list-image-set-versions \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --next-token "$NEXT_TOKEN" \
        --max-results "$MAX_RESULTS"
}


# update_image_set_metadata: Update metadata for an image set.
# Usage: update_image_set_metadata <datastore_id> <image_set_id> <latest_version_id> <update_image_set_metadata_updates>
update_image_set_metadata() {
    aws medical-imaging update-image-set-metadata \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --latest-version "$LATEST_VERSION_ID" \
        --update-image-set-metadata-updates "$UPDATE_IMAGE_SET_METADATA_UPDATES"
}


# delete_image_set: Delete an image set.
# Usage: delete_image_set <datastore_id> <image_set_id> <version_id>
delete_image_set() {
    aws medical-imaging delete-image-set \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --version "$VERSION_ID"
}


# copy_image_set: Copy an image set.
# Usage: copy_image_set <datastore_id> <source_image_set_id> <copy_image_set_information> <source_datastore_id>
copy_image_set() {
    aws medical-imaging copy-image-set \
        --destination-datastore-id "$DATASTORE_ID" \
        --source-image-set-id "$SOURCE_IMAGE_SET_ID" \
        --copy-image-set-information "$COPY_IMAGE_SET_INFORMATION" \
        --source-datastore-id "$SOURCE_DATASTORE_ID"
}


# get_image_frame: Get a specific image frame.
# Usage: get_image_frame <datastore_id> <image_set_id> <image_frame_information>
get_image_frame() {
    aws medical-imaging get-image-frame \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --image-frame-information "$IMAGE_FRAME_INFORMATION"
}


# list_tags_for_resource: List tags for a resource.
# Usage: list_tags_for_resource <resource_arn>
list_tags_for_resource() {
    aws healthimaging list-tags-for-resource \
        --resource-arn "$RESOURCE_ARN"
}


# tag_resource: Add tags to a resource.
# Usage: tag_resource <resource_arn> <tags>
tag_resource() {
    aws healthimaging tag-resource \
        --resource-arn "$RESOURCE_ARN" \
        --tags "$TAGS"
}


# untag_resource: Remove tags from a resource.
# Usage: untag_resource <resource_arn> <tag_keys>
untag_resource() {
    aws healthimaging untag-resource \
        --resource-arn "$RESOURCE_ARN" \
        --tag-keys "$TAG_KEYS"
}


# start_dicom_export_job: Start a DICOM export job.
# Usage: start_dicom_export_job <datastore_id> <data_access_role_arn> <output_s3_uri> <job_name> <client_token> <study_instance_uid> <series_instance_uid> <sop_instance_uid> <submitted_before> <submitted_after>
start_dicom_export_job() {
    aws medical-imaging start-dicom-export-job \
        --datastore-id "$DATASTORE_ID" \
        --data-access-role-arn "$DATA_ACCESS_ROLE_ARN" \
        --output-s3-uri "$OUTPUT_S3_URI" \
        --job-name "$JOB_NAME" \
        --client-token "$CLIENT_TOKEN" \
        --study-instance-uid "$STUDY_INSTANCE_UID" \
        --series-instance-uid "$SERIES_INSTANCE_UID" \
        --sop-instance-uid "$SOP_INSTANCE_UID" \
        --submitted-before "$SUBMITTED_BEFORE" \
        --submitted-after "$SUBMITTED_AFTER"
}


# get_dicom_export_job: Get information about a DICOM export job.
# Usage: get_dicom_export_job <datastore_id> <job_id>
get_dicom_export_job() {
    aws medical-imaging get-dicom-export-job \
        --datastore-id "$DATASTORE_ID" \
        --job-id "$JOB_ID"
}


# list_dicom_export_jobs: List DICOM export jobs for a data store.
# Usage: list_dicom_export_jobs <datastore_id> <job_status> <next_token> <max_results>
list_dicom_export_jobs() {
    aws medical-imaging list-dicom-export-jobs \
        --datastore-id "$DATASTORE_ID" \
        --job-status "$JOB_STATUS" \
        --next-token "$NEXT_TOKEN" \
        --max-results "$MAX_RESULTS"
}


# delete_study: Delete all image sets for a specific study.
# Usage: delete_study <datastore_id> <study_instance_uid>
delete_study() {
    aws medical-imaging delete-study \
        --datastore-id "$DATASTORE_ID" \
        --study-instance-uid "$STUDY_INSTANCE_UID"
}


# search_by_patient_id: Search for image sets by patient ID.
# Usage: search_by_patient_id <datastore_id> <patient_id> <max_results>
search_by_patient_id() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$PATIENT_ID" \
        --max-results "$MAX_RESULTS"
}


# search_by_study_uid: Search for image sets by study instance UID.
# Usage: search_by_study_uid <datastore_id> <study_instance_uid> <max_results>
search_by_study_uid() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$STUDY_INSTANCE_UID" \
        --max-results "$MAX_RESULTS"
}


# search_by_series_uid: Search for image sets by series instance UID.
# Usage: search_by_series_uid <datastore_id> <series_instance_uid> <max_results>
search_by_series_uid() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$SERIES_INSTANCE_UID" \
        --max-results "$MAX_RESULTS"
}


# get_patient_studies: Get all studies for a specific patient.
# Usage: get_patient_studies <datastore_id> <patient_id>
get_patient_studies() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$PATIENT_ID"
}


# get_patient_series: Get all series for a specific patient.
# Usage: get_patient_series <datastore_id> <patient_id>
get_patient_series() {
    aws healthimaging list-dicom-series \
        --datastore-id "$DATASTORE_ID" \
        --patient-id "$PATIENT_ID"
}


# get_study_primary_image_sets: Get primary image sets for a specific study.
# Usage: get_study_primary_image_sets <datastore_id> <study_instance_uid>
get_study_primary_image_sets() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$STUDY_INSTANCE_UID"
}


# delete_series_by_uid: Delete a series by SeriesInstanceUID using metadata updates.
# Usage: delete_series_by_uid <datastore_id> <series_instance_uid>
delete_series_by_uid() {
    aws medical-imaging delete-series \
        --datastore-id "$DATASTORE_ID" \
        --series-instance-uid "$SERIES_INSTANCE_UID"
}


# get_series_primary_image_set: Get the primary image set for a given series.
# Usage: get_series_primary_image_set <datastore_id> <series_instance_uid>
get_series_primary_image_set() {
    aws healthimaging get-dicom-series-image-set \
        --datastore-id "$DATASTORE_ID" \
        --series-instance-uid "$SERIES_INSTANCE_UID"
}


# get_patient_dicomweb_studies: Retrieve DICOMweb SearchStudies level information for a given patient ID.
# Usage: get_patient_dicomweb_studies <datastore_id> <patient_id>
get_patient_dicomweb_studies() {
    aws medical-imaging search-dicom-studies \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "${"PATIENTID": "PATIENT_ID"}"
}


# delete_instance_in_study: Delete a specific instance in a study.
# Usage: delete_instance_in_study <datastore_id> <study_instance_uid> <sop_instance_uid>
delete_instance_in_study() {
    aws medical-imaging delete-dicom-instance \
        --datastore-id "$DATASTORE_ID" \
        --study-instance-uid "$STUDY_INSTANCE_UID" \
        --sop-instance-uid "$SOP_INSTANCE_UID"
}


# delete_instance_in_series: Delete a specific instance in a series.
# Usage: delete_instance_in_series <datastore_id> <series_instance_uid> <sop_instance_uid>
delete_instance_in_series() {
    aws medical-imaging delete-dicom-instance \
        --datastore-id "$DATASTORE_ID" \
        --series-instance-uid "$SERIES_INSTANCE_UID" \
        --sop-instance-uid "$SOP_INSTANCE_UID"
}


# update_patient_study_metadata: Update Patient/Study metadata for an entire study.
# Usage: update_patient_study_metadata <datastore_id> <study_instance_uid> <patient_updates> <study_updates>
update_patient_study_metadata() {
    aws medical-imaging update-image-set-metadata \
        --datastore-id "$DATASTORE_ID" \
        --study-instance-uid "$STUDY_INSTANCE_UID" \
        --patient-metadata "$PATIENT_UPDATES" \
        --study-metadata "$STUDY_UPDATES"
}


# bulk_delete_by_criteria: Delete multiple image sets matching specified criteria.
# Usage: bulk_delete_by_criteria <datastore_id> <criteria> <max_deletions>
bulk_delete_by_criteria() {
    aws medical-imaging search-image-sets \
        --datastore-id "$DATASTORE_ID" \
        --search-criteria "$CRITERIA" \
        --max-results "$MAX_DELETIONS"
}


# remove_series_from_image_set: Remove a specific series from an image set using DICOM hierarchy operations.
# Usage: remove_series_from_image_set <datastore_id> <image_set_id> <series_instance_uid>
remove_series_from_image_set() {
    aws medical-imaging update-image-set-metadata \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --update-image-set-metadata-updates "${"REMOVESERIES": ["SERIES_INSTANCE_UID"]}"
}


# remove_instance_from_image_set: Remove a specific instance from an image set using DICOM hierarchy operations.
# Usage: remove_instance_from_image_set <datastore_id> <image_set_id> <series_instance_uid> <sop_instance_uid>
remove_instance_from_image_set() {
    aws healthimaging remove-image-set-instances \
        --datastore-id "$DATASTORE_ID" \
        --image-set-id "$IMAGE_SET_ID" \
        --instances "$[{"SERIESINSTANCEUID":"SERIES_INSTANCE_UID","SOPINSTANCEUID":"SOP_INSTANCE_UID"}]"
}


