"""Auto-generated boto3 functions for amazon-elasticache-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def create_replication_group(request: str, **kwargs) -> dict:
    """Create an Amazon ElastiCache replication group.

    This tool creates a new replication group with specified configuration including:
    - Basic replication group settings
    - Cache node configuration
    - Network and security settings
    - Encryption settings
    - Backup and maintenance settings
    - Monitoring and logging settings

    Args:
        request: The CreateReplicationGroupRequest object containing all parameters

    Returns:
        Dict containing information about the created replication group.
    """
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['ReplicationGroupId'] = request
    if request is not None:
        params['ReplicationGroupDescription'] = request
    params.update(kwargs)
    return client.create_replication_group(**params)



def create_jump_host_replication_group(replication_group_id: str, key_name: str, subnet_id: str | None = None, security_group_id: str | None = None, instance_type: str | None = None, **kwargs) -> dict:
    """Creates an EC2 jump host instance to access an ElastiCache replication group via SSH tunnel.

    Args:
        replication_group_id (str): ID of the ElastiCache replication group to connect to
        key_name (str): Name of the EC2 key pair to use for SSH access
        subnet_id (str, optional): ID of the subnet to launch the EC2 instance in (must be public).
            If not provided and replication group uses default VPC, will auto-select a default subnet.
        security_group_id (str, optional): ID of the security group to assign to the EC2 instance.
            If not provided and replication group uses default VPC, will use the default security group.
        instance_type (str, optional): EC2 instance type. Defaults to "t3.small"

    Returns:
        Dict[str, Any]: Dictionary containing the created EC2 instance details

    Raises:
        ValueError: If subnet is not public or VPC compatibility check fails
    """
    client = boto3.client('ec2')
    params = {}
    if key_name is not None:
        params['KeyName'] = key_name
    if subnet_id is not None:
        params['SubnetId'] = subnet_id
    if security_group_id is not None:
        params['SecurityGroupIds'] = security_group_id
    if instance_type is not None:
        params['InstanceType'] = instance_type
    params.update(kwargs)
    return client.run_instances(**params)



def delete_replication_group(replication_group_id: str, retain_primary_cluster: str | None = None, final_snapshot_name: str | None = None, **kwargs) -> dict:
    """Delete an Amazon ElastiCache replication group.

    This tool deletes an existing replication group. You can optionally retain the primary cluster
    as a standalone cache cluster or create a final snapshot before deletion.

    Parameters:
        replication_group_id (str): The identifier of the replication group to delete.
        retain_primary_cluster (Optional[bool]): If True, retains the primary cluster as a standalone
            cache cluster. If False, deletes all clusters in the replication group.
        final_snapshot_name (Optional[str]): The name of a final cache cluster snapshot to create
            before deleting the replication group.

    Returns:
        Dict containing information about the deleted replication group.
    """
    client = boto3.client('elasticache')
    params = {}
    if replication_group_id is not None:
        params['ReplicationGroupId'] = replication_group_id
    if retain_primary_cluster is not None:
        params['RetainPrimaryCluster'] = retain_primary_cluster
    if final_snapshot_name is not None:
        params['FinalSnapshotIdentifier'] = final_snapshot_name
    params.update(kwargs)
    return client.delete_replication_group(**params)



def describe_replication_groups(replication_group_id: str | None = None, max_records: str | None = None, marker: str | None = None, **kwargs) -> dict:
    """Describe one or more ElastiCache replication groups.

    This tool returns information about provisioned replication groups. If a replication group ID
    is specified, information about only that replication group is returned. Otherwise, information
    about up to MaxRecords replication groups is returned.

    Parameters:
        replication_group_id (Optional[str]): The identifier for the replication group to describe.
            If not provided, information about all replication groups is returned.
        max_records (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxRecords value, a marker is included
            in the response so that the remaining results can be retrieved.
        marker (Optional[str]): An optional marker returned from a previous request. Use this marker
            for pagination of results from this operation. If this parameter is specified,
            the response includes only records beyond the marker, up to the value specified
            by MaxRecords.

    Returns:
        Dict containing information about the replication group(s), including:
        - ReplicationGroups: List of replication groups
        - Marker: Pagination marker for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if replication_group_id is not None:
        params['ReplicationGroupId'] = replication_group_id
    if max_records is not None:
        params['MaxRecords'] = max_records
    if marker is not None:
        params['Marker'] = marker
    params.update(kwargs)
    return client.describe_replication_groups(**params)



def modify_replication_group_shard_configuration(replication_group_id: str, node_group_count: int, apply_immediately: str | None = None, resharding_configuration: str | None = None, **kwargs) -> dict:
    """Modify the shard configuration of an existing Amazon ElastiCache replication group.

    This tool modifies the shard configuration of an existing replication group by:
    - Modifying the number of replicas in a shard
    - Specifying preferred availability zones for replicas

    Parameters:
        replication_group_id (str): The identifier of the replication group to modify.
        node_group_count (int): The number of node groups (shards) in the replication group.
        apply_immediately (Optional[bool]): Whether to apply changes immediately or during maintenance window.
        resharding_configuration (Optional[Union[str, List[Dict]]]): Resharding configuration in either shorthand string format or list of dictionaries format.
            Shorthand format: "NodeGroupId=string,NewShardConfiguration={NewReplicaCount=integer,PreferredAvailabilityZones=string1,string2}"
            Multiple configurations can be separated by spaces.
            JSON format: List of dictionaries with required fields:
            - NodeGroupId: string
            - NewShardConfiguration:
                - NewReplicaCount: integer
                - PreferredAvailabilityZones: list of strings (optional)

    Returns:
        Dict containing information about the modified replication group.
    """
    client = boto3.client('elasticache')
    params = {}
    if replication_group_id is not None:
        params['ReplicationGroupId'] = replication_group_id
    if node_group_count is not None:
        params['NodeGroupCount'] = node_group_count
    if apply_immediately is not None:
        params['ApplyImmediately'] = apply_immediately
    if resharding_configuration is not None:
        params['ReshardingConfiguration'] = resharding_configuration
    params.update(kwargs)
    return client.modify_replication_group_shard_configuration(**params)



def start_migration(request: str, **kwargs) -> dict:
    """Start migration to an Amazon ElastiCache replication group.

    This tool starts migration from a Redis instance to an ElastiCache replication group.
    It initiates the data migration process from the specified endpoint(s) to
    the target replication group.

    Args:
        request: The StartMigrationRequest object containing:
            - replication_group_id: The ID of the replication group to which data should be migrated
            - customer_node_endpoint_list: List of endpoints from which data should be migrated.
              For Valkey or Redis OSS (cluster mode disabled), the list should have only one element.

    Returns:
        Dict containing information about the migration start result.
    """
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['ReplicationGroupId'] = request
    if True is not None:
        params['ReplicasMigration'] = True
    params.update(kwargs)
    return client.modify_replication_group(**params)



def complete_migration(request: str, **kwargs) -> dict:
    """Complete migration to an Amazon ElastiCache replication group.

    This tool completes the migration of data from a Redis instance to an ElastiCache replication group.
    It finalizes the data migration process and transitions the replication group to normal operation.

    Args:
        request: The CompleteMigrationRequest object containing:
            - replication_group_id: The ID of the replication group to which data is being migrated
            - force: (Optional) Forces the migration to stop without ensuring that data is in sync.
              It is recommended to use this option only to abort the migration and not recommended
              when application wants to continue migration to ElastiCache.

    Returns:
        Dict containing information about the migration completion result.
    """
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['ReplicationGroupId'] = request
    params.update(kwargs)
    return client.complete_migration(**params)



def create_cache_cluster(request: str, **kwargs) -> dict:
    """Create an Amazon ElastiCache cache cluster."""
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['ClusterName'] = request
    params.update(kwargs)
    return client.create_cache_cluster(**params)



def delete_cache_cluster(cache_cluster_id: str, final_snapshot_identifier: str | None = None, **kwargs) -> dict:
    """Delete an Amazon ElastiCache cache cluster.

    This tool deletes an existing cache cluster. Optionally, it can create a final
    snapshot of the cluster before deletion.

    Parameters:
        cache_cluster_id (str): The ID of the cache cluster to delete.
        final_snapshot_identifier (Optional[str]): The user-supplied name of a final
            cache cluster snapshot. This is the unique name that identifies the
            snapshot. ElastiCache creates the snapshot, and then deletes the cache
            cluster immediately afterward.

    Returns:
        Dict containing information about the deleted cache cluster.
    """
    client = boto3.client('elasticache')
    params = {}
    if cache_cluster_id is not None:
        params['CacheClusterId'] = cache_cluster_id
    if final_snapshot_identifier is not None:
        params['FinalSnapshotIdentifier'] = final_snapshot_identifier
    params.update(kwargs)
    return client.delete_cache_cluster(**params)



def describe_cache_clusters(cache_cluster_id: str | None = None, max_records: str | None = None, marker: str | None = None, show_cache_node_info: str | None = None, show_cache_clusters_not_in_replication_groups: str | None = None, **kwargs) -> dict:
    """Describe one or more ElastiCache cache clusters.

    This tool returns information about provisioned cache clusters. If a cache cluster ID
    is specified, information about only that cache cluster is returned. Otherwise, information
    about up to MaxRecords cache clusters is returned.

    Parameters:
        cache_cluster_id (Optional[str]): The identifier for the cache cluster to describe.
            If not provided, information about all cache clusters is returned.
        max_records (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxRecords value, a marker is included
            in the response so that the remaining results can be retrieved.
        marker (Optional[str]): An optional marker returned from a previous request. Use this marker
            for pagination of results from this operation. If this parameter is specified,
            the response includes only records beyond the marker, up to the value specified
            by MaxRecords.
        show_cache_node_info (Optional[bool]): Whether to include detailed information about
            cache nodes in the response.
        show_cache_clusters_not_in_replication_groups (Optional[bool]): Whether to show only
            cache clusters that are not members of a replication group.

    Returns:
        Dict containing information about the cache cluster(s), including:
        - CacheClusters: List of cache clusters
        - Marker: Pagination marker for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if cache_cluster_id is not None:
        params['CacheClusterId'] = cache_cluster_id
    if max_records is not None:
        params['MaxRecords'] = max_records
    if marker is not None:
        params['Marker'] = marker
    if show_cache_node_info is not None:
        params['ShowCacheNodeInfo'] = show_cache_node_info
    if show_cache_clusters_not_in_replication_groups is not None:
        params['ShowCacheClustersNotInReplicationGroups'] = show_cache_clusters_not_in_replication_groups
    params.update(kwargs)
    return client.describe_cache_clusters(**params)



def modify_cache_cluster(request: str, **kwargs) -> dict:
    """Modify an existing Amazon ElastiCache cache cluster."""
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['CacheClusterId'] = request
    params.update(kwargs)
    return client.modify_cache_cluster(**params)



def connect_jump_host_cache_cluster(cache_cluster_id: str, instance_id: str, **kwargs) -> dict:
    """Configures an existing EC2 instance as a jump host to access an ElastiCache cluster.

    Args:
        cache_cluster_id (str): ID of the ElastiCache cluster to connect to
        instance_id (str): ID of the EC2 instance to use as jump host

    Returns:
        Dict[str, Any]: Dictionary containing connection details and configuration status

    Raises:
        ValueError: If VPC compatibility check fails or required resources not found
    """
    client = boto3.client('elasticache')
    params = {}
    if cache_cluster_id is not None:
        params['CacheClusterId'] = cache_cluster_id
    params.update(kwargs)
    return client.describe_cache_clusters(**params)



def get_cost_and_usage(request: str, **kwargs) -> dict:
    """Get cost and usage data for ElastiCache resources.

    This tool retrieves cost and usage data for ElastiCache resources with customizable
    time periods and granularity. It uses default configurations for:
    - Metrics: BlendedCost, UnblendedCost, UsageQuantity
    - Group By: SERVICE dimension and Environment tag
    - Filter: Filtered to Amazon ElastiCache service

    Args:
        request: The GetCostAndUsageRequest object containing:
            - time_period: Time period in YYYY-MM-DD/YYYY-MM-DD format
            - granularity: Data granularity (DAILY, MONTHLY, or HOURLY)

    Returns:
        Dict containing the cost and usage data.
    """
    client = boto3.client('ce')
    params = {}
    if request is not None:
        params['TimePeriod'] = request
    params.update(kwargs)
    return client.get_cost_and_usage(**params)



def get_metric_statistics(metric_name: str, start_time: str, end_time: str, period: int, dimensions: str | None = None, statistics: str | None = None, extended_statistics: str | None = None, unit: str | None = None, **kwargs) -> dict:
    """Get CloudWatch metric statistics.

    Args:
        metric_name: The name of the metric
        start_time: The start time in ISO 8601 format
        end_time: The end time in ISO 8601 format
        period: The granularity, in seconds, of the returned data points
        dimensions: The dimensions to filter by
        statistics: The metric statistics to return
        extended_statistics: The percentile statistics to return
        unit: The unit for the metric

    Returns:
        Dict containing metric statistics
    """
    client = boto3.client('cloudwatch')
    params = {}
    if metric_name is not None:
        params['MetricName'] = metric_name
    if start_time is not None:
        params['StartTime'] = start_time
    if end_time is not None:
        params['EndTime'] = end_time
    if period is not None:
        params['Period'] = period
    if dimensions is not None:
        params['Dimensions'] = dimensions
    if statistics is not None:
        params['Statistics'] = statistics
    if extended_statistics is not None:
        params['ExtendedStatistics'] = extended_statistics
    if unit is not None:
        params['Unit'] = unit
    params.update(kwargs)
    return client.get_metric_statistics(**params)



def get_log_events(log_stream_name: str, log_group_name: str | None = None, log_group_identifier: str | None = None, start_time: str | None = None, end_time: str | None = None, next_token: str | None = None, limit: str | None = None, start_from_head: str | None = None, unmask: str | None = None, **kwargs) -> dict:
    """Get log events from CloudWatch Logs.

    Args:
        log_group_name: The name of the log group
        log_group_identifier: The unique identifier of the log group
        log_stream_name: The name of the log stream
        start_time: The start of the time range, inclusive
        end_time: The end of the time range, inclusive
        next_token: The token for the next set of items to return
        limit: The maximum number of log events to return
        start_from_head: If true, read from oldest to newest
        unmask: If true, unmask sensitive log data

    Returns:
        Dict containing:
        - events: List of log events
        - nextForwardToken: Token for getting the next set of events
        - nextBackwardToken: Token for getting the previous set of events
    """
    client = boto3.client('logs')
    params = {}
    if log_stream_name is not None:
        params['LogStreamName'] = log_stream_name
    if log_group_name is not None:
        params['LogGroupName'] = log_group_name
    if start_time is not None:
        params['StartTime'] = start_time
    if end_time is not None:
        params['EndTime'] = end_time
    if next_token is not None:
        params['NextToken'] = next_token
    if limit is not None:
        params['Limit'] = limit
    if start_from_head is not None:
        params['StartFromHead'] = start_from_head
    params.update(kwargs)
    return client.get_log_events(**params)



def create_log_group(log_group_name: str, kms_key_id: str | None = None, tags: str | None = None, log_group_class: str | None = None, **kwargs) -> dict:
    """Create a new CloudWatch Logs log group.

    Args:
        log_group_name: The name of the log group to create
        kms_key_id: The Amazon Resource Name (ARN) of the KMS key to use for encryption
        tags: The key-value pairs to use for the tags
        log_group_class: Specify one of the following classes:
            STANDARD - Standard log events (default)
            INFREQUENT_ACCESS - Infrequent Access log events

    Returns:
        Dict containing success message or error details
    """
    client = boto3.client('logs')
    params = {}
    if log_group_name is not None:
        params['LogGroupName'] = log_group_name
    if kms_key_id is not None:
        params['KmsKeyId'] = kms_key_id
    if tags is not None:
        params['Tags'] = tags
    if log_group_class is not None:
        params['LogGroupClass'] = log_group_class
    params.update(kwargs)
    return client.create_log_group(**params)



def describe_log_groups(account_identifiers: str | None = None, log_group_name_prefix: str | None = None, log_group_name_pattern: str | None = None, include_linked_accounts: str | None = None, log_group_class: str | None = None, log_group_identifiers: str | None = None, starting_token: str | None = None, page_size: str | None = None, max_items: str | None = None, **kwargs) -> dict:
    """Describe CloudWatch Logs log groups.

    Args:
        account_identifiers: List of account IDs to filter log groups
        log_group_name_prefix: Prefix to filter log groups by name
        log_group_name_pattern: Pattern to match log group names
        include_linked_accounts: Whether to include log groups from linked accounts
        log_group_class: Filter by log group class (STANDARD or INFREQUENT_ACCESS)
        log_group_identifiers: List of log group identifiers to describe
        starting_token: Token for starting the list from a specific page
        page_size: Number of records to include in each page
        max_items: Maximum number of records to return in total

    Returns:
        Dict containing log groups information or error details
    """
    client = boto3.client('logs')
    params = {}
    if log_group_name_prefix is not None:
        params['LogGroupNamePrefix'] = log_group_name_prefix
    if log_group_name_pattern is not None:
        params['LogGroupNamePattern'] = log_group_name_pattern
    if log_group_class is not None:
        params['LogGroupClass'] = log_group_class
    if log_group_identifiers is not None:
        params['LogGroupIdentifiers'] = log_group_identifiers
    if starting_token is not None:
        params['NextToken'] = starting_token
    if page_size is not None:
        params['Limit'] = page_size
    params.update(kwargs)
    return client.describe_log_groups(**params)



def describe_log_streams(log_group_name: str | None = None, log_group_identifier: str | None = None, log_stream_name_prefix: str | None = None, order_by: str | None = None, descending: str | None = None, starting_token: str | None = None, page_size: str | None = None, max_items: str | None = None, **kwargs) -> dict:
    """Describe CloudWatch Logs log streams.

    Args:
        log_group_name: The name of the log group containing the log streams to describe.
        log_group_identifier: The unique identifier of the log group.
        log_stream_name_prefix: The prefix to match when describing log streams.
        order_by: The parameter to sort by (LogStreamName or LastEventTime).
        descending: If true, results are returned in descending order.
        starting_token: Token for starting the list from a specific page.
        page_size: Number of records to include in each page.
        max_items: Maximum number of records to return in total.

    Returns:
        Dict containing information about the log streams or error details.
    """
    client = boto3.client('logs')
    params = {}
    if log_group_name is not None:
        params['LogGroupName'] = log_group_name
    if log_group_identifier is not None:
        params['LogGroupIdentifier'] = log_group_identifier
    if log_stream_name_prefix is not None:
        params['LogStreamNamePrefix'] = log_stream_name_prefix
    if order_by is not None:
        params['OrderBy'] = order_by
    if descending is not None:
        params['Descending'] = descending
    if starting_token is not None:
        params['NextToken'] = starting_token
    if page_size is not None:
        params['Limit'] = page_size
    params.update(kwargs)
    return client.describe_log_streams(**params)



def filter_log_events(log_group_name: str | None = None, log_group_identifier: str | None = None, log_stream_names: str | None = None, log_stream_name_prefix: str | None = None, start_time: str | None = None, end_time: str | None = None, filter_pattern: str | None = None, interleaved: str | None = None, unmask: str | None = None, starting_token: str | None = None, page_size: str | None = None, max_items: str | None = None, **kwargs) -> dict:
    """Filter log events from CloudWatch Logs.

    Args:
        log_group_name: The name of the log group
        log_group_identifier: The unique identifier of the log group
        log_stream_names: Optional list of log stream names to search
        log_stream_name_prefix: Optional prefix to match log stream names
        start_time: The start of the time range, inclusive
        end_time: The end of the time range, inclusive
        filter_pattern: The filter pattern to use
        interleaved: If true, multiple log streams are interleaved
        unmask: If true, unmask sensitive log data
        starting_token: Token for getting the next set of events
        page_size: Number of events to return per page
        max_items: Maximum number of events to return in total

    Returns:
        Dict containing:
        - events: List of filtered log events
        - searchedLogStreams: List of log streams that were searched
        - nextToken: Token for getting the next set of events
    """
    client = boto3.client('logs')
    params = {}
    if log_group_name is not None:
        params['LogGroupName'] = log_group_name
    if log_group_identifier is not None:
        params['LogGroupIdentifier'] = log_group_identifier
    if log_stream_names is not None:
        params['LogStreamNames'] = log_stream_names
    if log_stream_name_prefix is not None:
        params['LogStreamNamePrefix'] = log_stream_name_prefix
    if start_time is not None:
        params['StartTime'] = start_time
    if end_time is not None:
        params['EndTime'] = end_time
    if filter_pattern is not None:
        params['FilterPattern'] = filter_pattern
    if interleaved is not None:
        params['Interleaved'] = interleaved
    if unmask is not None:
        params['Unmask'] = unmask
    if starting_token is not None:
        params['NextToken'] = starting_token
    if page_size is not None:
        params['Limit'] = page_size
    params.update(kwargs)
    return client.filter_log_events(**params)



def list_delivery_streams(limit: str | None = None, delivery_stream_type: str | None = None, exclusive_start_delivery_stream_name: str | None = None, **kwargs) -> dict:
    """List your delivery streams.

    Args:
        limit: The maximum number of delivery streams to list
        delivery_stream_type: The delivery stream type. This can be one of the following values:
            DirectPut - Provider data is sent directly to the Firehose stream
            KinesisStreamAsSource - Data is sourced from an existing Kinesis stream
        exclusive_start_delivery_stream_name: The name of the delivery stream to start the list after

    Returns:
        Dict containing the list of delivery streams and whether there are more streams available
    """
    client = boto3.client('firehose')
    params = {}
    if limit is not None:
        params['Limit'] = limit
    if delivery_stream_type is not None:
        params['DeliveryStreamType'] = delivery_stream_type
    if exclusive_start_delivery_stream_name is not None:
        params['ExclusiveStartDeliveryStreamName'] = exclusive_start_delivery_stream_name
    params.update(kwargs)
    return client.list_delivery_streams(**params)



def batch_apply_update_action(service_update_name: str, replication_group_ids: str | None = None, cache_cluster_ids: str | None = None, **kwargs) -> dict:
    """Apply service update to multiple ElastiCache resources.

    Parameters:
        service_update_name (str): The unique ID of the service update to apply.
        replication_group_ids (Optional[List[str]]): List of replication group IDs to update.
            Either this or cache_cluster_ids must be provided.
        cache_cluster_ids (Optional[List[str]]): List of cache cluster IDs to update.
            Either this or replication_group_ids must be provided.

    Returns:
        Dict containing information about the batch update operation.
    """
    client = boto3.client('elasticache')
    params = {}
    if service_update_name is not None:
        params['ServiceUpdateName'] = service_update_name
    if replication_group_ids is not None:
        params['ReplicationGroupIds'] = replication_group_ids
    if cache_cluster_ids is not None:
        params['CacheClusterIds'] = cache_cluster_ids
    params.update(kwargs)
    return client.batch_apply_update_action(**params)



def batch_stop_update_action(service_update_name: str, replication_group_ids: str | None = None, cache_cluster_ids: str | None = None, **kwargs) -> dict:
    """Stop service update for multiple ElastiCache resources.

    Parameters:
        service_update_name (str): The unique ID of the service update to stop.
        replication_group_ids (Optional[List[str]]): List of replication group IDs to stop update.
            Either this or cache_cluster_ids must be provided.
        cache_cluster_ids (Optional[List[str]]): List of cache cluster IDs to stop update.
            Either this or replication_group_ids must be provided.

    Returns:
        Dict containing information about the batch stop operation.
    """
    client = boto3.client('elasticache')
    params = {}
    if service_update_name is not None:
        params['ServiceUpdateName'] = service_update_name
    if replication_group_ids is not None:
        params['ReplicationGroupIds'] = replication_group_ids
    if cache_cluster_ids is not None:
        params['CacheClusterIds'] = cache_cluster_ids
    params.update(kwargs)
    return client.batch_stop_update_action(**params)



def describe_cache_engine_versions(engine: str | None = None, engine_version: str | None = None, cache_parameter_group_family: str | None = None, max_records: str | None = None, marker: str | None = None, default_only: str | None = None, **kwargs) -> dict:
    """Returns a list of the available cache engines and their versions.

    Parameters:
        engine (Optional[str]): The cache engine to return. Valid values: memcached | redis | valkey
        engine_version (Optional[str]): The cache engine version to return.
            Example: memcached 1.4.14, redis 6.x, valkey 8.0
        cache_parameter_group_family (Optional[str]): The name of a specific cache parameter group family.
            Valid values are: memcached1.4 | memcached1.5 | memcached1.6 | redis2.6 | redis2.8 |
            redis3.2 | redis4.0 | redis5.0 | redis6.x | redis7.x | valkey7.x | valkey8.x
        max_records (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxRecords value, a marker is included
            in the response so that the remaining results can be retrieved.
        marker (Optional[str]): An optional marker returned from a previous request. Use this marker
            for pagination of results from this operation. If this parameter is specified,
            the response includes only records beyond the marker, up to the value specified
            by MaxRecords.
        default_only (Optional[bool]): If true, specifies that only the default version of the specified engine
            or engine and major version combination is to be returned.

    Returns:
        Dict containing information about the cache engine versions, including:
        - CacheEngineVersions: List of cache engine versions
        - Marker: Pagination marker for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if engine is not None:
        params['Engine'] = engine
    if engine_version is not None:
        params['EngineVersion'] = engine_version
    if cache_parameter_group_family is not None:
        params['CacheParameterGroupFamily'] = cache_parameter_group_family
    if max_records is not None:
        params['MaxRecords'] = max_records
    if marker is not None:
        params['Marker'] = marker
    if default_only is not None:
        params['DefaultOnly'] = default_only
    params.update(kwargs)
    return client.describe_cache_engine_versions(**params)



def describe_engine_default_parameters(cache_parameter_group_family: str, max_records: str | None = None, marker: str | None = None, **kwargs) -> dict:
    """Returns the default engine and system parameter information for the specified cache engine family.

    Parameters:
        cache_parameter_group_family (str): The name of the cache parameter group family.
            Valid values are: memcached1.4 | memcached1.5 | memcached1.6 | redis2.6 | redis2.8 |
            redis3.2 | redis4.0 | redis5.0 | redis6.x | redis7.x | valkey7.x | valkey8.x
        max_records (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxRecords value, a marker is included
            in the response so that the remaining results can be retrieved.
        marker (Optional[str]): An optional marker returned from a previous request. Use this marker
            for pagination of results from this operation. If this parameter is specified,
            the response includes only records beyond the marker, up to the value specified
            by MaxRecords.

    Returns:
        Dict containing information about the engine default parameters, including:
        - Parameters: List of parameters with their details
        - CacheParameterGroupFamily: The name of the cache parameter group family
        - Marker: Pagination marker for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if cache_parameter_group_family is not None:
        params['CacheParameterGroupFamily'] = cache_parameter_group_family
    if max_records is not None:
        params['MaxRecords'] = max_records
    if marker is not None:
        params['Marker'] = marker
    params.update(kwargs)
    return client.describe_engine_default_parameters(**params)



def describe_events(source_type: str | None = None, source_identifier: str | None = None, start_time: str | None = None, end_time: str | None = None, duration: str | None = None, max_records: str | None = None, marker: str | None = None, **kwargs) -> dict:
    """Returns events related to clusters, cache security groups, and parameter groups.

    Parameters:
        source_type (Optional[str]): The event source to retrieve events for. If not specified, all
            events are returned. Valid values: cache-cluster | cache-parameter-group |
            cache-security-group | cache-subnet-group | replication-group | user | user-group
        source_identifier (Optional[str]): The identifier of the event source for which events are
            returned. For example, if source_type is cache-cluster, you can specify a cluster
            identifier to see all events for only that cluster.
        start_time (Optional[datetime]): The beginning of the time interval to retrieve events for,
            specified in ISO 8601 format.
        end_time (Optional[datetime]): The end of the time interval to retrieve events for,
            specified in ISO 8601 format.
        duration (Optional[int]): The number of minutes worth of events to retrieve.
        max_records (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxRecords value, a marker is included
            in the response so that the remaining results can be retrieved.
        marker (Optional[str]): An optional marker returned from a previous request. Use this marker
            for pagination of results from this operation. If this parameter is specified,
            the response includes only records beyond the marker, up to the value specified
            by MaxRecords.

    Returns:
        Dict containing information about the events, including:
        - Events: List of events
        - Marker: Pagination marker for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if source_type is not None:
        params['SourceType'] = source_type
    if source_identifier is not None:
        params['SourceIdentifier'] = source_identifier
    if start_time is not None:
        params['StartTime'] = start_time
    if end_time is not None:
        params['EndTime'] = end_time
    if duration is not None:
        params['Duration'] = duration
    if max_records is not None:
        params['MaxRecords'] = max_records
    if marker is not None:
        params['Marker'] = marker
    params.update(kwargs)
    return client.describe_events(**params)



def describe_service_updates(service_update_name: str | None = None, service_update_status: str | None = None, starting_token: str | None = None, page_size: str | None = None, max_items: str | None = None, **kwargs) -> dict:
    """Returns details of the service updates.

    Parameters:
        service_update_name (Optional[str]): The unique ID of the service update to describe.
        service_update_status (Optional[List[str]]): List of status values to filter by.
            Valid values: available | cancelled | expired | complete
        starting_token (Optional[str]): An optional token returned from a previous request.
            Use this token for pagination of results from this operation.
        page_size (Optional[int]): The maximum number of records to include in each page
            of results.
        max_items (Optional[int]): The maximum number of records to include in the response.
            If more records exist than the specified MaxItems value, a marker is included
            in the response so that the remaining results can be retrieved.

    Returns:
        Dict containing information about the service updates, including:
        - ServiceUpdates: List of service updates
        - NextToken: Token for next set of results
    """
    client = boto3.client('elasticache')
    params = {}
    if service_update_name is not None:
        params['ServiceUpdateName'] = service_update_name
    if service_update_status is not None:
        params['ServiceUpdateStatus'] = service_update_status
    if starting_token is not None:
        params['Marker'] = starting_token
    if page_size is not None:
        params['MaxRecords'] = page_size
    if max_items is not None:
        params['MaxItems'] = max_items
    params.update(kwargs)
    return client.describe_service_updates(**params)



def delete_serverless_cache(serverless_cache_name: str, final_snapshot_name: str | None = None, **kwargs) -> dict:
    """Delete an Amazon ElastiCache serverless cache.

    This tool deletes a specified serverless cache from your AWS account.
    The cache must exist and be in a deletable state.

    Parameters:
        serverless_cache_name (str): Name of the serverless cache to delete.
        final_snapshot_name (Optional[str]): Name of the final snapshot to create before deletion.

    Returns:
        Dict containing the deletion response or error information.
    """
    client = boto3.client('elasticache')
    params = {}
    if serverless_cache_name is not None:
        params['ServerlessCacheName'] = serverless_cache_name
    if final_snapshot_name is not None:
        params['FinalSnapshotName'] = final_snapshot_name
    params.update(kwargs)
    return client.delete_serverless_cache(**params)



def describe_serverless_caches(serverless_cache_name: str | None = None, max_items: str | None = None, starting_token: str | None = None, page_size: str | None = None, **kwargs) -> dict:
    """Describe Amazon ElastiCache serverless caches in your AWS account.

    This tool retrieves detailed information about serverless caches including:
    - Cache configuration
    - Cache endpoints
    - Cache status
    - Cache size
    - Cache connections

    Parameters:
        serverless_cache_name (Optional[str]): Name of the serverless cache to describe. If not provided, describes all caches.
        max_items (Optional[int]): Maximum number of results to return.
        starting_token (Optional[str]): Token to start the list from a specific page.
        page_size (Optional[int]): Number of records to include in each page.

    Returns:
        Dict containing information about the serverless cache(s).
    """
    client = boto3.client('elasticache')
    params = {}
    if serverless_cache_name is not None:
        params['ServerlessCacheName'] = serverless_cache_name
    if max_items is not None:
        params['MaxResults'] = max_items
    if starting_token is not None:
        params['NextToken'] = starting_token
    if page_size is not None:
        params['MaxRecords'] = page_size
    params.update(kwargs)
    return client.describe_serverless_caches(**params)



def modify_serverless_cache(request: str, **kwargs) -> dict:
    """Modify an Amazon ElastiCache serverless cache.

    This tool modifies the configuration of an existing serverless cache including:
    - Cache description
    - Engine version
    - Snapshot settings
    - Usage limits
    - Security groups
    - User groups

    Parameters:
        serverless_cache_name (str): Name of the serverless cache to modify.
        apply_immediately (Optional[bool]): Whether to apply changes immediately or during maintenance window.
        description (Optional[str]): New description for the cache.
        major_engine_version (Optional[str]): New major engine version.
        snapshot_retention_limit (Optional[int]): Number of days for which ElastiCache retains automatic snapshots.
        daily_snapshot_time (Optional[str]): Time range (in UTC) when daily snapshots are taken (e.g., '04:00-05:00').
        cache_usage_limits (Optional[CacheUsageLimits]): New usage limits for the cache. Structure:
            {
                "DataStorage": {
                    "Maximum": int,  # Maximum storage in GB
                    "Minimum": int,  # Minimum storage in GB
                    "Unit": "GB"     # Storage unit (currently only GB is supported)
                },
                "ECPUPerSecond": {
                    "Maximum": int,  # Maximum ECPU per second
                    "Minimum": int   # Minimum ECPU per second
                }
            }
        security_group_ids (Optional[List[str]]): List of security group IDs.
        user_group_id (Optional[str]): ID of the user group to associate with the cache.

    Returns:
        Dict containing information about the modified serverless cache.
    """
    client = boto3.client('elasticache')
    params = {}
    if request is not None:
        params['ServerlessCacheName'] = request
    params.update(kwargs)
    return client.modify_serverless_cache(**params)



def create_jump_host_serverless_cache(serverless_cache_name: str, key_name: str, subnet_id: str | None = None, security_group_id: str | None = None, instance_type: str | None = None, **kwargs) -> dict:
    """Creates an EC2 jump host instance to access an ElastiCache serverless cache via SSH tunnel.

    Args:
        serverless_cache_name (str): Name of the ElastiCache serverless cache to connect to
        key_name (str): Name of the EC2 key pair to use for SSH access
        subnet_id (str, optional): ID of the subnet to launch the EC2 instance in (must be public).
            If not provided and serverless cache uses default VPC, will auto-select a default subnet.
        security_group_id (str, optional): ID of the security group to assign to the EC2 instance.
            If not provided and serverless cache uses default VPC, will use the default security group.
        instance_type (str, optional): EC2 instance type. Defaults to "t3.small"

    Returns:
        Dict[str, Any]: Dictionary containing the created EC2 instance details

    Raises:
        ValueError: If subnet is not public or VPC compatibility check fails
    """
    client = boto3.client('ec2')
    params = {}
    if key_name is not None:
        params['KeyName'] = key_name
    if subnet_id is not None:
        params['SubnetId'] = subnet_id
    if security_group_id is not None:
        params['SecurityGroupIds'] = security_group_id
    if instance_type is not None:
        params['InstanceType'] = instance_type
    params.update(kwargs)
    return client.run_instances(**params)



