#!/usr/bin/env bash
# Auto-generated AWS CLI functions for aws-serverless-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# sam_logs: Fetches CloudWatch logs that are generated by Lambda function and API GW resources in a SAM application.

        Requirements:
        - AWS SAM CLI MUST be installed and configured in your environment
        - Your SAM application MUST be deployed and receiving traffic

        After deploying your serverless application, you can use this tool to monitor it to provide insights on
        its operations and detect anomalies. Use this tool to help troubleshoot invocation failures, and function code errors
        and find root causes. Lambda function logs contain application logs emitted by your code and platform level logs emitted by the Lambda service.

        Usage tips:
        - Use logs to debug out-of-memory errors. Platform logs indicate memory usage in the REPORT line. If memory usage is high compared to
        configured memory, out-of-memory could be causing invocation failures.
        - Use logs to debug timeouts errors. Functions that have timed-out contain a log line like ' Task timed out after 3.00 seconds'.

        Note: You MUST explicitly enable logging on API GW resources

        Returns:
            Dict: Log retrieval result
        
# Usage: sam_logs <resource_name> <stack_name> <start_time> <end_time> <region> <profile> <cw_log_group> <config_env> <config_file> <save_params>
sam_logs() {
    aws logs filter-log-events \
        --log-group-name "$CW_LOG_GROUP" \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --region "$REGION" \
        --profile "$PROFILE"
}


# list_registries: Lists the registries in your account.

        REQUIREMENTS:
        - For AWS service events, you MUST use the aws.events registry directly
        - For custom schemas, you MAY use LOCAL scope to manage your own registries
        - When searching AWS service events, you SHOULD use the AWS scope

        USAGE PATTERNS:
        1. Finding AWS Service Event Schemas:
        - Use aws.events registry directly instead of searching
        - Filter by AWS scope to see only AWS-provided schemas

        2. Managing Custom Schemas:
        - Use LOCAL scope to view your custom registries
        - Apply registry_name_prefix to find specific registry groups
        
# Usage: list_registries <registry_name_prefix> <scope> <limit> <next_token>
list_registries() {
    aws eventbridge list-registries \
        --name-prefix "$REGISTRY_NAME_PREFIX" \
        --scope "$SCOPE" \
        --limit "$LIMIT" \
        --next-token "$NEXT_TOKEN"
}


# search_schema: Search for schemas in a registry using keywords.

        REQUIREMENTS:
        - You MUST use this tool to find schemas for AWS service events
        - You MUST search in the "aws.events" registry for AWS service events
        - You MUST use this tool when implementing Lambda functions that consume events from EventBridge
        - You SHOULD prefix search keywords with "aws." for optimal results (e.g., "aws.s3", "aws.ec2")
        - You MAY filter results using additional keywords for specific event types

        USE CASES:

        1. Lambda Function Development with EventBridge:
        - CRITICAL: Required for Lambda functions consuming events from EventBridge
        - Search for event schemas your function needs to process
        - Example: "aws.s3" for S3 events, "aws.dynamodb" for DynamoDB streams
        - Use results with describe_schema to get complete event structure

        2. EventBridge Rule Creation:
        - Find schemas to create properly structured event patterns
        - Example: "aws.ec2" for EC2 instance state changes
        - Ensure exact field names and types in rule patterns

        IMPLEMENTATION FLOW:
        1. Search aws.events registry for service schemas
        2. Note relevant schema names from results
        3. Use describe_schema to get complete definitions
        4. Implement handlers using exact schema structure
        
# Usage: search_schema <keywords> <registry_name> <limit> <next_token>
search_schema() {
    aws schemas search-schemas \
        --keywords "$KEYWORDS" \
        --registry-name "$REGISTRY_NAME" \
        --limit "$LIMIT" \
        --next-token "$NEXT_TOKEN"
}


# describe_schema: Retrieve the schema definition for the specified schema version.

        REQUIREMENTS:
        - You MUST use this tool to get complete schema definitions before implementing handlers
        - You MUST use this tool when implementing Lambda functions that consume events from EventBridge
        - You MUST use the returned schema structure for type-safe event handling
        - You SHOULD use the latest schema version unless specifically required otherwise
        - You MUST validate all required fields defined in the schema

        USE CASES:

        1. Lambda Function Handlers with EventBridge:
        You MUST:
        - CRITICAL: Required for Lambda functions consuming events from EventBridge
        - Implement handlers using the exact event structure
        - Validate all required fields defined in schema
        - Handle optional fields appropriately
        - Ensure type safety for EventBridge-sourced events

        You SHOULD:
        - Generate strongly typed code based on schema
        - Implement error handling for missing fields
        - Document any assumptions about structure

        2. EventBridge Rules:
        You MUST:
        - Create patterns that exactly match schema
        - Use correct field names and value types
        - Include all required fields in patterns

        You SHOULD:
        - Test patterns against sample events
        - Document pattern matching logic
        - Consider schema versions in design

        The schema content provides complete event structure with all fields and types, ensuring correct event handling.
        
# Usage: describe_schema <registry_name> <schema_name> <schema_version>
describe_schema() {
    aws schemas describe-schema \
        --registry-name "$REGISTRY_NAME" \
        --schema-name "$SCHEMA_NAME" \
        --schema-version "$SCHEMA_VERSION"
}


# get_metrics: Retrieves CloudWatch metrics from a deployed web application.

        Use this tool get metrics on error rates, latency, throttles, etc. of Lambda functions, API Gateways, or CloudFront distributions.
        This tool can help provide insights into anomalies and monitor operations, which can help with troubleshooting.

        Returns:
            Dict: Metrics retrieval result
        
# Usage: get_metrics <project_name> <start_time> <end_time> <period> <resources> <function_name> <distribution_id> <region> <stage>
get_metrics() {
    aws cloudwatch get-metric-data \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --period "$PERIOD" \
        --metric-data-queries "$RESOURCES"
}


# update_webapp_frontend: Update the frontend assets of a deployed web application.

        This tool uploads new frontend assets to S3 and optionally invalidates the CloudFront cache.
        
# Usage: update_webapp_frontend <project_name> <project_root> <built_assets_path> <invalidate_cache> <region>
update_webapp_frontend() {
    aws s3 sync \
        --bucket "$PROJECT_NAME" \
        --prefix "$PROJECT_ROOT" \
        --source "$BUILT_ASSETS_PATH"
}


# secure_esm_sqs_policy: Generate security-approved IAM policy for SQS ESM with scoped permissions. Uses pre-approved templates, not LLM generation.
# Usage: secure_esm_sqs_policy <region> <account> <queue_name> <function_name> <partition>
secure_esm_sqs_policy() {
    aws iam create-policy \
        --policy-name "$QUEUE_NAME" \
        --policy-document "$FUNCTION_NAME" \
        --description "$QUEUE_NAME"
}


# secure_esm_kinesis_policy: Generate security-approved IAM policy for Kinesis ESM with scoped permissions. Uses pre-approved templates, not LLM generation.
# Usage: secure_esm_kinesis_policy <region> <account> <stream_name> <function_name> <partition>
secure_esm_kinesis_policy() {
    aws iam create-policy \
        --policy-name "$STREAM_NAME" \
        --policy-document "$FUNCTION_NAME" \
        --description "$STREAM_NAME"
}


# secure_esm_dynamodb_policy: Generate security-approved IAM policy for DynamoDB Streams ESM with scoped permissions. Uses pre-approved templates, not LLM generation.
# Usage: secure_esm_dynamodb_policy <region> <account> <table_name> <function_name> <partition>
secure_esm_dynamodb_policy() {
    aws iam create-policy \
        --policy-name "$TABLE_NAME" \
        --policy-document "$FUNCTION_NAME" \
        --description "$DYNAMODB STREAMS ESM POLICY"
}


