"""Auto-generated boto3 functions for amazon-timestream-influxdb-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def CreateDbInstance(db_instance_name: str, db_instance_type: str, password: str, allocated_storage_gb: int, vpc_security_group_ids: list, vpc_subnet_ids: list, publicly_accessible: bool | None = None, username: str | None = None, organization: str | None = None, bucket: str | None = None, db_storage_type: str | None = None, deployment_type: str | None = None, networkType: str | None = None, port: str | None = None, db_parameter_group_id: str | None = None, tags: str | None = None, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Create a new Timestream for InfluxDB database instance"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if db_instance_name is not None:
        params['DbInstanceName'] = db_instance_name
    if db_instance_type is not None:
        params['DbInstanceType'] = db_instance_type
    if password is not None:
        params['Password'] = password
    if allocated_storage_gb is not None:
        params['AllocatedStorageGb'] = allocated_storage_gb
    if vpc_security_group_ids is not None:
        params['VpcSecurityGroupIds'] = vpc_security_group_ids
    if vpc_subnet_ids is not None:
        params['VpcSubnetIds'] = vpc_subnet_ids
    if publicly_accessible is not None:
        params['PubliclyAccessible'] = publicly_accessible
    if username is not None:
        params['Username'] = username
    if organization is not None:
        params['Organization'] = organization
    if bucket is not None:
        params['Bucket'] = bucket
    if db_storage_type is not None:
        params['DbStorageType'] = db_storage_type
    if deployment_type is not None:
        params['DeploymentType'] = deployment_type
    if networkType is not None:
        params['NetworkType'] = networkType
    if port is not None:
        params['Port'] = port
    if db_parameter_group_id is not None:
        params['DbParameterGroupId'] = db_parameter_group_id
    if tags is not None:
        params['Tags'] = tags
    params.update(kwargs)
    return client.create_db_instance(**params)



def LsInstancesOfCluster(db_cluster_id: str, next_token: str | None = None, max_results: str | None = None, **kwargs) -> dict:
    """List all Timestream for InfluxDB instances belonging to a specific DB cluster."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if db_cluster_id is not None:
        params['DbClusterId'] = db_cluster_id
    if next_token is not None:
        params['NextToken'] = next_token
    if max_results is not None:
        params['MaxResults'] = max_results
    params.update(kwargs)
    return client.list_db_instances(**params)



def ListDbInstances(next_token: str | None = None, max_results: str | None = None, **kwargs) -> dict:
    """List all Timestream for InfluxDB DB instances"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if next_token is not None:
        params['NextToken'] = next_token
    if max_results is not None:
        params['MaxResults'] = max_results
    params.update(kwargs)
    return client.list_db_instances(**params)



def ListDbClusters(next_token: str | None = None, max_results: str | None = None, **kwargs) -> dict:
    """List all Timestream for InfluxDB DB clusters."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if next_token is not None:
        params['NextToken'] = next_token
    if max_results is not None:
        params['MaxResults'] = max_results
    params.update(kwargs)
    return client.list_db_clusters(**params)



def GetDbParameterGroup(identifier: str, **kwargs) -> dict:
    """Get a Timestream for InfluxDB DB parameter group details for a db_parameter_group_id"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if identifier is not None:
        params['DbParameterGroupIdentifier'] = identifier
    params.update(kwargs)
    return client.get_db_parameter_group(**params)



def GetDbInstance(identifier: str, **kwargs) -> dict:
    """Returns a Timestream for InfluxDB DB instance details by the instance-identifier"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if identifier is not None:
        params['DbInstanceId'] = identifier
    params.update(kwargs)
    return client.get_db_instance(**params)



def GetDbCluster(db_cluster_id: str, **kwargs) -> dict:
    """Returns a Timestream for InfluxDB DB cluster details by the db_cluster_id"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if db_cluster_id is not None:
        params['DbClusterId'] = db_cluster_id
    params.update(kwargs)
    return client.get_db_cluster(**params)



def DeleteDbInstance(identifier: str, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Deletes a Timestream for InfluxDB DB instance by the instance-identifier"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if identifier is not None:
        params['DbInstanceId'] = identifier
    params.update(kwargs)
    return client.delete_db_instance(**params)



def DeleteDbCluster(db_cluster_id: str, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Deletes a Timestream for InfluxDB cluster by the db_cluster_id"""
    client = boto3.client('timestream-influxdb')
    params = {}
    if db_cluster_id is not None:
        params['DbClusterId'] = db_cluster_id
    params.update(kwargs)
    return client.delete_db_cluster(**params)



def ListDbParamGroups(next_token: str | None = None, max_results: str | None = None, **kwargs) -> dict:
    """List all Timestream for InfluxDB DB parameter groups."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if next_token is not None:
        params['NextToken'] = next_token
    if max_results is not None:
        params['MaxResults'] = max_results
    params.update(kwargs)
    return client.list_db_parameter_groups(**params)



def ListTagsForResource(resource_arn: str, **kwargs) -> dict:
    """A list of tags applied to the resource."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if resource_arn is not None:
        params['ResourceArn'] = resource_arn
    params.update(kwargs)
    return client.list_tags_for_resource(**params)



def TagResource(resource_arn: str, tags: dict, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Tags are composed of a Key/Value pairs. Apply them to Timestream for InfluxDB resource."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if resource_arn is not None:
        params['ResourceArn'] = resource_arn
    if tags is not None:
        params['Tags'] = tags
    params.update(kwargs)
    return client.tag_resource(**params)



def UntagResource(resource_arn: str, tag_keys: list, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Removes the tags, identified by the keys, from the specified resource."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if resource_arn is not None:
        params['ResourceArn'] = resource_arn
    if tag_keys is not None:
        params['TagKeys'] = tag_keys
    params.update(kwargs)
    return client.untag_resource(**params)



def UpdateDbCluster(db_cluster_id: str, db_instance_type: str | None = None, db_parameter_group_identifier: str | None = None, port: str | None = None, failover_mode: str | None = None, log_delivery_configuration: str | None = None, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Updates a Timestream for InfluxDB cluster."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if db_cluster_id is not None:
        params['DbClusterId'] = db_cluster_id
    if db_instance_type is not None:
        params['DbInstanceType'] = db_instance_type
    if db_parameter_group_identifier is not None:
        params['DbParameterGroupIdentifier'] = db_parameter_group_identifier
    if port is not None:
        params['Port'] = port
    if failover_mode is not None:
        params['FailoverMode'] = failover_mode
    if log_delivery_configuration is not None:
        params['LogDeliveryConfiguration'] = log_delivery_configuration
    params.update(kwargs)
    return client.update_db_cluster(**params)



def UpdateDbInstance(identifier: str, db_instance_type: str | None = None, db_parameter_group_identifier: str | None = None, port: str | None = None, allocated_storage_gb: str | None = None, db_storage_type: str | None = None, deployment_type: str | None = None, log_delivery_configuration: str | None = None, tool_write_mode: bool | None = None, **kwargs) -> dict:
    """Updates a Timestream for InfluxDB DB instance."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if identifier is not None:
        params['DbInstanceIdentifier'] = identifier
    if db_instance_type is not None:
        params['DbInstanceType'] = db_instance_type
    if db_parameter_group_identifier is not None:
        params['DbParameterGroupIdentifier'] = db_parameter_group_identifier
    if port is not None:
        params['Port'] = port
    if allocated_storage_gb is not None:
        params['AllocatedStorageGb'] = allocated_storage_gb
    if db_storage_type is not None:
        params['DbStorageType'] = db_storage_type
    if deployment_type is not None:
        params['DeploymentType'] = deployment_type
    if log_delivery_configuration is not None:
        params['LogDeliveryConfiguration'] = log_delivery_configuration
    params.update(kwargs)
    return client.update_db_instance(**params)



def LsInstancesByStatus(status: str, **kwargs) -> dict:
    """Returns a list of Timestream for InfluxDB DB instances filtered by status (case-insensitive)."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if status is not None:
        params['Status'] = status
    params.update(kwargs)
    return client.list_db_instances(**params)



def ListClustersByStatus(status: str, **kwargs) -> dict:
    """Returns a list of Timestream for InfluxDB DB clusters filtered by status (case-insensitive)."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if status is not None:
        params['ClusterStatus'] = status
    params.update(kwargs)
    return client.list_clusters(**params)



def CreateDbParamGroup(name: str, tool_write_mode: bool | None = None, description: str | None = None, parameters: str | None = None, tags: str | None = None, **kwargs) -> dict:
    """Creates a new Timestream for InfluxDB DB parameter group to associate with DB instances."""
    client = boto3.client('timestream-influxdb')
    params = {}
    if name is not None:
        params['Name'] = name
    if description is not None:
        params['Description'] = description
    if parameters is not None:
        params['Parameters'] = parameters
    if tags is not None:
        params['Tags'] = tags
    params.update(kwargs)
    return client.create_db_parameter_group(**params)



