#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-elasticache-memcached-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# cache_get: Get a value from the cache.

    Args:
        key: The key to retrieve

    Returns:
        Value or error message
    
# Usage: cache_get <key>
cache_get() {
    aws elasticache get-item \
        --key "$KEY"
}


# cache_gets: Get a value and its CAS token from the cache.

    Args:
        key: The key to retrieve

    Returns:
        Value and CAS token or error message
    
# Usage: cache_gets <key>
cache_gets() {
    aws elasticache get-item \
        --key "$KEY"
}


# cache_get_many: Get multiple values from the cache.

    Args:
        keys: List of keys to retrieve

    Returns:
        Dictionary of key-value pairs or error message
    
# Usage: cache_get_many <keys>
cache_get_many() {
    aws elasticache get-many \
        --keys "$KEYS"
}


# cache_set: Set a value in the cache.

    Args:
        key: The key to set
        value: The value to store
        expire: Optional expiration time in seconds

    Returns:
        Success message or error message
    
# Usage: cache_set <key> <value> <expire>
cache_set() {
    aws elasticache set-cache-value \
        --key "$KEY" \
        --value "$VALUE" \
        --expiration "$EXPIRE"
}


# cache_cas: Set a value using CAS (Check And Set).

    Args:
        key: The key to set
        value: The value to store
        cas: CAS token from gets()
        expire: Optional expiration time in seconds

    Returns:
        Success message or error message
    
# Usage: cache_cas <key> <value> <cas> <expire>
cache_cas() {
    aws elasticache set-cache-parameter \
        --key "$KEY" \
        --value "$VALUE" \
        --cas "$CAS" \
        --ttl "$EXPIRE"
}


# cache_set_many: Set multiple values in the cache.

    Args:
        mapping: Dictionary of key-value pairs
        expire: Optional expiration time in seconds

    Returns:
        Success message or error message
    
# Usage: cache_set_many <mapping> <expire>
cache_set_many() {
    aws elasticache set-many \
        --mapping "$MAPPING" \
        --expire "$EXPIRE"
}


# cache_set_multi: Set multiple values in the cache (alias for set_many).

    Args:
        mapping: Dictionary of key-value pairs
        expire: Optional expiration time in seconds

    Returns:
        Success message or error message
    
# Usage: cache_set_multi <mapping> <expire>
cache_set_multi() {
    aws elasticache set-multi \
        --mapping "$MAPPING" \
        --expire "$EXPIRE"
}


# cache_replace: Replace a value in the cache only if the key exists.

    Args:
        key: The key to replace
        value: The new value
        expire: Optional expiration time in seconds

    Returns:
        Success message or error message
    
# Usage: cache_replace <key> <value> <expire>
cache_replace() {
    aws elasticache replace-cache-value \
        --key "$KEY" \
        --value "$VALUE" \
        --expiration "$EXPIRE"
}


# cache_prepend: Prepend a string to an existing value.

    Args:
        key: The key to prepend to
        value: String to prepend

    Returns:
        Success message or error message
    
# Usage: cache_prepend <key> <value>
cache_prepend() {
    aws elasticache prepend-value \
        --key "$KEY" \
        --value "$VALUE"
}


# cache_delete: Delete a value from the cache.

    Args:
        key: The key to delete

    Returns:
        Success message or error message
    
# Usage: cache_delete <key>
cache_delete() {
    aws elasticache delete-cache-cluster \
        --cache-cluster-id "$KEY"
}


# cache_incr: Increment a counter in the cache.

    Args:
        key: The key to increment
        value: Amount to increment by (default 1)

    Returns:
        New value or error message
    
# Usage: cache_incr <key> <value>
cache_incr() {
    aws elasticache increment-counter \
        --key "$KEY" \
        --value "$VALUE"
}


# cache_decr: Decrement a counter in the cache.

    Args:
        key: The key to decrement
        value: Amount to decrement by (default 1)

    Returns:
        New value or error message
    
# Usage: cache_decr <key> <value>
cache_decr() {
    aws elasticache decrement-counter \
        --key "$KEY" \
        --decrement-amount "$VALUE"
}


# cache_flush_all: Flush all cache entries.

    Args:
        delay: Optional delay in seconds before flushing

    Returns:
        Success message or error message
    
# Usage: cache_flush_all <delay>
cache_flush_all() {
    aws elasticache flush-cache-cluster \
        --cache-cluster-id "$SERVER"
}


