"""Auto-generated boto3 functions for aws-msk-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def describe_cluster_operation(region: str, cluster_operation_arn: str, **kwargs) -> dict:
    """Gets information about a cluster operation."""
    client = boto3.client('kafka')
    params = {}
    if cluster_operation_arn is not None:
        params['ClusterOperationArn'] = cluster_operation_arn
    params.update(kwargs)
    return client.describe_cluster_operation(**params)



def describe_vpc_connection(region: str, vpc_connection_arn: str, **kwargs) -> dict:
    """Gets detailed information about a VPC connection."""
    client = boto3.client('kafka')
    params = {}
    if vpc_connection_arn is not None:
        params['VpcConnectionArn'] = vpc_connection_arn
    params.update(kwargs)
    return client.describe_vpc_connection(**params)



def get_configuration_info(region: str, action: str, arn: str, kwargs: dict | None = None, **kwargs) -> dict:
    """Gets information about MSK configurations."""
    client = boto3.client('kafka')
    params = {}
    if arn is not None:
        params['ConfigurationArn'] = arn
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.describe_configuration(**params)



def list_tags_for_resource(region: str, arn: str, **kwargs) -> dict:
    """Lists all tags for an MSK resource."""
    client = boto3.client('kafka')
    params = {}
    if arn is not None:
        params['ResourceArn'] = arn
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.list_tags_for_resource(**params)



def list_topics(region: str, cluster_arn: str, topic_name_filter: str | None = None, max_results: str | None = None, next_token: str | None = None, **kwargs) -> dict:
    """Returns all topics in an MSK cluster."""
    client = boto3.client('kafka')
    params = {}
    if cluster_arn is not None:
        params['ClusterArn'] = cluster_arn
    if max_results is not None:
        params['MaxResults'] = max_results
    if next_token is not None:
        params['NextToken'] = next_token
    if topic_name_filter is not None:
        params['Filter'] = topic_name_filter
    params.update(kwargs)
    return client.list_topics(**params)



def describe_topic(region: str, cluster_arn: str, topic_name: str, **kwargs) -> dict:
    """Returns details for a specific topic on an MSK cluster."""
    client = boto3.client('kafka')
    params = {}
    if cluster_arn is not None:
        params['ClusterArn'] = cluster_arn
    if topic_name is not None:
        params['TopicName'] = topic_name
    params.update(kwargs)
    return client.describe_topic(**params)



def describe_topic_partitions(region: str, cluster_arn: str, topic_name: str, max_results: str | None = None, next_token: str | None = None, **kwargs) -> dict:
    """Returns partition information for a specific topic on an MSK cluster."""
    client = boto3.client('kafka')
    params = {}
    if cluster_arn is not None:
        params['ClusterArn'] = cluster_arn
    if max_results is not None:
        params['MaxResults'] = max_results
    if next_token is not None:
        params['NextToken'] = next_token
    params.update(kwargs)
    return client.list_cluster_operations(**params)



def list_customer_iam_access(region: str, cluster_arn: str, **kwargs) -> dict:
    """Lists IAM access information for an MSK cluster."""
    client = boto3.client('kafka')
    params = {}
    if cluster_arn is not None:
        params['ClusterArn'] = cluster_arn
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.list_cluster_operations(**params)



def get_cluster_best_practices(instance_type: str, number_of_brokers: int, **kwargs) -> dict:
    """Gets best practices and quotas for AWS MSK clusters."""
    client = boto3.client('kafka')
    params = {}
    if instance_type is not None:
        params['ClusterOperationArn'] = instance_type
    if number_of_brokers is not None:
        params['NumberOfBrokerNodes'] = number_of_brokers
    params.update(kwargs)
    return client.describe_cluster_operation(**params)



