"""Auto-generated boto3 functions for amazon-aurora-dsql-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def readonly_query(sql: str, **kwargs) -> dict:
    """Run a read-only SQL query against the configured Aurora DSQL cluster.

Aurora DSQL is distributed SQL database with Postgres compatibility. The following table
summarizes `SELECT` functionality that is expected to work. Items not in this table may
also be supported, as this is a point in time snapshot.
| Primary clause                  | Supported clauses     |
|---------------------------------|-----------------------|
| FROM                            |                       |
| GROUP BY                        | ALL, DISTINCT         |
| ORDER BY                        | ASC, DESC, NULLS      |
| LIMIT                           |                       |
| DISTINCT                        |                       |
| HAVING                          |                       |
| USING                           |                       |
| WITH (common table expressions) |                       |
| INNER JOIN                      | ON                    |
| OUTER JOIN                      | LEFT, RIGHT, FULL, ON |
| CROSS JOIN                      | ON                    |
| UNION                           | ALL                   |
| INTERSECT                       | ALL                   |
| EXCEPT                          | ALL                   |
| OVER                            | RANK (), PARTITION BY |
| FOR UPDATE                      |                       |
"""
    client = boto3.client('rds-data')
    params = {}
    if cluster_arn is not None:
        params['ClusterArn'] = cluster_arn
    if secret_arn is not None:
        params['SecretArn'] = secret_arn
    if sql is not None:
        params['Sql'] = sql
    params.update(kwargs)
    return client.execute_statement(**params)



def get_schema(table_name: str, **kwargs) -> dict:
    """Get the schema of the given table"""
    client = boto3.client('rds')
    params = {}
    if table_name is not None:
        params['DBClusterEndpointIdentifier'] = table_name
    params.update(kwargs)
    return client.describe_db_cluster_endpoints(**params)



def dsql_search_documentation(search_phrase: str, limit: str | None = None, **kwargs) -> dict:
    """Search Aurora DSQL documentation"""
    client = boto3.client('rds')
    params = {}
    if search_phrase is not None:
        params['SearchPhrase'] = search_phrase
    if limit is not None:
        params['MaxResults'] = limit
    params.update(kwargs)
    return client.search_documentation(**params)



