#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-mq-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# delete_broker: Execute the AWS AmazonMQ `delete_broker` operation.
# Usage: delete_broker <region> <BrokerId>
delete_broker() {
    aws mq delete-broker \
        --broker-id "$BROKERID" \
        --region "$REGION"
}


# delete_configuration: Execute the AWS AmazonMQ `delete_configuration` operation.
# Usage: delete_configuration <region> <ConfigurationId>
delete_configuration() {
    aws mq delete-configuration \
        --configuration-id "$CONFIGURATIONID" \
        --region "$REGION"
}


# describe_broker: Execute the AWS AmazonMQ `describe_broker` operation.
# Usage: describe_broker <region> <BrokerId>
describe_broker() {
    aws mq describe-broker \
        --broker-id "$BROKERID" \
        --region "$REGION"
}


# describe_broker_engine_types: Execute the AWS AmazonMQ `describe_broker_engine_types` operation.
# Usage: describe_broker_engine_types <region> <EngineType> <MaxResults> <NextToken>
describe_broker_engine_types() {
    aws mq describe-broker-engine-types \
        --engine-type "$ENGINETYPE" \
        --max-results "$MAXRESULTS" \
        --next-token "$NEXTTOKEN"
}


# describe_broker_instance_options: Execute the AWS AmazonMQ `describe_broker_instance_options` operation.
# Usage: describe_broker_instance_options <region> <EngineType> <HostInstanceType> <MaxResults> <NextToken> <StorageType>
describe_broker_instance_options() {
    aws mq describe-broker-instance-options \
        --region "$REGION" \
        --engine-type "$ENGINETYPE" \
        --host-instance-type "$HOSTINSTANCETYPE" \
        --max-results "$MAXRESULTS" \
        --next-token "$NEXTTOKEN" \
        --storage-type "$STORAGETYPE"
}


# describe_configuration: Execute the AWS AmazonMQ `describe_configuration` operation.
# Usage: describe_configuration <region> <ConfigurationId>
describe_configuration() {
    aws mq describe-configuration \
        --configuration-id "$CONFIGURATIONID" \
        --region "$REGION"
}


# describe_configuration_revision: Execute the AWS AmazonMQ `describe_configuration_revision` operation.
# Usage: describe_configuration_revision <region> <ConfigurationRevision> <ConfigurationId>
describe_configuration_revision() {
    aws mq describe-configuration-revision \
        --configuration-id "$CONFIGURATIONID" \
        --configuration-revision "$CONFIGURATIONREVISION"
}


# describe_user: Execute the AWS AmazonMQ `describe_user` operation.
# Usage: describe_user <region> <Username> <BrokerId>
describe_user() {
    aws mq describe-user \
        --broker-id "$BROKERID" \
        --username "$USERNAME" \
        --region "$REGION"
}


# list_brokers: Execute the AWS AmazonMQ `list_brokers` operation.
# Usage: list_brokers <region> <MaxResults> <NextToken>
list_brokers() {
    aws mq list-brokers \
        --region "$REGION" \
        --max-results "$MAXRESULTS" \
        --next-token "$NEXTTOKEN"
}


# list_configuration_revisions: Execute the AWS AmazonMQ `list_configuration_revisions` operation.
# Usage: list_configuration_revisions <region> <ConfigurationId> <MaxResults> <NextToken>
list_configuration_revisions() {
    aws mq list-configuration-revisions \
        --configuration-id "$CONFIGURATIONID" \
        --max-results "$MAXRESULTS" \
        --next-token "$NEXTTOKEN"
}


# list_configurations: Execute the AWS AmazonMQ `list_configurations` operation.
# Usage: list_configurations <region> <MaxResults> <NextToken>
list_configurations() {
    aws mq list-configurations \
        --region "$REGION" \
        --max-results "$MAXRESULTS" \
        --next-token "$NEXTTOKEN"
}


# list_tags: Execute the AWS AmazonMQ `list_tags` operation.
# Usage: list_tags <region> <ResourceArn>
list_tags() {
    aws mq list-tags-for-resource \
        --resource-arn "$RESOURCEARN" \
        --region "$REGION"
}


# list_users: Execute the AWS AmazonMQ `list_users` operation.
# Usage: list_users <region> <BrokerId> <MaxResults> <NextToken>
list_users() {
    aws iam list-users \
        --path-prefix "$PATH_PREFIX" \
        --max-items "$MAX_ITEMS"
}


# promote: Execute the AWS AmazonMQ `promote` operation.
# Usage: promote <region> <Mode> <BrokerId>
promote() {
    aws mq promote-broker \
        --broker-id "$BROKERID" \
        --mode "$MODE"
}


# reboot_broker: Execute the AWS AmazonMQ `reboot_broker` operation.
# Usage: reboot_broker <region> <BrokerId>
reboot_broker() {
    aws mq reboot-broker \
        --broker-id "$BROKERID" \
        --region "$REGION"
}


# update_broker: Execute the AWS AmazonMQ `update_broker` operation.
# Usage: update_broker <region> <BrokerId> <AuthenticationStrategy> <AutoMinorVersionUpgrade> <Configuration> <EngineVersion> <HostInstanceType> <LdapServerMetadata> <Logs> <MaintenanceWindowStartTime> <SecurityGroups> <DataReplicationMode>
update_broker() {
    aws mq update-broker \
        --broker-id "$BROKERID" \
        --authentication-strategy "$AUTHENTICATIONSTRATEGY" \
        --auto-minor-version-upgrade "$AUTOMINORVERSIONUPGRADE" \
        --configuration "$CONFIGURATION" \
        --engine-version "$ENGINEVERSION" \
        --host-instance-type "$HOSTINSTANCETYPE" \
        --ldap-server-metadata "$LDAPSERVERMETADATA" \
        --logs "$LOGS" \
        --maintenance-window-start-time "$MAINTENANCEWINDOWSTARTTIME" \
        --security-groups "$SECURITYGROUPS" \
        --data-replication-mode "$DATAREPLICATIONMODE"
}


# update_configuration: Execute the AWS AmazonMQ `update_configuration` operation.
# Usage: update_configuration <region> <Data> <ConfigurationId> <Description>
update_configuration() {
    aws mq update-configuration \
        --configuration-id "$CONFIGURATIONID" \
        --data "$DATA" \
        --description "$DESCRIPTION"
}


# rabbimq_broker_initialize_connection: Connect to a new RabbitMQ broker which authentication strategy is SIMPLE.

            broker_hostname: The hostname of the broker. For example, b-a9565a64-da39-4afc-9239-c43a9376b5ba.mq.us-east-1.on.aws, b-9560b8e1-3d33-4d91-9488-a3dc4a61dfe7.mq.us-east-1.amazonaws.com
            username: The username of user
            password: The password of user
            
# Usage: rabbimq_broker_initialize_connection <broker_hostname> <username> <password>
rabbimq_broker_initialize_connection() {
    aws mq create-broker-connection \
        --broker-hostname "$BROKER_HOSTNAME" \
        --username "$USERNAME" \
        --password "$PASSWORD"
}


# rabbimq_broker_initialize_connection_with_oauth: Connect to a new RabbitMQ broker using OAuth. It only applies to RabbitMQ broker which authentication strategy is config_managed.

            broker_hostname: The hostname of the broker. For example, b-a9565a64-da39-4afc-9239-c43a9376b5ba.mq.us-east-1.on.aws, b-9560b8e1-3d33-4d91-9488-a3dc4a61dfe7.mq.us-east-1.amazonaws.com
            oauth_token: A valid access token
            
# Usage: rabbimq_broker_initialize_connection_with_oauth <broker_hostname> <oauth_token>
rabbimq_broker_initialize_connection_with_oauth() {
    aws mq create-broker-connection \
        --broker-hostname "$BROKER_HOSTNAME" \
        --oauth-token "$OAUTH_TOKEN"
}


# rabbitmq_broker_list_queues: List all the queues in the broker.
# Usage: rabbitmq_broker_list_queues
rabbitmq_broker_list_queues() {
    aws mq list-queues \
}


# rabbitmq_broker_list_vhosts: List all the virtual hosts (vhosts) in the broker.
# Usage: rabbitmq_broker_list_vhosts
rabbitmq_broker_list_vhosts() {
    aws mq list-vhosts \
}


# rabbitmq_broker_list_connections: List all connections on the RabbitMQ broker.
# Usage: rabbitmq_broker_list_connections
rabbitmq_broker_list_connections() {
    aws mq list-broker-connections \
}


