#!/usr/bin/env bash
# Auto-generated AWS CLI functions for synthetic-data-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# get_data_gen_instructions: Get instructions for generating synthetic data based on a business description.

    This tool analyzes a business description and provides detailed instructions
    for generating synthetic data in JSON Lines format.

    Parameters:
        business_description: A description of the business use case

    Returns:
        A dictionary containing detailed instructions for generating synthetic data
    
# Usage: get_data_gen_instructions <business_description>
get_data_gen_instructions() {
    aws bedrock-runtime invoke-model \
        --model-id "$ANTHROPIC.CLAUDE-V2" \
        --body "$BUSINESS_DESCRIPTION" \
        --content-type "$APPLICATION/JSON"
}


