"""Auto-generated boto3 functions for aws-dynamodb-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def source_db_analyzer(source_db_type: str, output_dir: str, database_name: str | None = None, execution_mode: str | None = None, queries_file_path: str | None = None, query_result_file_path: str | None = None, pattern_analysis_days: str | None = None, max_query_results: str | None = None, aws_cluster_arn: str | None = None, aws_secret_arn: str | None = None, aws_region: str | None = None, hostname: str | None = None, port: str | None = None, **kwargs) -> dict:
    """Analyzes source database to extract schema and access patterns for DynamoDB modeling.

    WHEN TO USE: Call this tool when the user selects "Existing Database Analysis" option
    after invoking the `dynamodb_data_modeling` tool. This extracts schema and query patterns
    from an existing relational database to accelerate DynamoDB data model design.

    IMPORTANT: Always ask the user which execution mode they prefer before calling this tool.

    Execution Modes:
    - self_service: Generates SQL queries for user to run manually, then parses their results.
    - managed (MySQL only): Database connection via RDS Data API or hostname.

    Supported Databases: MySQL, PostgreSQL, SQL Server

    Output: Generates analysis files (schema structure, access patterns, relationships) in
    Markdown format. These files feed into the DynamoDB data modeling workflow to inform
    table design, GSI selection, and access pattern mapping.

    Returns: Analysis summary with file locations and next steps.
    """
    client = boto3.client('rds')
    params = {}
    if aws_cluster_arn is not None:
        params['ClusterArn'] = aws_cluster_arn
    if aws_secret_arn is not None:
        params['SecretArn'] = aws_secret_arn
    if database_name is not None:
        params['Database'] = database_name
    if queries_file_path is not None:
        params['SqlStatements'] = queries_file_path
    if {'MaxRows': 'max_query_results'} is not None:
        params['ResultSetOptions'] = {'MaxRows': 'max_query_results'}
    params.update(kwargs)
    return client.execute_statement(**params)



