#!/usr/bin/env bash
# Auto-generated AWS CLI functions for document-loader-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# read_document: Extract content from various document formats (PDF, Word, Excel, PowerPoint).
# Usage: read_document <file_path> <file_type> <timeout_seconds>
read_document() {
    aws textract detect-document-text \
        --document "$FILE_PATH" \
        --max-results "$TIMEOUT_SECONDS"
}


# read_image: Load an image file and return it to the LLM for viewing and analysis.
# Usage: read_image <file_path> <timeout_seconds>
read_image() {
    aws s3 cp \
        --source "$FILE_PATH" \
        --timeout "$TIMEOUT_SECONDS"
}


