#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-documentdb-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# disconnect: Close a connection to DocumentDB.

    This tool closes a previously established connection to DocumentDB.

    Returns:
        Dict[str, Any]: Confirmation of successful disconnection
    
# Usage: disconnect <connection_id>
disconnect() {
    aws docdb close-connection \
        --connection-id "$CONNECTION_ID"
}


# find: Run a query against a DocumentDB collection.

    This tool queries documents from a specified collection based on a filter.

    Returns:
        List[Dict[str, Any]]: List of matching documents
    
# Usage: find <connection_id> <database> <collection> <query> <projection> <limit>
find() {
    aws docdb find-documents \
        --connection-id "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --filter "$QUERY" \
        --projection "$PROJECTION" \
        --max-results "$LIMIT"
}


# aggregate: Run an aggregation pipeline against a DocumentDB collection.

    This tool executes a DocumentDB aggregation pipeline on a specified collection.

    Returns:
        List[Dict[str, Any]]: List of aggregation results
    
# Usage: aggregate <connection_id> <database> <collection> <pipeline> <limit>
aggregate() {
    aws docdb aggregate \
        --connection-id "$CONNECTION_ID" \
        --database "$DATABASE" \
        --collection "$COLLECTION" \
        --pipeline "$PIPELINE" \
        --limit "$LIMIT"
}


# insert: Insert one or more documents into a DocumentDB collection.

    This tool inserts new documents into a specified collection.

    Returns:
        Dict[str, Any]: Insert operation results including document IDs
    
# Usage: insert <connection_id> <database> <collection> <documents>
insert() {
    aws docdb insert-documents \
        --connection-id "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --documents "$DOCUMENTS"
}


# update: Update documents in a DocumentDB collection.

    This tool updates existing documents that match a specified filter.

    Returns:
        Dict[str, Any]: Update operation results
    
# Usage: update <connection_id> <database> <collection> <filter> <update> <upsert> <many>
update() {
    aws docdb update-documents \
        --connection-id "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --filter "$FILTER" \
        --update "$UPDATE" \
        --upsert "$UPSERT" \
        --many "$MANY"
}


# delete: Delete documents from a DocumentDB collection.

    This tool deletes documents that match a specified filter.

    Returns:
        Dict[str, Any]: Delete operation results
    
# Usage: delete <connection_id> <database> <collection> <filter> <many>
delete() {
    aws docdb delete-documents \
        --connection-id "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --filter "$FILTER" \
        --many "$MANY"
}


# createCollection: Create a new collection in a DocumentDB database.

    This tool creates a new collection in the specified database.

    Returns:
        Dict[str, Any]: Status of collection creation
    
# Usage: createCollection <connection_id> <database> <collection>
createCollection() {
    aws docdb create-collection \
        --cluster-identifier "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION"
}


# dropCollection: Drop a collection from a DocumentDB database.

    This tool completely removes a collection and all its documents from the specified database.
    This operation cannot be undone, so use it with caution.

    Returns:
        Dict[str, Any]: Status of the drop operation
    
# Usage: dropCollection <connection_id> <database> <collection>
dropCollection() {
    aws docdb delete-collection \
        --cluster-identifier "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION"
}


# countDocuments: Count documents in a DocumentDB collection.

    This tool counts the number of documents in a collection that match the provided filter.
    If no filter is provided, it counts all documents.

    Returns:
        Dict[str, Any]: Count result
    
# Usage: countDocuments <connection_id> <database> <collection> <filter>
countDocuments() {
    aws docdb count-documents \
        --connection-id "$CONNECTION_ID" \
        --database "$DATABASE" \
        --collection "$COLLECTION" \
        --filter "$FILTER"
}


# analyzeSchema: Analyze the schema of a collection by sampling documents.

    This tool samples documents from a collection and provides information about
    the document structure and field coverage across the sampled documents.

    Returns:
        Dict[str, Any]: Schema analysis results including field coverage
    
# Usage: analyzeSchema <connection_id> <database> <collection> <sample_size>
analyzeSchema() {
    aws docdb describe-db-cluster-snapshot-attributes \
        --db-cluster-snapshot-identifier "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --max-records "$SAMPLE_SIZE"
}


# explainOperation: Get an explanation of how an operation will be executed.

    This tool returns the execution plan for a query or aggregation operation,
    helping you understand how DocumentDB will process your operations.

    Returns:
        Dict[str, Any]: Operation explanation
    
# Usage: explainOperation <connection_id> <database> <collection> <operation_type> <query> <pipeline> <verbosity>
explainOperation() {
    aws docdb explain-operation \
        --connection-id "$CONNECTION_ID" \
        --database-name "$DATABASE" \
        --collection-name "$COLLECTION" \
        --operation-type "$OPERATION_TYPE" \
        --query "$QUERY" \
        --pipeline "$PIPELINE" \
        --verbosity "$VERBOSITY"
}


