#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-aurora-postgresql-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# run_query: Run a SQL query against PostgreSQL
# Usage: run_query <sql> <connection_method> <cluster_identifier> <db_endpoint> <database> <query_parameters>
run_query() {
    aws rds-data execute-statement \
        --cluster-arn "$CLUSTER_IDENTIFIER" \
        --database "$DATABASE" \
        --sql "$SQL" \
        --parameters "$QUERY_PARAMETERS"
}


# is_database_connected: Check if a connection has been established
# Usage: is_database_connected <cluster_identifier> <db_endpoint> <database>
is_database_connected() {
    aws rds describe-db-clusters \
        --db-cluster-identifier "$CLUSTER_IDENTIFIER"
}


# create_cluster: Create an Aurora Postgres cluster
# Usage: create_cluster <region> <cluster_identifier> <database> <engine_version>
create_cluster() {
    aws rds create-db-cluster \
        --cluster-identifier "$CLUSTER_IDENTIFIER" \
        --engine "$AURORA-POSTGRESQL" \
        --engine-version "$ENGINE_VERSION" \
        --database-name "$DATABASE" \
        --region "$REGION"
}


# get_job_status: get background job status
# Usage: get_job_status <job_id>
get_job_status() {
    aws rds describe-db-cluster-backtrack \
        --db-cluster-backtrack-identifier "$JOB_ID"
}


