#!/usr/bin/env bash
# Auto-generated AWS CLI functions for aws-cloudtrail-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# lookup_events: Look up CloudTrail events based on various criteria.

        This tool searches CloudTrail events using the LookupEvents API, which provides access to the
        last 90 days of management events. You can filter by time range and search for specific
        attribute values.

        Usage: Use this tool to find CloudTrail events by various attributes like username, event name,
        resource name, etc. This is useful for security investigations, troubleshooting, and audit trails.

        IMPORTANT PAGINATION REQUIREMENTS:
        - AWS CloudTrail requires pagination tokens to be used with exactly the same parameters as the original request
        - When using next_token, you must provide the exact same start_time, end_time, attribute_key, and attribute_value
        - Use the 'query_params' returned in the response for subsequent paginated requests

        Returns:
        --------
        Dictionary containing:
            - events: List of CloudTrail events matching the criteria with exact CloudTrail schema
            - next_token: Token for pagination if more results available
            - query_params: Parameters used for the query (includes pagination parameters when next_token is present)
        
# Usage: lookup_events <start_time> <end_time> <attribute_key> <attribute_value> <max_results> <next_token> <region>
lookup_events() {
    aws cloudtrail lookup-events \
        --start-time "$START_TIME" \
        --end-time "$END_TIME" \
        --attribute-key "$ATTRIBUTE_KEY" \
        --attribute-value "$ATTRIBUTE_VALUE" \
        --max-results "$MAX_RESULTS" \
        --next-token "$NEXT_TOKEN"
}


# get_query_status: Get the status of a CloudTrail Lake query.

        This tool checks the status of a previously started CloudTrail Lake query. Use this
        when you need to check if a long-running query has completed or if you want to get
        details about query execution.

        Usage: Use this tool to monitor the progress of CloudTrail Lake queries, especially
        long-running ones that may take time to complete.

        Returns:
        --------
        QueryStatus containing:
            - query_id: The query identifier
            - query_status: Current status (QUEUED, RUNNING, FINISHED, FAILED, CANCELLED, TIMED_OUT)
            - query_statistics: Performance and execution statistics
            - error_message: Error details if the query failed
        
# Usage: get_query_status <query_id> <region>
get_query_status() {
    aws cloudtrail get-query-results \
        --query-id "$QUERY_ID" \
        --region "$REGION"
}


# get_query_results: Get the results of a completed CloudTrail Lake query with pagination support.

        This tool retrieves the results of a previously executed CloudTrail Lake query. It supports
        pagination for large result sets, allowing you to fetch results in chunks.

        Usage: Use this tool to get the results of a query that has completed (status = 'FINISHED').
        For large result sets, use the next_token to fetch subsequent pages of results.

        Pagination workflow:
        1. Call get_query_results with just the query_id to get the first page
        2. If next_token is returned, call again with the same query_id and the next_token
        3. Repeat until next_token is null/empty

        Returns:
        --------
        QueryResult containing:
            - query_id: The query identifier
            - query_status: Current status of the query
            - query_result_rows: Results for this page
            - next_token: Token for next page (null if no more pages)
            - query_statistics: Performance statistics for the query
        
# Usage: get_query_results <query_id> <max_results> <next_token> <region>
get_query_results() {
    aws cloudtrail get-query-results \
        --query-id "$QUERY_ID" \
        --max-results "$MAX_RESULTS" \
        --next-token "$NEXT_TOKEN"
}


# list_event_data_stores: List available CloudTrail Lake Event Data Stores with their capabilities and event selectors.

        Event Data Stores are the storage and query engines for CloudTrail Lake. This tool helps you
        understand which Event Data Stores are available and their configurations.

        Usage: Use this tool to understand which Event Data Stores are available and their
        configurations. This information is needed when executing CloudTrail Lake queries.

        Returns:
        --------
        List of available Event Data Stores with their configurations
        
# Usage: list_event_data_stores <include_details> <region>
list_event_data_stores() {
    aws cloudtrail list-event-data-stores \
        --include-details "$INCLUDE_DETAILS" \
        --region "$REGION"
}


