"""Auto-generated boto3 functions for aws-appsync-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def create_api_key(api_id: str, description: str | None = None, expires: str | None = None, **kwargs) -> dict:
    """Creates a unique key that you can distribute to clients who invoke your API.

        This operation creates an API key for the specified GraphQL API. API keys are used
        to authenticate requests when the API uses API_KEY authentication type.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if description is not None:
        params['Description'] = description
    if expires is not None:
        params['Expires'] = expires
    params.update(kwargs)
    return client.create_api_key(**params)



def create_api_cache(api_id: str, ttl: int, api_caching_behavior: str, type: str, transit_encryption_enabled: str | None = None, at_rest_encryption_enabled: str | None = None, health_metrics_config: str | None = None, **kwargs) -> dict:
    """Creates a cache for the GraphQL API.

        This operation creates an API cache for the specified GraphQL API. Caching improves
        performance by storing frequently requested data and reducing the number of requests
        to data sources.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if ttl is not None:
        params['Ttl'] = ttl
    if api_caching_behavior is not None:
        params['ApiCachingBehavior'] = api_caching_behavior
    if type is not None:
        params['Type'] = type
    if transit_encryption_enabled is not None:
        params['TransitEncryptionEnabled'] = transit_encryption_enabled
    if at_rest_encryption_enabled is not None:
        params['AtRestEncryptionEnabled'] = at_rest_encryption_enabled
    if health_metrics_config is not None:
        params['HealthMetricsConfig'] = health_metrics_config
    params.update(kwargs)
    return client.update_api_cache(**params)



def create_datasource(api_id: str, name: str, type: str, description: str | None = None, service_role_arn: str | None = None, dynamodb_config: str | None = None, lambda_config: str | None = None, elasticsearch_config: str | None = None, open_search_service_config: str | None = None, http_config: str | None = None, relational_database_config: str | None = None, event_bridge_config: str | None = None, metrics_config: str | None = None, **kwargs) -> dict:
    """Creates a DataSource object for a GraphQL API.

        This operation creates a data source for the specified GraphQL API. Data sources
        connect your GraphQL API to various backend services like DynamoDB, Lambda,
        HTTP endpoints, and more.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if name is not None:
        params['Name'] = name
    if type is not None:
        params['Type'] = type
    if description is not None:
        params['Description'] = description
    if service_role_arn is not None:
        params['ServiceRoleArn'] = service_role_arn
    if dynamodb_config is not None:
        params['DynamodbConfig'] = dynamodb_config
    if lambda_config is not None:
        params['LambdaConfig'] = lambda_config
    if elasticsearch_config is not None:
        params['ElasticsearchConfig'] = elasticsearch_config
    if open_search_service_config is not None:
        params['OpenSearchServiceConfig'] = open_search_service_config
    if http_config is not None:
        params['HttpConfig'] = http_config
    if relational_database_config is not None:
        params['RelationalDatabaseConfig'] = relational_database_config
    if event_bridge_config is not None:
        params['EventBridgeConfig'] = event_bridge_config
    if metrics_config is not None:
        params['MetricsConfig'] = metrics_config
    params.update(kwargs)
    return client.create_data_source(**params)



def create_function(api_id: str, name: str, data_source_name: str, description: str | None = None, request_mapping_template: str | None = None, response_mapping_template: str | None = None, function_version: str | None = None, sync_config: str | None = None, max_batch_size: str | None = None, runtime: str | None = None, code: str | None = None, **kwargs) -> dict:
    """Creates a Function object for a GraphQL API.

        This operation creates a function for the specified GraphQL API. Functions
        are reusable pieces of resolver logic that can be attached to multiple fields
        in your GraphQL schema.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if name is not None:
        params['Name'] = name
    if data_source_name is not None:
        params['DataSourceName'] = data_source_name
    if description is not None:
        params['Description'] = description
    if request_mapping_template is not None:
        params['RequestMappingTemplate'] = request_mapping_template
    if response_mapping_template is not None:
        params['ResponseMappingTemplate'] = response_mapping_template
    if function_version is not None:
        params['FunctionVersion'] = function_version
    if sync_config is not None:
        params['SyncConfig'] = sync_config
    if max_batch_size is not None:
        params['MaxBatchSize'] = max_batch_size
    if runtime is not None:
        params['Runtime'] = runtime
    if code is not None:
        params['Code'] = code
    params.update(kwargs)
    return client.create_function(**params)



def create_channel_namespace(api_id: str, name: str, subscribe_auth_modes: str | None = None, publish_auth_modes: str | None = None, code_handlers: str | None = None, handler_configs: str | None = None, tags: str | None = None, **kwargs) -> dict:
    """Creates a ChannelNamespace for an Api.

        This operation creates a channel namespace for the specified GraphQL API.
        Channel namespaces provide a way to organize and manage real-time subscriptions
        in AppSync APIs, enabling event-driven architectures and real-time data updates.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if name is not None:
        params['Name'] = name
    if subscribe_auth_modes is not None:
        params['SubscribeAuthMode'] = subscribe_auth_modes
    if publish_auth_modes is not None:
        params['PublishAuthMode'] = publish_auth_modes
    if code_handlers is not None:
        params['CodeHandlers'] = code_handlers
    if handler_configs is not None:
        params['HandlerConfigs'] = handler_configs
    if tags is not None:
        params['Tags'] = tags
    params.update(kwargs)
    return client.create_channel_namespace(**params)



def create_domain_name(domain_name: str, certificate_arn: str, description: str | None = None, tags: str | None = None, **kwargs) -> dict:
    """Creates a custom domain name for use with AppSync APIs.

        This operation creates a custom domain name that can be associated with
        AppSync APIs, allowing you to use your own domain instead of the default
        AppSync domain. Requires an SSL certificate from AWS Certificate Manager.
        """
    client = boto3.client('appsync')
    params = {}
    if domain_name is not None:
        params['DomainName'] = domain_name
    if certificate_arn is not None:
        params['CertificateArn'] = certificate_arn
    if description is not None:
        params['Description'] = description
    if tags is not None:
        params['Tags'] = tags
    params.update(kwargs)
    return client.create_domain_name(**params)



def create_resolver(api_id: str, type_name: str, field_name: str, data_source_name: str | None = None, request_mapping_template: str | None = None, response_mapping_template: str | None = None, kind: str | None = None, pipeline_config: str | None = None, sync_config: str | None = None, caching_config: str | None = None, max_batch_size: str | None = None, runtime: str | None = None, code: str | None = None, metrics_config: str | None = None, **kwargs) -> dict:
    """Creates a resolver for a GraphQL field in an AppSync API.

        A resolver is the bridge between your GraphQL schema and your data sources.
        It defines how to fetch or modify data for a specific field in your schema.
        Resolvers can be unit resolvers (attached to a single data source) or
        pipeline resolvers (composed of multiple functions).
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if type_name is not None:
        params['TypeName'] = type_name
    if field_name is not None:
        params['FieldName'] = field_name
    if data_source_name is not None:
        params['DataSourceName'] = data_source_name
    if request_mapping_template is not None:
        params['RequestMappingTemplate'] = request_mapping_template
    if response_mapping_template is not None:
        params['ResponseMappingTemplate'] = response_mapping_template
    if kind is not None:
        params['Kind'] = kind
    if pipeline_config is not None:
        params['PipelineConfig'] = pipeline_config
    if sync_config is not None:
        params['SyncConfig'] = sync_config
    if caching_config is not None:
        params['CachingConfig'] = caching_config
    if max_batch_size is not None:
        params['MaxBatchSize'] = max_batch_size
    if runtime is not None:
        params['Runtime'] = runtime
    if code is not None:
        params['Code'] = code
    if metrics_config is not None:
        params['MetricsConfig'] = metrics_config
    params.update(kwargs)
    return client.create_resolver(**params)



def create_schema(api_id: str, definition: str, **kwargs) -> dict:
    """Creates a GraphQL schema for an AppSync API and polls until completion.

        This tool starts the schema creation process and automatically polls for the status
        until the operation completes (either SUCCESS or FAILED). The schema defines the
        structure of your GraphQL API, including types, queries, mutations, and subscriptions.
        """
    client = boto3.client('appsync')
    params = {}
    if api_id is not None:
        params['ApiId'] = api_id
    if definition is not None:
        params['Definition'] = definition
    params.update(kwargs)
    return client.update_graphql_api(**params)



