#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-nova-canvas-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# generate_image: Generate an image using Amazon Nova Canvas with text prompt.

    This tool uses Amazon Nova Canvas to generate images based on a text prompt.
    The generated image will be saved to a file and the path will be returned.

    IMPORTANT FOR ASSISTANT: Always send the current workspace directory when calling this tool!
    The workspace_dir parameter should be set to the directory where the user is currently working
    so that images are saved to a location accessible to the user.

    ## Prompt Best Practices

    An effective prompt often includes short descriptions of:
    1. The subject
    2. The environment
    3. (optional) The position or pose of the subject
    4. (optional) Lighting description
    5. (optional) Camera position/framing
    6. (optional) The visual style or medium ("photo", "illustration", "painting", etc.)

    Do not use negation words like "no", "not", "without" in your prompt. Instead, use the
    negative_prompt parameter to specify what you don't want in the image.

    You should always include "people, anatomy, hands, low quality, low resolution, low detail" in your negative_prompt

    ## Example Prompts

    - "realistic editorial photo of female teacher standing at a blackboard with a warm smile"
    - "whimsical and ethereal soft-shaded story illustration: A woman in a large hat stands at the ship's railing looking out across the ocean"
    - "drone view of a dark river winding through a stark Iceland landscape, cinematic quality"

    Returns:
        McpImageGenerationResponse: A response containing the generated image paths.
    
# Usage: generate_image <prompt> <negative_prompt> <filename> <width> <height> <quality> <cfg_scale> <seed> <number_of_images> <workspace_dir>
generate_image() {
    aws bedrock-runtime invoke-model \
        --model-id "$STABILITY.STABLE-DIFFUSION-XL-V1" \
        --body "$PROMPT" \
        --negative-prompt "$NEGATIVE_PROMPT" \
        --width "$WIDTH" \
        --height "$HEIGHT" \
        --cfg-scale "$CFG_SCALE" \
        --seed "$SEED" \
        --samples "$NUMBER_OF_IMAGES"
}


# generate_image_with_colors: Generate an image using Amazon Nova Canvas with color guidance.

    This tool uses Amazon Nova Canvas to generate images based on a text prompt and color palette.
    The generated image will be saved to a file and the path will be returned.

    IMPORTANT FOR Assistant: Always send the current workspace directory when calling this tool!
    The workspace_dir parameter should be set to the directory where the user is currently working
    so that images are saved to a location accessible to the user.

    ## Prompt Best Practices

    An effective prompt often includes short descriptions of:
    1. The subject
    2. The environment
    3. (optional) The position or pose of the subject
    4. (optional) Lighting description
    5. (optional) Camera position/framing
    6. (optional) The visual style or medium ("photo", "illustration", "painting", etc.)

    Do not use negation words like "no", "not", "without" in your prompt. Instead, use the
    negative_prompt parameter to specify what you don't want in the image.

    ## Example Colors

    - ["#FF5733", "#33FF57", "#3357FF"] - A vibrant color scheme with red, green, and blue
    - ["#000000", "#FFFFFF"] - A high contrast black and white scheme
    - ["#FFD700", "#B87333"] - A gold and bronze color scheme

    Returns:
        McpImageGenerationResponse: A response containing the generated image paths.
    
# Usage: generate_image_with_colors <prompt> <colors> <negative_prompt> <filename> <width> <height> <quality> <cfg_scale> <seed> <number_of_images> <workspace_dir>
generate_image_with_colors() {
    aws bedrock-runtime invoke-model \
        --model-id "$AMAZON.TITAN-IMAGE-GENERATOR-V1" \
        --body "$JSON_BODY_WITH_PARAMS"
}


