"""Auto-generated boto3 functions for healthlake-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def list_datastores(filter: str | None = None, **kwargs) -> dict:
    """List all HealthLake datastores in the account"""
    client = boto3.client('healthlake')
    params = {}
    if filter is not None:
        params['Filter'] = filter
    params.update(kwargs)
    return client.list_fhir_datastores(**params)



def get_datastore_details(datastore_id: str, **kwargs) -> dict:
    """Get detailed information about a specific HealthLake datastore"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    params.update(kwargs)
    return client.describe_fhir_datastore(**params)



def create_fhir_resource(datastore_id: str, resource_type: str, resource_data: dict, **kwargs) -> dict:
    """Create a new FHIR resource in HealthLake"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if resource_type is not None:
        params['ResourceType'] = resource_type
    if resource_data is not None:
        params['ResourceData'] = resource_data
    params.update(kwargs)
    return client.create_resource(**params)



def read_fhir_resource(datastore_id: str, resource_type: str, resource_id: str, **kwargs) -> dict:
    """Get a specific FHIR resource by ID"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if resource_type is not None:
        params['ResourceType'] = resource_type
    if resource_id is not None:
        params['ResourceId'] = resource_id
    params.update(kwargs)
    return client.read_resource(**params)



def update_fhir_resource(datastore_id: str, resource_type: str, resource_id: str, resource_data: dict, **kwargs) -> dict:
    """Update an existing FHIR resource in HealthLake"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if resource_type is not None:
        params['ResourceType'] = resource_type
    if resource_id is not None:
        params['ResourceId'] = resource_id
    if resource_data is not None:
        params['ResourceJson'] = resource_data
    params.update(kwargs)
    return client.update_resource(**params)



def delete_fhir_resource(datastore_id: str, resource_type: str, resource_id: str, **kwargs) -> dict:
    """Delete a FHIR resource from HealthLake"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if resource_type is not None:
        params['ResourceType'] = resource_type
    if resource_id is not None:
        params['ResourceId'] = resource_id
    params.update(kwargs)
    return client.delete_resource(**params)



def patient_everything(datastore_id: str, patient_id: str, start: str | None = None, end: str | None = None, count: int | None = None, next_token: str | None = None, **kwargs) -> dict:
    """Retrieve all resources related to a specific patient using the FHIR $patient-everything operation"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if {'S3Configuration': {'S3Uri': 's3://bucket/path'}} is not None:
        params['OutputDataConfig'] = {'S3Configuration': {'S3Uri': 's3://bucket/path'}}
    if start is not None:
        params['StartTime'] = start
    if end is not None:
        params['EndTime'] = end
    if count is not None:
        params['MaxResults'] = count
    if next_token is not None:
        params['NextToken'] = next_token
    params.update(kwargs)
    return client.start_fhir_export_job(**params)



def start_fhir_import_job(datastore_id: str, input_data_config: dict, job_output_data_config: dict, data_access_role_arn: str, job_name: str | None = None, **kwargs) -> dict:
    """Start a FHIR import job to load data into HealthLake"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if input_data_config is not None:
        params['InputDataConfig'] = input_data_config
    if job_output_data_config is not None:
        params['JobOutputDataConfig'] = job_output_data_config
    if data_access_role_arn is not None:
        params['DataAccessRoleArn'] = data_access_role_arn
    if job_name is not None:
        params['JobName'] = job_name
    params.update(kwargs)
    return client.start_fhir_import_job(**params)



def start_fhir_export_job(datastore_id: str, output_data_config: dict, data_access_role_arn: str, job_name: str | None = None, **kwargs) -> dict:
    """Start a FHIR export job to export data from HealthLake"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if output_data_config is not None:
        params['OutputDataConfig'] = output_data_config
    if data_access_role_arn is not None:
        params['DataAccessRoleArn'] = data_access_role_arn
    if job_name is not None:
        params['JobName'] = job_name
    params.update(kwargs)
    return client.start_fhir_export_job(**params)



def list_fhir_jobs(datastore_id: str, job_status: str | None = None, job_type: str | None = None, **kwargs) -> dict:
    """List FHIR import/export jobs"""
    client = boto3.client('healthlake')
    params = {}
    if datastore_id is not None:
        params['DatastoreId'] = datastore_id
    if job_status is not None:
        params['JobStatus'] = job_status
    if job_type is not None:
        params['JobType'] = job_type
    params.update(kwargs)
    return client.list_fhir_jobs(**params)



