"""Auto-generated boto3 functions for amazon-ecs-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def delete_app(service_arn: str, app_name: str, **kwargs) -> dict:
    """Deletes a complete Express Mode deployment including service and ECR infrastructure.

This tool performs complete cleanup of an Express Mode deployment:
1. Deletes the Express Gateway Service
2. Deletes the ECR CloudFormation stack (ECR repository + IAM role)

## Parameters:
- Required: service_arn (ARN of Express Gateway Service)
- Required: app_name (Application name used during deployment)

## What Gets Deleted:
- Express Gateway Service and all provisioned infrastructure
  (ALB, target groups, security groups)
- CloudFormation stack for ECR resources, including ECR repo and container images

## Returns:
Dictionary containing:
- service_deletion: Status and details of service deletion
- ecr_deletion: Status and details of ECR stack deletion
- summary: Overall deletion summary with list of deleted resources
- errors: List of any errors encountered

## Usage Examples:
```
# Delete complete deployment
delete_app(
    service_arn="arn:aws:ecs:us-west-2:123456789012:express-service/my-api",
    app_name="my-app"
)
```

Returns on success:
```
{
  "service_deletion": {
    "status": "deleted",
    "service_arn": "arn:aws:ecs:us-west-2:123456789012:express-service/my-api",
    "message": "Express Gateway Service deleted successfully"
  },
  "ecr_deletion": {
    "status": "deleted",
    "stack_name": "my-app-ecr-infrastructure",
    "message": "ECR stack deleted successfully",
    "deleted_resources": [
      "ECR repository: my-app-repo",
      "IAM role: my-app-ecr-push-pull-role"
    ]
  },
  "summary": {
    "status": "success",
    "message": "Successfully deleted Express Mode deployment for my-app",
    "deleted_resources": [
      "Express Gateway Service: arn:aws:ecs:...",
      "ECR repository: my-app-repo",
      "IAM role: my-app-ecr-push-pull-role"
    ]
  },
  "errors": []
}
```

## Important Notes:
- This operation requires WRITE permission (ALLOW_WRITE=true)
- Deletion is irreversible - all container images will be deleted
- Service deletion may take a few minutes as infrastructure is deprovisioned
- If errors occur, partial deletion is possible (check summary for details)"""
    client = boto3.client('ecs')
    params = {}
    if service_arn is not None:
        params['ServiceArn'] = service_arn
    if True is not None:
        params['Force'] = True
    params.update(kwargs)
    return client.delete_service(**params)



def wait_for_service_ready(cluster: str, service_name: str, timeout_seconds: int | None = None, **kwargs) -> dict:
    """Waits for ECS tasks in a service to reach RUNNING status.

This tool polls the service every 10 seconds to check if tasks are running.
It will wait up to the specified timeout before returning a timeout status.

## Parameters:
- Required: cluster (ECS cluster name)
- Required: service_name (ECS service name)
- Optional: timeout_seconds (Max wait time, defaults to 300 seconds)

## Returns:
Dictionary containing:
- status: "success" if tasks are running, "timeout" if timeout reached,
  "failed" if an error occurred
- message: Human-readable status message

## Usage Examples:
```
# Wait for service with default 5-minute timeout
wait_for_service_ready(
    cluster="my-cluster",
    service_name="my-service"
)

# Wait for service with custom timeout
wait_for_service_ready(
    cluster="my-cluster",
    service_name="my-service",
    timeout_seconds=600
)
```

Returns on success:
```
{
  "status": "success",
  "message": "Service is ready with 2 running task(s)"
}
```

Returns on timeout:
```
{
  "status": "timeout",
  "message": "Timeout after 300s - service not ready"
}
```"""
    client = boto3.client('ecs')
    params = {}
    if cluster is not None:
        params['ClusterName'] = cluster
    if service_name is not None:
        params['ServiceName'] = service_name
    if {'Delay': 15, 'MaxAttempts': 20} is not None:
        params['WaiterConfig'] = {'Delay': 15, 'MaxAttempts': 20}
    params.update(kwargs)
    return client.wait_for_service_stable(**params)



def ecs_resource_management(api_operation: str, api_params: dict | None = None, **kwargs) -> dict:
    """Execute ECS API operations directly.

This tool allows direct execution of ECS API operations using boto3.

Supported operations:
- CreateCapacityProvider (requires WRITE permission)
- CreateCluster (requires WRITE permission)
- CreateExpressGatewayService (requires WRITE permission)
- CreateService (requires WRITE permission)
- CreateTaskSet (requires WRITE permission)
- DeleteAccountSetting (requires WRITE permission)
- DeleteAttributes (requires WRITE permission)
- DeleteCapacityProvider (requires WRITE permission)
- DeleteCluster (requires WRITE permission)
- DeleteExpressGatewayService (requires WRITE permission)
- DeleteService (requires WRITE permission)
- DeleteTaskDefinitions (requires WRITE permission)
- DeleteTaskSet (requires WRITE permission)
- DeregisterContainerInstance (requires WRITE permission)
- DeregisterTaskDefinition (requires WRITE permission)
- DescribeCapacityProviders (read-only)
- DescribeClusters (read-only)
- DescribeContainerInstances (read-only)
- DescribeExpressGatewayService (read-only)
- DescribeServiceDeployments (read-only)
- DescribeServiceRevisions (read-only)
- DescribeServices (read-only)
- DescribeTaskDefinition (read-only)
- DescribeTasks (read-only)
- DescribeTaskSets (read-only)
- DiscoverPollEndpoint (requires WRITE permission)
- ExecuteCommand (requires WRITE permission)
- GetTaskProtection (requires WRITE permission)
- ListAccountSettings (read-only)
- ListAttributes (read-only)
- ListClusters (read-only)
- ListContainerInstances (read-only)
- ListExpressGatewayServices (read-only)
- ListServiceDeployments (read-only)
- ListServices (read-only)
- ListServicesByNamespace (read-only)
- ListTagsForResource (read-only)
- ListTaskDefinitionFamilies (read-only)
- ListTaskDefinitions (read-only)
- ListTasks (read-only)
- PutAccountSetting (requires WRITE permission)
- PutAccountSettingDefault (requires WRITE permission)
- PutAttributes (requires WRITE permission)
- PutClusterCapacityProviders (requires WRITE permission)
- RegisterContainerInstance (requires WRITE permission)
- RegisterTaskDefinition (requires WRITE permission)
- RunTask (requires WRITE permission)
- StartTask (requires WRITE permission)
- StopServiceDeployment (requires WRITE permission)
- StopTask (requires WRITE permission)
- SubmitAttachmentStateChanges (requires WRITE permission)
- SubmitContainerStateChange (requires WRITE permission)
- SubmitTaskStateChange (requires WRITE permission)
- TagResource (requires WRITE permission)
- UntagResource (requires WRITE permission)
- UpdateCapacityProvider (requires WRITE permission)
- UpdateCluster (requires WRITE permission)
- UpdateClusterSettings (requires WRITE permission)
- UpdateContainerAgent (requires WRITE permission)
- UpdateContainerInstancesState (requires WRITE permission)
- UpdateExpressGatewayService (requires WRITE permission)
- UpdateService (requires WRITE permission)
- UpdateServicePrimaryTaskSet (requires WRITE permission)
- UpdateTaskProtection (requires WRITE permission)
- UpdateTaskSet (requires WRITE permission)

Parameters:
    api_operation: The ECS API operation to execute (CamelCase)
    api_params: Dictionary of parameters to pass to the API operation

Returns:
    Dictionary containing the API response"""
    client = boto3.client('ecs')
    params = {}
    if api_operation is not None:
        params['ApiOperation'] = api_operation
    if api_params is not None:
        params['Params'] = api_params
    params.update(kwargs)
    return client.api_operation(**params)



