"""Auto-generated boto3 functions for amazon-sns-sqs-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def add_sns_permission(ActionName: list, AWSAccountId: list, Label: str, TopicArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `add_permission` operation."""
    client = boto3.client('sns')
    params = {}
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if Label is not None:
        params['Label'] = Label
    if AWSAccountId is not None:
        params['AWSAccountId'] = AWSAccountId
    if ActionName is not None:
        params['ActionName'] = ActionName
    params.update(kwargs)
    return client.add_permission(**params)



def check_if_phone_number_is_opted_out(phoneNumber: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `check_if_phone_number_is_opted_out` operation."""
    client = boto3.client('sns')
    params = {}
    if phoneNumber is not None:
        params['PhoneNumber'] = phoneNumber
    if region is not None:
        params['region'] = region
    params.update(kwargs)
    return client.check_phone_number_opt_out(**params)



def confirm_subscription(Token: str, TopicArn: str, AuthenticateOnUnsubscribe: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `confirm_subscription` operation."""
    client = boto3.client('sns')
    params = {}
    if Token is not None:
        params['Token'] = Token
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if AuthenticateOnUnsubscribe is not None:
        params['AuthenticateOnUnsubscribe'] = AuthenticateOnUnsubscribe
    params.update(kwargs)
    return client.confirm_subscription(**params)



def get_data_protection_policy(ResourceArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `get_data_protection_policy` operation."""
    client = boto3.client('sns')
    params = {}
    if ResourceArn is not None:
        params['ResourceArn'] = ResourceArn
    params.update(kwargs)
    return client.get_data_protection_policy(**params)



def get_endpoint_attributes(EndpointArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `get_endpoint_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if EndpointArn is not None:
        params['EndpointArn'] = EndpointArn
    params.update(kwargs)
    return client.get_endpoint_attributes(**params)



def get_platform_application_attributes(PlatformApplicationArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `get_platform_application_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if PlatformApplicationArn is not None:
        params['PlatformApplicationArn'] = PlatformApplicationArn
    params.update(kwargs)
    return client.get_platform_application_attributes(**params)



def get_subscription_attributes(SubscriptionArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `get_subscription_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if SubscriptionArn is not None:
        params['SubscriptionArn'] = SubscriptionArn
    params.update(kwargs)
    return client.get_subscription_attributes(**params)



def get_topic_attributes(TopicArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `get_topic_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    params.update(kwargs)
    return client.get_topic_attributes(**params)



def list_endpoints_by_platform_application(PlatformApplicationArn: str, NextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_endpoints_by_platform_application` operation."""
    client = boto3.client('sns')
    params = {}
    if PlatformApplicationArn is not None:
        params['PlatformApplicationArn'] = PlatformApplicationArn
    if NextToken is not None:
        params['NextToken'] = NextToken
    params.update(kwargs)
    return client.list_endpoints_by_platform_application(**params)



def list_origination_numbers(NextToken: str | None = None, MaxResults: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_origination_numbers` operation."""
    client = boto3.client('sns')
    params = {}
    if NextToken is not None:
        params['NextToken'] = NextToken
    if MaxResults is not None:
        params['MaxResults'] = MaxResults
    params.update(kwargs)
    return client.list_origination_numbers(**params)



def list_phone_numbers_opted_out(nextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_phone_numbers_opted_out` operation."""
    client = boto3.client('sns')
    params = {}
    if nextToken is not None:
        params['NextToken'] = nextToken
    if region is not None:
        params['PhoneNumberRegion'] = region
    params.update(kwargs)
    return client.list_phone_numbers_opted_out(**params)



def list_platform_applications(NextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_platform_applications` operation."""
    client = boto3.client('sns')
    params = {}
    if NextToken is not None:
        params['NextToken'] = NextToken
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.list_platform_applications(**params)



def list_subscriptions(NextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_subscriptions` operation."""
    client = boto3.client('sns')
    params = {}
    if NextToken is not None:
        params['NextToken'] = NextToken
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.list_subscriptions(**params)



def list_subscriptions_by_topic(TopicArn: str, NextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_subscriptions_by_topic` operation."""
    client = boto3.client('sns')
    params = {}
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if NextToken is not None:
        params['NextToken'] = NextToken
    params.update(kwargs)
    return client.list_subscriptions_by_topic(**params)



def list_tags_for_resource(ResourceArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_tags_for_resource` operation."""
    client = boto3.client('sns')
    params = {}
    if ResourceArn is not None:
        params['ResourceArn'] = ResourceArn
    params.update(kwargs)
    return client.list_tags_for_resource(**params)



def list_topics(NextToken: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `list_topics` operation."""
    client = boto3.client('sns')
    params = {}
    if NextToken is not None:
        params['NextToken'] = NextToken
    params.update(kwargs)
    return client.list_topics(**params)



def opt_in_phone_number(phoneNumber: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `opt_in_phone_number` operation."""
    client = boto3.client('sns')
    params = {}
    if phoneNumber is not None:
        params['PhoneNumber'] = phoneNumber
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.opt_in_phone_number(**params)



def publish(Message: str, TopicArn: str | None = None, TargetArn: str | None = None, PhoneNumber: str | None = None, Subject: str | None = None, MessageStructure: str | None = None, MessageAttributes: str | None = None, MessageDeduplicationId: str | None = None, MessageGroupId: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `publish` operation."""
    client = boto3.client('sns')
    params = {}
    if Message is not None:
        params['Message'] = Message
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if TargetArn is not None:
        params['TargetArn'] = TargetArn
    if PhoneNumber is not None:
        params['PhoneNumber'] = PhoneNumber
    if Subject is not None:
        params['Subject'] = Subject
    if MessageStructure is not None:
        params['MessageStructure'] = MessageStructure
    if MessageAttributes is not None:
        params['MessageAttributes'] = MessageAttributes
    if MessageDeduplicationId is not None:
        params['MessageDeduplicationId'] = MessageDeduplicationId
    if MessageGroupId is not None:
        params['MessageGroupId'] = MessageGroupId
    params.update(kwargs)
    return client.publish(**params)



def publish_batch(PublishBatchRequestEntries: list, TopicArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `publish_batch` operation."""
    client = boto3.client('sns')
    params = {}
    if PublishBatchRequestEntries is not None:
        params['PublishBatchRequestEntries'] = PublishBatchRequestEntries
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    params.update(kwargs)
    return client.publish_batch(**params)



def put_data_protection_policy(DataProtectionPolicy: str, ResourceArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `put_data_protection_policy` operation."""
    client = boto3.client('sns')
    params = {}
    if DataProtectionPolicy is not None:
        params['DataProtectionPolicy'] = DataProtectionPolicy
    if ResourceArn is not None:
        params['ResourceArn'] = ResourceArn
    params.update(kwargs)
    return client.put_data_protection_policy(**params)



def set_subscription_attributes(AttributeName: str, SubscriptionArn: str, AttributeValue: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `set_subscription_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if SubscriptionArn is not None:
        params['SubscriptionArn'] = SubscriptionArn
    if AttributeName is not None:
        params['AttributeName'] = AttributeName
    if AttributeValue is not None:
        params['AttributeValue'] = AttributeValue
    params.update(kwargs)
    return client.set_subscription_attributes(**params)



def set_topic_attributes(AttributeName: str, TopicArn: str, AttributeValue: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `set_topic_attributes` operation."""
    client = boto3.client('sns')
    params = {}
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if AttributeName is not None:
        params['AttributeName'] = AttributeName
    if AttributeValue is not None:
        params['AttributeValue'] = AttributeValue
    params.update(kwargs)
    return client.set_topic_attributes(**params)



def subscribe(Protocol: str, TopicArn: str, Endpoint: str | None = None, Attributes: str | None = None, ReturnSubscriptionArn: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute AWS SNS Subscribe. Ensure that you set correct permission policies if required."""
    client = boto3.client('sns')
    params = {}
    if Protocol is not None:
        params['Protocol'] = Protocol
    if TopicArn is not None:
        params['TopicArn'] = TopicArn
    if Endpoint is not None:
        params['Endpoint'] = Endpoint
    if Attributes is not None:
        params['Attributes'] = Attributes
    if ReturnSubscriptionArn is not None:
        params['ReturnSubscriptionArn'] = ReturnSubscriptionArn
    params.update(kwargs)
    return client.subscribe(**params)



def unsubscribe(SubscriptionArn: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SNS `unsubscribe` operation."""
    client = boto3.client('sns')
    params = {}
    if SubscriptionArn is not None:
        params['SubscriptionArn'] = SubscriptionArn
    params.update(kwargs)
    return client.unsubscribe(**params)



def add_sqs_permission(Actions: list, AWSAccountIds: list, Label: str, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `add_permission` operation."""
    client = boto3.client('sqs')
    params = {}
    if Actions is not None:
        params['Actions'] = Actions
    if AWSAccountIds is not None:
        params['AWSAccountIds'] = AWSAccountIds
    if Label is not None:
        params['Label'] = Label
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    params.update(kwargs)
    return client.add_permission(**params)



def cancel_message_move_task(TaskHandle: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `cancel_message_move_task` operation."""
    client = boto3.client('sqs')
    params = {}
    if TaskHandle is not None:
        params['TaskHandle'] = TaskHandle
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.cancel_message_move_task(**params)



def change_message_visibility(VisibilityTimeout: int, ReceiptHandle: str, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `change_message_visibility` operation."""
    client = boto3.client('sqs')
    params = {}
    if VisibilityTimeout is not None:
        params['VisibilityTimeout'] = VisibilityTimeout
    if ReceiptHandle is not None:
        params['ReceiptHandle'] = ReceiptHandle
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    params.update(kwargs)
    return client.change_message_visibility(**params)



def change_message_visibility_batch(Entries: list, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `change_message_visibility_batch` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if Entries is not None:
        params['Entries'] = Entries
    params.update(kwargs)
    return client.change_message_visibility_batch(**params)



def delete_message(ReceiptHandle: str, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `delete_message` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if ReceiptHandle is not None:
        params['ReceiptHandle'] = ReceiptHandle
    params.update(kwargs)
    return client.delete_message(**params)



def delete_message_batch(Entries: list, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `delete_message_batch` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if Entries is not None:
        params['Entries'] = Entries
    params.update(kwargs)
    return client.delete_message_batch(**params)



def get_queue_attributes(QueueUrl: str, AttributeNames: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `get_queue_attributes` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if AttributeNames is not None:
        params['AttributeNames'] = AttributeNames
    params.update(kwargs)
    return client.get_queue_attributes(**params)



def get_queue_url(QueueName: str, QueueOwnerAWSAccountId: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `get_queue_url` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueName is not None:
        params['QueueName'] = QueueName
    if QueueOwnerAWSAccountId is not None:
        params['QueueOwnerAWSAccountId'] = QueueOwnerAWSAccountId
    params.update(kwargs)
    return client.get_queue_url(**params)



def list_dead_letter_source_queues(QueueUrl: str, NextToken: str | None = None, MaxResults: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `list_dead_letter_source_queues` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if NextToken is not None:
        params['NextToken'] = NextToken
    if MaxResults is not None:
        params['MaxResults'] = MaxResults
    params.update(kwargs)
    return client.list_dead_letter_source_queues(**params)



def list_message_move_tasks(SourceArn: str, MaxResults: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `list_message_move_tasks` operation."""
    client = boto3.client('sqs')
    params = {}
    if SourceArn is not None:
        params['SourceArn'] = SourceArn
    if MaxResults is not None:
        params['MaxResults'] = MaxResults
    params.update(kwargs)
    return client.list_message_move_tasks(**params)



def list_queue_tags(QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `list_queue_tags` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.list_queue_tags(**params)



def list_queues(QueueNamePrefix: str | None = None, NextToken: str | None = None, MaxResults: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `list_queues` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueNamePrefix is not None:
        params['QueueNamePrefix'] = QueueNamePrefix
    if NextToken is not None:
        params['NextToken'] = NextToken
    if MaxResults is not None:
        params['MaxResults'] = MaxResults
    params.update(kwargs)
    return client.list_queues(**params)



def purge_queue(QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `purge_queue` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.purge_queue(**params)



def receive_message(QueueUrl: str, AttributeNames: str | None = None, MessageSystemAttributeNames: str | None = None, MessageAttributeNames: str | None = None, MaxNumberOfMessages: str | None = None, VisibilityTimeout: str | None = None, WaitTimeSeconds: str | None = None, ReceiveRequestAttemptId: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `receive_message` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if AttributeNames is not None:
        params['AttributeNames'] = AttributeNames
    if MessageSystemAttributeNames is not None:
        params['MessageSystemAttributeNames'] = MessageSystemAttributeNames
    if MessageAttributeNames is not None:
        params['MessageAttributeNames'] = MessageAttributeNames
    if MaxNumberOfMessages is not None:
        params['MaxNumberOfMessages'] = MaxNumberOfMessages
    if VisibilityTimeout is not None:
        params['VisibilityTimeout'] = VisibilityTimeout
    if WaitTimeSeconds is not None:
        params['WaitTimeSeconds'] = WaitTimeSeconds
    if ReceiveRequestAttemptId is not None:
        params['ReceiveRequestAttemptId'] = ReceiveRequestAttemptId
    params.update(kwargs)
    return client.receive_message(**params)



def remove_sqs_permission(Label: str, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `remove_permission` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if Label is not None:
        params['Label'] = Label
    params.update(kwargs)
    return client.remove_permission(**params)



def send_message(MessageBody: str, QueueUrl: str, DelaySeconds: str | None = None, MessageAttributes: str | None = None, MessageSystemAttributes: str | None = None, MessageDeduplicationId: str | None = None, MessageGroupId: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `send_message` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if MessageBody is not None:
        params['MessageBody'] = MessageBody
    if DelaySeconds is not None:
        params['DelaySeconds'] = DelaySeconds
    if MessageAttributes is not None:
        params['MessageAttributes'] = MessageAttributes
    if MessageSystemAttributes is not None:
        params['MessageSystemAttributes'] = MessageSystemAttributes
    if MessageDeduplicationId is not None:
        params['MessageDeduplicationId'] = MessageDeduplicationId
    if MessageGroupId is not None:
        params['MessageGroupId'] = MessageGroupId
    params.update(kwargs)
    return client.send_message(**params)



def send_message_batch(Entries: list, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `send_message_batch` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if Entries is not None:
        params['Entries'] = Entries
    params.update(kwargs)
    return client.send_message_batch(**params)



def set_queue_attributes(Attributes: dict, QueueUrl: str, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `set_queue_attributes` operation."""
    client = boto3.client('sqs')
    params = {}
    if QueueUrl is not None:
        params['QueueUrl'] = QueueUrl
    if Attributes is not None:
        params['Attributes'] = Attributes
    params.update(kwargs)
    return client.set_queue_attributes(**params)



def start_message_move_task(SourceArn: str, DestinationArn: str | None = None, MaxNumberOfMessagesPerSecond: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Execute the AWS Amazon SQS `start_message_move_task` operation."""
    client = boto3.client('sqs')
    params = {}
    if SourceArn is not None:
        params['SourceArn'] = SourceArn
    if DestinationArn is not None:
        params['DestinationArn'] = DestinationArn
    if MaxNumberOfMessagesPerSecond is not None:
        params['MaxNumberOfMessagesPerSecond'] = MaxNumberOfMessagesPerSecond
    params.update(kwargs)
    return client.start_message_move_task(**params)



