"""Auto-generated boto3 functions for amazon-neptune-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def get_graph_schema(**kwargs) -> dict:
    """Get the schema for the graph including the vertex and edge labels as well as the
    (vertex)-[edge]->(vertex) combinations.
    """
    client = boto3.client('neptune')
    params = {}
    params.update(kwargs)
    return client.get_graph_schema(**params)



def run_opencypher_query(query: str, parameters: str | None = None, **kwargs) -> dict:
    """Executes the provided openCypher against the graph."""
    client = boto3.client('neptune')
    params = {}
    if query is not None:
        params['Query'] = query
    if parameters is not None:
        params['Parameters'] = parameters
    params.update(kwargs)
    return client.execute_open_cypher_query(**params)



def run_gremlin_query(query: str, **kwargs) -> dict:
    """Executes the provided Tinkerpop Gremlin against the graph."""
    client = boto3.client('neptune')
    params = {}
    if query is not None:
        params['Query'] = query
    params.update(kwargs)
    return client.execute_gremlin_query(**params)



