#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-sns-sqs-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# add_sns_permission: Execute the AWS Amazon SNS `add_permission` operation.
# Usage: add_sns_permission <ActionName> <AWSAccountId> <Label> <TopicArn> <region>
add_sns_permission() {
    aws sns add-permission \
        --topic-arn "$TOPICARN" \
        --label "$LABEL" \
        --aws-account-id "$AWSACCOUNTID" \
        --action-name "$ACTIONNAME"
}


# check_if_phone_number_is_opted_out: Execute the AWS Amazon SNS `check_if_phone_number_is_opted_out` operation.
# Usage: check_if_phone_number_is_opted_out <phoneNumber> <region>
check_if_phone_number_is_opted_out() {
    aws sns check-phone-number-opt-out \
        --phone-number "$PHONENUMBER" \
        --region "$REGION"
}


# confirm_subscription: Execute the AWS Amazon SNS `confirm_subscription` operation.
# Usage: confirm_subscription <Token> <TopicArn> <AuthenticateOnUnsubscribe> <region>
confirm_subscription() {
    aws sns confirm-subscription \
        --token "$TOKEN" \
        --topic-arn "$TOPICARN" \
        --authenticate-on-unsubscribe "$AUTHENTICATEONUNSUBSCRIBE" \
        --region "$REGION"
}


# get_data_protection_policy: Execute the AWS Amazon SNS `get_data_protection_policy` operation.
# Usage: get_data_protection_policy <ResourceArn> <region>
get_data_protection_policy() {
    aws sns get-data-protection-policy \
        --resource-arn "$RESOURCEARN" \
        --region "$REGION"
}


# get_endpoint_attributes: Execute the AWS Amazon SNS `get_endpoint_attributes` operation.
# Usage: get_endpoint_attributes <EndpointArn> <region>
get_endpoint_attributes() {
    aws sns get-endpoint-attributes \
        --endpoint-arn "$ENDPOINTARN" \
        --region "$REGION"
}


# get_platform_application_attributes: Execute the AWS Amazon SNS `get_platform_application_attributes` operation.
# Usage: get_platform_application_attributes <PlatformApplicationArn> <region>
get_platform_application_attributes() {
    aws sns get-platform-application-attributes \
        --platform-application-arn "$PLATFORMAPPLICATIONARN"
}


# get_subscription_attributes: Execute the AWS Amazon SNS `get_subscription_attributes` operation.
# Usage: get_subscription_attributes <SubscriptionArn> <region>
get_subscription_attributes() {
    aws sns get-subscription-attributes \
        --subscription-arn "$SUBSCRIPTIONARN" \
        --region "$REGION"
}


# get_topic_attributes: Execute the AWS Amazon SNS `get_topic_attributes` operation.
# Usage: get_topic_attributes <TopicArn> <region>
get_topic_attributes() {
    aws sns get-topic-attributes \
        --topic-arn "$TOPICARN"
}


# list_endpoints_by_platform_application: Execute the AWS Amazon SNS `list_endpoints_by_platform_application` operation.
# Usage: list_endpoints_by_platform_application <PlatformApplicationArn> <NextToken> <region>
list_endpoints_by_platform_application() {
    aws sns list-endpoints-by-platform-application \
        --platform-application-arn "$PLATFORMAPPLICATIONARN" \
        --next-token "$NEXTTOKEN" \
        --region "$REGION"
}


# list_origination_numbers: Execute the AWS Amazon SNS `list_origination_numbers` operation.
# Usage: list_origination_numbers <NextToken> <MaxResults> <region>
list_origination_numbers() {
    aws sns list-origination-numbers \
        --next-token "$NEXTTOKEN" \
        --max-results "$MAXRESULTS" \
        --region "$REGION"
}


# list_phone_numbers_opted_out: Execute the AWS Amazon SNS `list_phone_numbers_opted_out` operation.
# Usage: list_phone_numbers_opted_out <nextToken> <region>
list_phone_numbers_opted_out() {
    aws sns list-phone-numbers-opted-out \
        --next-token "$NEXTTOKEN" \
        --phone-number-region "$REGION"
}


# list_platform_applications: Execute the AWS Amazon SNS `list_platform_applications` operation.
# Usage: list_platform_applications <NextToken> <region>
list_platform_applications() {
    aws sns list-platform-applications \
        --next-token "$NEXTTOKEN" \
        --region "$REGION"
}


# list_subscriptions: Execute the AWS Amazon SNS `list_subscriptions` operation.
# Usage: list_subscriptions <NextToken> <region>
list_subscriptions() {
    aws sns list-subscriptions \
        --next-token "$NEXTTOKEN" \
        --region "$REGION"
}


# list_subscriptions_by_topic: Execute the AWS Amazon SNS `list_subscriptions_by_topic` operation.
# Usage: list_subscriptions_by_topic <TopicArn> <NextToken> <region>
list_subscriptions_by_topic() {
    aws sns list-subscriptions-by-topic \
        --topic-arn "$TOPICARN" \
        --next-token "$NEXTTOKEN" \
        --region "$REGION"
}


# list_tags_for_resource: Execute the AWS Amazon SNS `list_tags_for_resource` operation.
# Usage: list_tags_for_resource <ResourceArn> <region>
list_tags_for_resource() {
    aws sns list-tags-for-resource \
        --resource-arn "$RESOURCEARN" \
        --region "$REGION"
}


# list_topics: Execute the AWS Amazon SNS `list_topics` operation.
# Usage: list_topics <NextToken> <region>
list_topics() {
    aws sns list-topics \
        --next-token "$NEXTTOKEN" \
        --region "$REGION"
}


# opt_in_phone_number: Execute the AWS Amazon SNS `opt_in_phone_number` operation.
# Usage: opt_in_phone_number <phoneNumber> <region>
opt_in_phone_number() {
    aws sns opt-in-phone-number \
        --phone-number "$PHONENUMBER" \
        --region "$REGION"
}


# publish: Execute the AWS Amazon SNS `publish` operation.
# Usage: publish <Message> <TopicArn> <TargetArn> <PhoneNumber> <Subject> <MessageStructure> <MessageAttributes> <MessageDeduplicationId> <MessageGroupId> <region>
publish() {
    aws sns publish \
        --message "$MESSAGE" \
        --topic-arn "$TOPICARN" \
        --target-arn "$TARGETARN" \
        --phone-number "$PHONENUMBER" \
        --subject "$SUBJECT" \
        --message-structure "$MESSAGESTRUCTURE" \
        --message-attributes "$MESSAGEATTRIBUTES" \
        --message-deduplication-id "$MESSAGEDEDUPLICATIONID" \
        --message-group-id "$MESSAGEGROUPID"
}


# publish_batch: Execute the AWS Amazon SNS `publish_batch` operation.
# Usage: publish_batch <PublishBatchRequestEntries> <TopicArn> <region>
publish_batch() {
    aws sns publish-batch \
        --topic-arn "$TOPICARN" \
        --publish-batch-request-entries "$PUBLISHBATCHREQUESTENTRIES"
}


# put_data_protection_policy: Execute the AWS Amazon SNS `put_data_protection_policy` operation.
# Usage: put_data_protection_policy <DataProtectionPolicy> <ResourceArn> <region>
put_data_protection_policy() {
    aws sns put-data-protection-policy \
        --data-protection-policy "$DATAPROTECTIONPOLICY" \
        --resource-arn "$RESOURCEARN" \
        --region "$REGION"
}


# set_subscription_attributes: Execute the AWS Amazon SNS `set_subscription_attributes` operation.
# Usage: set_subscription_attributes <AttributeName> <SubscriptionArn> <AttributeValue> <region>
set_subscription_attributes() {
    aws sns set-subscription-attributes \
        --subscription-arn "$SUBSCRIPTIONARN" \
        --attribute-name "$ATTRIBUTENAME" \
        --attribute-value "$ATTRIBUTEVALUE"
}


# set_topic_attributes: Execute the AWS Amazon SNS `set_topic_attributes` operation.
# Usage: set_topic_attributes <AttributeName> <TopicArn> <AttributeValue> <region>
set_topic_attributes() {
    aws sns set-topic-attributes \
        --topic-arn "$TOPICARN" \
        --attribute-name "$ATTRIBUTENAME" \
        --attribute-value "$ATTRIBUTEVALUE"
}


# subscribe: Execute AWS SNS Subscribe. Ensure that you set correct permission policies if required.
# Usage: subscribe <Protocol> <TopicArn> <Endpoint> <Attributes> <ReturnSubscriptionArn> <region>
subscribe() {
    aws sns subscribe \
        --protocol "$PROTOCOL" \
        --topic-arn "$TOPICARN" \
        --endpoint "$ENDPOINT" \
        --attributes "$ATTRIBUTES" \
        --return-subscription-arn "$RETURNSUBSCRIPTIONARN" \
        --region "$REGION"
}


# unsubscribe: Execute the AWS Amazon SNS `unsubscribe` operation.
# Usage: unsubscribe <SubscriptionArn> <region>
unsubscribe() {
    aws sns unsubscribe \
        --subscription-arn "$SUBSCRIPTIONARN"
}


# add_sqs_permission: Execute the AWS Amazon SQS `add_permission` operation.
# Usage: add_sqs_permission <Actions> <AWSAccountIds> <Label> <QueueUrl> <region>
add_sqs_permission() {
    aws sqs add-permission \
        --actions "$ACTIONS" \
        --aws-account-ids "$AWSACCOUNTIDS" \
        --label "$LABEL" \
        --queue-url "$QUEUEURL"
}


# cancel_message_move_task: Execute the AWS Amazon SQS `cancel_message_move_task` operation.
# Usage: cancel_message_move_task <TaskHandle> <region>
cancel_message_move_task() {
    aws sqs cancel-message-move-task \
        --task-handle "$TASKHANDLE" \
        --region "$REGION"
}


# change_message_visibility: Execute the AWS Amazon SQS `change_message_visibility` operation.
# Usage: change_message_visibility <VisibilityTimeout> <ReceiptHandle> <QueueUrl> <region>
change_message_visibility() {
    aws sqs change-message-visibility \
        --visibility-timeout "$VISIBILITYTIMEOUT" \
        --receipt-handle "$RECEIPTHANDLE" \
        --queue-url "$QUEUEURL"
}


# change_message_visibility_batch: Execute the AWS Amazon SQS `change_message_visibility_batch` operation.
# Usage: change_message_visibility_batch <Entries> <QueueUrl> <region>
change_message_visibility_batch() {
    aws sqs change-message-visibility-batch \
        --queue-url "$QUEUEURL" \
        --entries "$ENTRIES"
}


# delete_message: Execute the AWS Amazon SQS `delete_message` operation.
# Usage: delete_message <ReceiptHandle> <QueueUrl> <region>
delete_message() {
    aws sqs delete-message \
        --queue-url "$QUEUEURL" \
        --receipt-handle "$RECEIPTHANDLE"
}


# delete_message_batch: Execute the AWS Amazon SQS `delete_message_batch` operation.
# Usage: delete_message_batch <Entries> <QueueUrl> <region>
delete_message_batch() {
    aws sqs delete-message-batch \
        --queue-url "$QUEUEURL" \
        --entries "$ENTRIES"
}


# get_queue_attributes: Execute the AWS Amazon SQS `get_queue_attributes` operation.
# Usage: get_queue_attributes <QueueUrl> <AttributeNames> <region>
get_queue_attributes() {
    aws sqs get-queue-attributes \
        --queue-url "$QUEUEURL" \
        --attribute-names "$ATTRIBUTENAMES" \
        --region "$REGION"
}


# get_queue_url: Execute the AWS Amazon SQS `get_queue_url` operation.
# Usage: get_queue_url <QueueName> <QueueOwnerAWSAccountId> <region>
get_queue_url() {
    aws sqs get-queue-url \
        --queue-name "$QUEUENAME" \
        --queue-owner-aws-account-id "$QUEUEOWNERAWSACCOUNTID"
}


# list_dead_letter_source_queues: Execute the AWS Amazon SQS `list_dead_letter_source_queues` operation.
# Usage: list_dead_letter_source_queues <QueueUrl> <NextToken> <MaxResults> <region>
list_dead_letter_source_queues() {
    aws sqs list-dead-letter-source-queues \
        --queue-url "$QUEUEURL" \
        --next-token "$NEXTTOKEN" \
        --max-results "$MAXRESULTS"
}


# list_message_move_tasks: Execute the AWS Amazon SQS `list_message_move_tasks` operation.
# Usage: list_message_move_tasks <SourceArn> <MaxResults> <region>
list_message_move_tasks() {
    aws sqs list-message-move-tasks \
        --source-arn "$SOURCEARN" \
        --max-results "$MAXRESULTS" \
        --region "$REGION"
}


# list_queue_tags: Execute the AWS Amazon SQS `list_queue_tags` operation.
# Usage: list_queue_tags <QueueUrl> <region>
list_queue_tags() {
    aws sqs list-queue-tags \
        --queue-url "$QUEUEURL" \
        --region "$REGION"
}


# list_queues: Execute the AWS Amazon SQS `list_queues` operation.
# Usage: list_queues <QueueNamePrefix> <NextToken> <MaxResults> <region>
list_queues() {
    aws sqs list-queues \
        --queue-name-prefix "$QUEUENAMEPREFIX" \
        --next-token "$NEXTTOKEN" \
        --max-results "$MAXRESULTS"
}


# purge_queue: Execute the AWS Amazon SQS `purge_queue` operation.
# Usage: purge_queue <QueueUrl> <region>
purge_queue() {
    aws sqs purge-queue \
        --queue-url "$QUEUEURL" \
        --region "$REGION"
}


# receive_message: Execute the AWS Amazon SQS `receive_message` operation.
# Usage: receive_message <QueueUrl> <AttributeNames> <MessageSystemAttributeNames> <MessageAttributeNames> <MaxNumberOfMessages> <VisibilityTimeout> <WaitTimeSeconds> <ReceiveRequestAttemptId> <region>
receive_message() {
    aws sqs receive-message \
        --queue-url "$QUEUEURL" \
        --attribute-names "$ATTRIBUTENAMES" \
        --message-system-attribute-names "$MESSAGESYSTEMATTRIBUTENAMES" \
        --message-attribute-names "$MESSAGEATTRIBUTENAMES" \
        --max-number-of-messages "$MAXNUMBEROFMESSAGES" \
        --visibility-timeout "$VISIBILITYTIMEOUT" \
        --wait-time-seconds "$WAITTIMESECONDS" \
        --receive-request-attempt-id "$RECEIVEREQUESTATTEMPTID"
}


# remove_sqs_permission: Execute the AWS Amazon SQS `remove_permission` operation.
# Usage: remove_sqs_permission <Label> <QueueUrl> <region>
remove_sqs_permission() {
    aws sqs remove-permission \
        --queue-url "$QUEUEURL" \
        --label "$LABEL" \
        --region "$REGION"
}


# send_message: Execute the AWS Amazon SQS `send_message` operation.
# Usage: send_message <MessageBody> <QueueUrl> <DelaySeconds> <MessageAttributes> <MessageSystemAttributes> <MessageDeduplicationId> <MessageGroupId> <region>
send_message() {
    aws sqs send-message \
        --queue-url "$QUEUEURL" \
        --message-body "$MESSAGEBODY" \
        --delay-seconds "$DELAYSECONDS" \
        --message-attributes "$MESSAGEATTRIBUTES" \
        --message-system-attributes "$MESSAGESYSTEMATTRIBUTES" \
        --message-deduplication-id "$MESSAGEDEDUPLICATIONID" \
        --message-group-id "$MESSAGEGROUPID"
}


# send_message_batch: Execute the AWS Amazon SQS `send_message_batch` operation.
# Usage: send_message_batch <Entries> <QueueUrl> <region>
send_message_batch() {
    aws sqs send-message-batch \
        --queue-url "$QUEUEURL" \
        --entries "$ENTRIES"
}


# set_queue_attributes: Execute the AWS Amazon SQS `set_queue_attributes` operation.
# Usage: set_queue_attributes <Attributes> <QueueUrl> <region>
set_queue_attributes() {
    aws sqs set-queue-attributes \
        --queue-url "$QUEUEURL" \
        --attributes "$ATTRIBUTES"
}


# start_message_move_task: Execute the AWS Amazon SQS `start_message_move_task` operation.
# Usage: start_message_move_task <SourceArn> <DestinationArn> <MaxNumberOfMessagesPerSecond> <region>
start_message_move_task() {
    aws sqs start-message-move-task \
        --source-arn "$SOURCEARN" \
        --destination-arn "$DESTINATIONARN" \
        --max-number-of-messages-per-second "$MAXNUMBEROFMESSAGESPERSECOND"
}


