"""Auto-generated boto3 functions for amazon-location-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def search_places(query: str, max_results: int | None = None, mode: str | None = None, **kwargs) -> dict:
    """Search for places using Amazon Location Service geo-places search_text API. Geocode the query using the geocode API to get BiasPosition. If no results, try a bounding box filter. Includes contact info and opening hours if present. Output is standardized and includes all fields, even if empty or not available."""
    client = boto3.client('location')
    params = {}
    if query is not None:
        params['IndexName'] = query
    if query is not None:
        params['Text'] = query
    if max_results is not None:
        params['MaxResults'] = max_results
    params.update(kwargs)
    return client.search_place_index_for_text(**params)



def get_place(place_id: str, mode: str | None = None, **kwargs) -> dict:
    """Get details for a place using Amazon Location Service geo-places get_place API. Output is standardized and includes all fields, even if empty or not available."""
    client = boto3.client('location')
    params = {}
    if place_id is not None:
        params['PlaceId'] = place_id
    if mode is not None:
        params['IndexName'] = mode
    params.update(kwargs)
    return client.get_place(**params)



def reverse_geocode(longitude: Any, latitude: Any, **kwargs) -> dict:
    """Reverse geocode coordinates to an address using Amazon Location Service geo-places reverse_geocode API."""
    client = boto3.client('location')
    params = {}
    if default is not None:
        params['IndexName'] = default
    if longitude,latitude is not None:
        params['Position'] = longitude,latitude
    params.update(kwargs)
    return client.search_place_index_for_position(**params)



def geocode(location: str, **kwargs) -> dict:
    """Get coordinates for a location name or address using Amazon Location Service geo-places geocode API."""
    client = boto3.client('location')
    params = {}
    if location is not None:
        params['IndexName'] = location
    if location is not None:
        params['Text'] = location
    params.update(kwargs)
    return client.search_place_index_for_text(**params)



def search_nearby(longitude: Any, latitude: Any, max_results: int | None = None, query: str | None = None, radius: int | None = None, **kwargs) -> dict:
    """Search for places near a location using Amazon Location Service geo-places search_nearby API. If no results, expand the radius up to max_radius. Output is standardized and includes all fields, even if empty or not available."""
    client = boto3.client('location')
    params = {}
    if query is not None:
        params['IndexName'] = query
    if ['longitude', 'latitude'] is not None:
        params['Position'] = ['longitude', 'latitude']
    if max_results is not None:
        params['MaxResults'] = max_results
    if radius is not None:
        params['RadiusInMeters'] = radius
    params.update(kwargs)
    return client.search_place_index_for_position(**params)



def search_places_open_now(query: str, initial_radius: int | None = None, **kwargs) -> dict:
    """Search for places that are open now using Amazon Location Service geo-places search_text API and filter by opening hours. If no open places, expand the search radius up to max_radius. Uses BiasPosition from geocode."""
    client = boto3.client('location')
    params = {}
    if query is not None:
        params['IndexName'] = query
    if query is not None:
        params['Text'] = query
    if None is not None:
        params['MaxResults'] = None
    if None is not None:
        params['BiasPosition'] = None
    if None is not None:
        params['FilterBBox'] = None
    if None is not None:
        params['FilterCountries'] = None
    params.update(kwargs)
    return client.search_place_index_for_text(**params)



def calculate_route(departure_position: list, destination_position: list, travel_mode: str | None = None, optimize_for: str | None = None, **kwargs) -> dict:
    """Calculate a route and return summary info and turn-by-turn directions.

    Parameters:
        departure_position: [lon, lat]
        destination_position: [lon, lat]
        travel_mode: 'Car', 'Truck', 'Walking', or 'Bicycle' (default: 'Car')
        optimize_for: 'FastestRoute' or 'ShortestRoute' (default: 'FastestRoute')

    Returns:
        dict with distance, duration, and turn_by_turn directions (list of step summaries).
    """
    client = boto3.client('location')
    params = {}
    if departure_position is not None:
        params['DeparturePosition'] = departure_position
    if destination_position is not None:
        params['DestinationPosition'] = destination_position
    if travel_mode is not None:
        params['TravelMode'] = travel_mode
    if optimize_for is not None:
        params['OptimizeFor'] = optimize_for
    params.update(kwargs)
    return client.calculate_route(**params)



def optimize_waypoints(origin_position: list, destination_position: list, waypoints: list, travel_mode: str | None = None, mode: str | None = None, **kwargs) -> dict:
    """Optimize the order of waypoints using Amazon Location Service geo-routes optimize_waypoints API (V2).

    Returns summary (optimized order, total distance, duration, etc.) or full response if mode='raw'.
    """
    client = boto3.client('location')
    params = {}
    if ctx.config.calculator_name is not None:
        params['CalculatorName'] = ctx.config.calculator_name
    if origin_position is not None:
        params['DeparturePosition'] = origin_position
    if destination_position is not None:
        params['DestinationPosition'] = destination_position
    if waypoints is not None:
        params['Waypoints'] = waypoints
    if travel_mode is not None:
        params['TravelMode'] = travel_mode
    params.update(kwargs)
    return client.calculate_route(**params)



