#!/usr/bin/env bash
# Auto-generated AWS CLI functions for amazon-aurora-dsql-mcp-server
# Generated by mcp-to-cli from MCP tool schemas.
set -euo pipefail

# readonly_query: Run a read-only SQL query against the configured Aurora DSQL cluster.

Aurora DSQL is distributed SQL database with Postgres compatibility. The following table
summarizes `SELECT` functionality that is expected to work. Items not in this table may
also be supported, as this is a point in time snapshot.
| Primary clause                  | Supported clauses     |
|---------------------------------|-----------------------|
| FROM                            |                       |
| GROUP BY                        | ALL, DISTINCT         |
| ORDER BY                        | ASC, DESC, NULLS      |
| LIMIT                           |                       |
| DISTINCT                        |                       |
| HAVING                          |                       |
| USING                           |                       |
| WITH (common table expressions) |                       |
| INNER JOIN                      | ON                    |
| OUTER JOIN                      | LEFT, RIGHT, FULL, ON |
| CROSS JOIN                      | ON                    |
| UNION                           | ALL                   |
| INTERSECT                       | ALL                   |
| EXCEPT                          | ALL                   |
| OVER                            | RANK (), PARTITION BY |
| FOR UPDATE                      |                       |

# Usage: readonly_query <sql>
readonly_query() {
    aws rds-data execute-statement \
        --cluster-arn "$CLUSTER_ARN" \
        --secret-arn "$SECRET_ARN" \
        --sql "$SQL"
}


# get_schema: Get the schema of the given table
# Usage: get_schema <table_name>
get_schema() {
    aws rds describe-db-cluster-endpoints \
        --db-cluster-endpoint-identifier "$TABLE_NAME"
}


# dsql_search_documentation: Search Aurora DSQL documentation
# Usage: dsql_search_documentation <search_phrase> <limit>
dsql_search_documentation() {
    aws rds search-documentation \
        --search-phrase "$SEARCH_PHRASE" \
        --max-results "$LIMIT"
}


