"""Auto-generated boto3 functions for aws-cloudformation-mcp-server.

Generated by mcp-to-cli from MCP tool schemas.
"""
from __future__ import annotations

import boto3
from typing import Any


def get_resource_schema_information(resource_type: str, region: str | None = None, **kwargs) -> dict:
    """Get schema information for an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")

    Returns:
        The resource schema information
    """
    client = boto3.client('cloudformation')
    params = {}
    if resource_type is not None:
        params['Type'] = resource_type
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.describe_type(**params)



def list_resources(resource_type: str, region: str | None = None, **kwargs) -> dict:
    """List AWS resources of a specified type.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket", "AWS::RDS::DBInstance")
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        A list of resource identifiers
    """
    client = boto3.client('cloudformation')
    params = {}
    if resource_type is not None:
        params['StackName'] = resource_type
    params.update(kwargs)
    return client.list_stack_resources(**params)



def get_resource(resource_type: str, identifier: str, region: str | None = None, **kwargs) -> dict:
    """Get details of a specific AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to get (e.g., bucket name for S3 buckets)
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Detailed information about the specified resource with a consistent structure:
        {
            "identifier": The resource identifier,
            "properties": The detailed information about the resource
        }
    """
    client = boto3.client('cloudformation')
    params = {}
    if identifier is not None:
        params['StackName'] = identifier
    if resource_type is not None:
        params['LogicalResourceId'] = resource_type
    if identifier is not None:
        params['StackResourceName'] = identifier
    params.update(kwargs)
    return client.describe_stack_resource(**params)



def update_resource(resource_type: str, identifier: str, patch_document: list | None = None, region: str | None = None, **kwargs) -> dict:
    """Update an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to update
        patch_document: A list of RFC 6902 JSON Patch operations to apply
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the updated resource with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "resource_info": Optional information about the resource properties
        }
    """
    client = boto3.client('cloudformation')
    params = {}
    if identifier is not None:
        params['StackName'] = identifier
    if patch_document is not None:
        params['TemplateBody'] = patch_document
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.update_stack(**params)



def create_resource(resource_type: str, properties: dict, region: str | None = None, **kwargs) -> dict:
    """Create an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        properties: A dictionary of properties for the resource
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the created resource with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "resource_info": Optional information about the resource properties
        }
    """
    client = boto3.client('cloudformation')
    params = {}
    if resource_type is not None:
        params['StackName'] = resource_type
    if properties is not None:
        params['TemplateBody'] = properties
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.create_stack(**params)



def delete_resource(resource_type: str, identifier: str, region: str | None = None, **kwargs) -> dict:
    """Delete an AWS resource.

    Parameters:
        resource_type: The AWS resource type (e.g., "AWS::S3::Bucket")
        identifier: The primary identifier of the resource to delete (e.g., bucket name for S3 buckets)
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Information about the deletion operation with a consistent structure:
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", "NOT_FOUND", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
        }
    """
    client = boto3.client('cloudformation')
    params = {}
    if identifier is not None:
        params['StackName'] = identifier
    params.update(kwargs)
    return client.delete_stack(**params)



def get_resource_request_status(request_token: str, region: str | None = None, **kwargs) -> dict:
    """Get the status of a long running operation with the request token.

    Args:
        request_token: The request_token returned from the long running operation
        region: AWS region to use (e.g., "us-east-1", "us-west-2")

    Returns:
        Detailed information about the request status structured as
        {
            "status": Status of the operation ("SUCCESS", "PENDING", "FAILED", "NOT_FOUND", etc.)
            "resource_type": The AWS resource type
            "identifier": The resource identifier
            "is_complete": Boolean indicating whether the operation is complete
            "status_message": Human-readable message describing the result
            "request_token": A token that allows you to track long running operations via the get_resource_request_status tool
            "error_code": A code associated with any errors if the request failed
            "retry_after": A duration to wait before retrying the request
        }
    """
    client = boto3.client('cloudformation')
    params = {}
    if request_token is not None:
        params['OperationId'] = request_token
    if  is not None:
        params['StackSetName'] = 
    if region is not None:
        params['Region'] = region
    params.update(kwargs)
    return client.describe_stack_set_operation(**params)



def create_template(template_name: str | None = None, resources: str | None = None, output_format: str | None = None, deletion_policy: str | None = None, update_replace_policy: str | None = None, template_id: str | None = None, save_to_file: str | None = None, region: str | None = None, **kwargs) -> dict:
    """Create a CloudFormation template from existing resources using the IaC Generator API.

    This tool allows you to generate CloudFormation templates from existing AWS resources
    that are not already managed by CloudFormation. The template generation process is
    asynchronous, so you can check the status of the process and retrieve the template
    once it's complete. You can pass up to 500 resources at a time.

    Examples:
    1. Start template generation for an S3 bucket:
       create_template(
           template_name="my-template",
           resources=[{"ResourceType": "AWS::S3::Bucket", "ResourceIdentifier": {"BucketName": "my-bucket"}}],
           deletion_policy="RETAIN",
           update_replace_policy="RETAIN"
       )

    2. Check status of template generation:
       create_template(template_id="arn:aws:cloudformation:us-east-1:123456789012:generatedtemplate/abcdef12-3456-7890-abcd-ef1234567890")

    3. Retrieve and save generated template:
       create_template(
           template_id="arn:aws:cloudformation:us-east-1:123456789012:generatedtemplate/abcdef12-3456-7890-abcd-ef1234567890",
           save_to_file="/path/to/template.yaml",
           output_format="YAML"
       )
    """
    client = boto3.client('cloudformation')
    params = {}
    if template_name is not None:
        params['TemplateName'] = template_name
    if resources is not None:
        params['Resources'] = resources
    if output_format is not None:
        params['OutputFormat'] = output_format
    if deletion_policy is not None:
        params['DeletionPolicy'] = deletion_policy
    if update_replace_policy is not None:
        params['UpdateReplacePolicy'] = update_replace_policy
    if template_id is not None:
        params['TemplateId'] = template_id
    params.update(kwargs)
    return client.generate_template(**params)



